package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * CdxCurrentReportView2 generated by hbm2java
 */
public class CdxCurrentReportView2 implements java.io.Serializable {

	private CdxCurrentReportView2Id id;

	public CdxCurrentReportView2() {
	}

	public CdxCurrentReportView2(CdxCurrentReportView2Id id) {
		this.id = id;
	}

	public CdxCurrentReportView2Id getId() {
		return this.id;
	}

	public void setId(CdxCurrentReportView2Id id) {
		this.id = id;
	}

}
