package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ChecklistContentStepViewId generated by hbm2java
 */
public class ChecklistContentStepViewId implements java.io.Serializable {

	private BigDecimal column;
	private String sampleTube;
	private String accessionNumber;
	private String study;
	private String value;
	private String hasComment;
	private String completedBy;
	private String dateCompleted;
	private String lastCol;
	private BigDecimal checklistId;
	private BigDecimal checklistRow;

	public ChecklistContentStepViewId() {
	}

	public ChecklistContentStepViewId(BigDecimal column, String sampleTube,
			String accessionNumber, String study, String value,
			String hasComment, String completedBy, String dateCompleted,
			String lastCol, BigDecimal checklistId, BigDecimal checklistRow) {
		this.column = column;
		this.sampleTube = sampleTube;
		this.accessionNumber = accessionNumber;
		this.study = study;
		this.value = value;
		this.hasComment = hasComment;
		this.completedBy = completedBy;
		this.dateCompleted = dateCompleted;
		this.lastCol = lastCol;
		this.checklistId = checklistId;
		this.checklistRow = checklistRow;
	}

	public BigDecimal getColumn() {
		return this.column;
	}

	public void setColumn(BigDecimal column) {
		this.column = column;
	}

	public String getSampleTube() {
		return this.sampleTube;
	}

	public void setSampleTube(String sampleTube) {
		this.sampleTube = sampleTube;
	}

	public String getAccessionNumber() {
		return this.accessionNumber;
	}

	public void setAccessionNumber(String accessionNumber) {
		this.accessionNumber = accessionNumber;
	}

	public String getStudy() {
		return this.study;
	}

	public void setStudy(String study) {
		this.study = study;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getHasComment() {
		return this.hasComment;
	}

	public void setHasComment(String hasComment) {
		this.hasComment = hasComment;
	}

	public String getCompletedBy() {
		return this.completedBy;
	}

	public void setCompletedBy(String completedBy) {
		this.completedBy = completedBy;
	}

	public String getDateCompleted() {
		return this.dateCompleted;
	}

	public void setDateCompleted(String dateCompleted) {
		this.dateCompleted = dateCompleted;
	}

	public String getLastCol() {
		return this.lastCol;
	}

	public void setLastCol(String lastCol) {
		this.lastCol = lastCol;
	}

	public BigDecimal getChecklistId() {
		return this.checklistId;
	}

	public void setChecklistId(BigDecimal checklistId) {
		this.checklistId = checklistId;
	}

	public BigDecimal getChecklistRow() {
		return this.checklistRow;
	}

	public void setChecklistRow(BigDecimal checklistRow) {
		this.checklistRow = checklistRow;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChecklistContentStepViewId))
			return false;
		ChecklistContentStepViewId castOther = (ChecklistContentStepViewId) other;

		return ((this.getColumn() == castOther.getColumn()) || (this
				.getColumn() != null && castOther.getColumn() != null && this
				.getColumn().equals(castOther.getColumn())))
				&& ((this.getSampleTube() == castOther.getSampleTube()) || (this
						.getSampleTube() != null
						&& castOther.getSampleTube() != null && this
						.getSampleTube().equals(castOther.getSampleTube())))
				&& ((this.getAccessionNumber() == castOther
						.getAccessionNumber()) || (this.getAccessionNumber() != null
						&& castOther.getAccessionNumber() != null && this
						.getAccessionNumber().equals(
								castOther.getAccessionNumber())))
				&& ((this.getStudy() == castOther.getStudy()) || (this
						.getStudy() != null && castOther.getStudy() != null && this
						.getStudy().equals(castOther.getStudy())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null && castOther.getValue() != null && this
						.getValue().equals(castOther.getValue())))
				&& ((this.getHasComment() == castOther.getHasComment()) || (this
						.getHasComment() != null
						&& castOther.getHasComment() != null && this
						.getHasComment().equals(castOther.getHasComment())))
				&& ((this.getCompletedBy() == castOther.getCompletedBy()) || (this
						.getCompletedBy() != null
						&& castOther.getCompletedBy() != null && this
						.getCompletedBy().equals(castOther.getCompletedBy())))
				&& ((this.getDateCompleted() == castOther.getDateCompleted()) || (this
						.getDateCompleted() != null
						&& castOther.getDateCompleted() != null && this
						.getDateCompleted()
						.equals(castOther.getDateCompleted())))
				&& ((this.getLastCol() == castOther.getLastCol()) || (this
						.getLastCol() != null && castOther.getLastCol() != null && this
						.getLastCol().equals(castOther.getLastCol())))
				&& ((this.getChecklistId() == castOther.getChecklistId()) || (this
						.getChecklistId() != null
						&& castOther.getChecklistId() != null && this
						.getChecklistId().equals(castOther.getChecklistId())))
				&& ((this.getChecklistRow() == castOther.getChecklistRow()) || (this
						.getChecklistRow() != null
						&& castOther.getChecklistRow() != null && this
						.getChecklistRow().equals(castOther.getChecklistRow())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getColumn() == null ? 0 : this.getColumn().hashCode());
		result = 37
				* result
				+ (getSampleTube() == null ? 0 : this.getSampleTube()
						.hashCode());
		result = 37
				* result
				+ (getAccessionNumber() == null ? 0 : this.getAccessionNumber()
						.hashCode());
		result = 37 * result
				+ (getStudy() == null ? 0 : this.getStudy().hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37
				* result
				+ (getHasComment() == null ? 0 : this.getHasComment()
						.hashCode());
		result = 37
				* result
				+ (getCompletedBy() == null ? 0 : this.getCompletedBy()
						.hashCode());
		result = 37
				* result
				+ (getDateCompleted() == null ? 0 : this.getDateCompleted()
						.hashCode());
		result = 37 * result
				+ (getLastCol() == null ? 0 : this.getLastCol().hashCode());
		result = 37
				* result
				+ (getChecklistId() == null ? 0 : this.getChecklistId()
						.hashCode());
		result = 37
				* result
				+ (getChecklistRow() == null ? 0 : this.getChecklistRow()
						.hashCode());
		return result;
	}

}
