package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClinicalDataView generated by hbm2java
 */
public class ClinicalDataView implements java.io.Serializable {

	private ClinicalDataViewId id;

	public ClinicalDataView() {
	}

	public ClinicalDataView(ClinicalDataViewId id) {
		this.id = id;
	}

	public ClinicalDataViewId getId() {
		return this.id;
	}

	public void setId(ClinicalDataViewId id) {
		this.id = id;
	}

}
