package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * CompoundReportViewId generated by hbm2java
 */
public class CompoundReportViewId implements java.io.Serializable {

	private BigDecimal studyProtocolId;
	private String compound;
	private String franchise;
	private String cimsTrialCode;
	private BigDecimal numberOfPatients;
	private BigDecimal consentStorage;
	private BigDecimal consentDna;
	private String assayDetails;

	public CompoundReportViewId() {
	}

	public CompoundReportViewId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public CompoundReportViewId(BigDecimal studyProtocolId, String compound,
			String franchise, String cimsTrialCode,
			BigDecimal numberOfPatients, BigDecimal consentStorage,
			BigDecimal consentDna, String assayDetails) {
		this.studyProtocolId = studyProtocolId;
		this.compound = compound;
		this.franchise = franchise;
		this.cimsTrialCode = cimsTrialCode;
		this.numberOfPatients = numberOfPatients;
		this.consentStorage = consentStorage;
		this.consentDna = consentDna;
		this.assayDetails = assayDetails;
	}

	public BigDecimal getStudyProtocolId() {
		return this.studyProtocolId;
	}

	public void setStudyProtocolId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public String getCompound() {
		return this.compound;
	}

	public void setCompound(String compound) {
		this.compound = compound;
	}

	public String getFranchise() {
		return this.franchise;
	}

	public void setFranchise(String franchise) {
		this.franchise = franchise;
	}

	public String getCimsTrialCode() {
		return this.cimsTrialCode;
	}

	public void setCimsTrialCode(String cimsTrialCode) {
		this.cimsTrialCode = cimsTrialCode;
	}

	public BigDecimal getNumberOfPatients() {
		return this.numberOfPatients;
	}

	public void setNumberOfPatients(BigDecimal numberOfPatients) {
		this.numberOfPatients = numberOfPatients;
	}

	public BigDecimal getConsentStorage() {
		return this.consentStorage;
	}

	public void setConsentStorage(BigDecimal consentStorage) {
		this.consentStorage = consentStorage;
	}

	public BigDecimal getConsentDna() {
		return this.consentDna;
	}

	public void setConsentDna(BigDecimal consentDna) {
		this.consentDna = consentDna;
	}

	public String getAssayDetails() {
		return this.assayDetails;
	}

	public void setAssayDetails(String assayDetails) {
		this.assayDetails = assayDetails;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CompoundReportViewId))
			return false;
		CompoundReportViewId castOther = (CompoundReportViewId) other;

		return ((this.getStudyProtocolId() == castOther.getStudyProtocolId()) || (this
				.getStudyProtocolId() != null
				&& castOther.getStudyProtocolId() != null && this
				.getStudyProtocolId().equals(castOther.getStudyProtocolId())))
				&& ((this.getCompound() == castOther.getCompound()) || (this
						.getCompound() != null
						&& castOther.getCompound() != null && this
						.getCompound().equals(castOther.getCompound())))
				&& ((this.getFranchise() == castOther.getFranchise()) || (this
						.getFranchise() != null
						&& castOther.getFranchise() != null && this
						.getFranchise().equals(castOther.getFranchise())))
				&& ((this.getCimsTrialCode() == castOther.getCimsTrialCode()) || (this
						.getCimsTrialCode() != null
						&& castOther.getCimsTrialCode() != null && this
						.getCimsTrialCode()
						.equals(castOther.getCimsTrialCode())))
				&& ((this.getNumberOfPatients() == castOther
						.getNumberOfPatients()) || (this.getNumberOfPatients() != null
						&& castOther.getNumberOfPatients() != null && this
						.getNumberOfPatients().equals(
								castOther.getNumberOfPatients())))
				&& ((this.getConsentStorage() == castOther.getConsentStorage()) || (this
						.getConsentStorage() != null
						&& castOther.getConsentStorage() != null && this
						.getConsentStorage().equals(
								castOther.getConsentStorage())))
				&& ((this.getConsentDna() == castOther.getConsentDna()) || (this
						.getConsentDna() != null
						&& castOther.getConsentDna() != null && this
						.getConsentDna().equals(castOther.getConsentDna())))
				&& ((this.getAssayDetails() == castOther.getAssayDetails()) || (this
						.getAssayDetails() != null
						&& castOther.getAssayDetails() != null && this
						.getAssayDetails().equals(castOther.getAssayDetails())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getStudyProtocolId() == null ? 0 : this.getStudyProtocolId()
						.hashCode());
		result = 37 * result
				+ (getCompound() == null ? 0 : this.getCompound().hashCode());
		result = 37 * result
				+ (getFranchise() == null ? 0 : this.getFranchise().hashCode());
		result = 37
				* result
				+ (getCimsTrialCode() == null ? 0 : this.getCimsTrialCode()
						.hashCode());
		result = 37
				* result
				+ (getNumberOfPatients() == null ? 0 : this
						.getNumberOfPatients().hashCode());
		result = 37
				* result
				+ (getConsentStorage() == null ? 0 : this.getConsentStorage()
						.hashCode());
		result = 37
				* result
				+ (getConsentDna() == null ? 0 : this.getConsentDna()
						.hashCode());
		result = 37
				* result
				+ (getAssayDetails() == null ? 0 : this.getAssayDetails()
						.hashCode());
		return result;
	}

}
