package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ConfigAttrDisplayViewId generated by hbm2java
 */
public class ConfigAttrDisplayViewId implements java.io.Serializable {

	private String attributeName;
	private String objectType;
	private String attributeType;
	private Character lastCol;
	private BigDecimal configAttributeId;
	private BigDecimal variableId;

	public ConfigAttrDisplayViewId() {
	}

	public ConfigAttrDisplayViewId(String attributeName, String objectType,
			String attributeType, BigDecimal configAttributeId,
			BigDecimal variableId) {
		this.attributeName = attributeName;
		this.objectType = objectType;
		this.attributeType = attributeType;
		this.configAttributeId = configAttributeId;
		this.variableId = variableId;
	}

	public ConfigAttrDisplayViewId(String attributeName, String objectType,
			String attributeType, Character lastCol,
			BigDecimal configAttributeId, BigDecimal variableId) {
		this.attributeName = attributeName;
		this.objectType = objectType;
		this.attributeType = attributeType;
		this.lastCol = lastCol;
		this.configAttributeId = configAttributeId;
		this.variableId = variableId;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	public String getAttributeType() {
		return this.attributeType;
	}

	public void setAttributeType(String attributeType) {
		this.attributeType = attributeType;
	}

	public Character getLastCol() {
		return this.lastCol;
	}

	public void setLastCol(Character lastCol) {
		this.lastCol = lastCol;
	}

	public BigDecimal getConfigAttributeId() {
		return this.configAttributeId;
	}

	public void setConfigAttributeId(BigDecimal configAttributeId) {
		this.configAttributeId = configAttributeId;
	}

	public BigDecimal getVariableId() {
		return this.variableId;
	}

	public void setVariableId(BigDecimal variableId) {
		this.variableId = variableId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfigAttrDisplayViewId))
			return false;
		ConfigAttrDisplayViewId castOther = (ConfigAttrDisplayViewId) other;

		return ((this.getAttributeName() == castOther.getAttributeName()) || (this
				.getAttributeName() != null
				&& castOther.getAttributeName() != null && this
				.getAttributeName().equals(castOther.getAttributeName())))
				&& ((this.getObjectType() == castOther.getObjectType()) || (this
						.getObjectType() != null
						&& castOther.getObjectType() != null && this
						.getObjectType().equals(castOther.getObjectType())))
				&& ((this.getAttributeType() == castOther.getAttributeType()) || (this
						.getAttributeType() != null
						&& castOther.getAttributeType() != null && this
						.getAttributeType()
						.equals(castOther.getAttributeType())))
				&& ((this.getLastCol() == castOther.getLastCol()) || (this
						.getLastCol() != null && castOther.getLastCol() != null && this
						.getLastCol().equals(castOther.getLastCol())))
				&& ((this.getConfigAttributeId() == castOther
						.getConfigAttributeId()) || (this
						.getConfigAttributeId() != null
						&& castOther.getConfigAttributeId() != null && this
						.getConfigAttributeId().equals(
								castOther.getConfigAttributeId())))
				&& ((this.getVariableId() == castOther.getVariableId()) || (this
						.getVariableId() != null
						&& castOther.getVariableId() != null && this
						.getVariableId().equals(castOther.getVariableId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAttributeName() == null ? 0 : this.getAttributeName()
						.hashCode());
		result = 37
				* result
				+ (getObjectType() == null ? 0 : this.getObjectType()
						.hashCode());
		result = 37
				* result
				+ (getAttributeType() == null ? 0 : this.getAttributeType()
						.hashCode());
		result = 37 * result
				+ (getLastCol() == null ? 0 : this.getLastCol().hashCode());
		result = 37
				* result
				+ (getConfigAttributeId() == null ? 0 : this
						.getConfigAttributeId().hashCode());
		result = 37
				* result
				+ (getVariableId() == null ? 0 : this.getVariableId()
						.hashCode());
		return result;
	}

}
