package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * CostForecastView generated by hbm2java
 */
public class CostForecastView implements java.io.Serializable {

	private CostForecastViewId id;

	public CostForecastView() {
	}

	public CostForecastView(CostForecastViewId id) {
		this.id = id;
	}

	public CostForecastViewId getId() {
		return this.id;
	}

	public void setId(CostForecastViewId id) {
		this.id = id;
	}

}
