package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * DilutionView generated by hbm2java
 */
public class DilutionView implements java.io.Serializable {

	private DilutionViewId id;

	public DilutionView() {
	}

	public DilutionView(DilutionViewId id) {
		this.id = id;
	}

	public DilutionViewId getId() {
		return this.id;
	}

	public void setId(DilutionViewId id) {
		this.id = id;
	}

}
