package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * DiscreteAttributeViewId generated by hbm2java
 */
public class DiscreteAttributeViewId implements java.io.Serializable {

	private String attributeName;
	private String attributeValue;
	private BigDecimal numberInSequence;
	private Boolean global;
	private BigDecimal subsidiaryId;

	public DiscreteAttributeViewId() {
	}

	public DiscreteAttributeViewId(String attributeName,
			BigDecimal numberInSequence, BigDecimal subsidiaryId) {
		this.attributeName = attributeName;
		this.numberInSequence = numberInSequence;
		this.subsidiaryId = subsidiaryId;
	}

	public DiscreteAttributeViewId(String attributeName, String attributeValue,
			BigDecimal numberInSequence, Boolean global, BigDecimal subsidiaryId) {
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
		this.numberInSequence = numberInSequence;
		this.global = global;
		this.subsidiaryId = subsidiaryId;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

	public BigDecimal getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(BigDecimal numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	public Boolean getGlobal() {
		return this.global;
	}

	public void setGlobal(Boolean global) {
		this.global = global;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DiscreteAttributeViewId))
			return false;
		DiscreteAttributeViewId castOther = (DiscreteAttributeViewId) other;

		return ((this.getAttributeName() == castOther.getAttributeName()) || (this
				.getAttributeName() != null
				&& castOther.getAttributeName() != null && this
				.getAttributeName().equals(castOther.getAttributeName())))
				&& ((this.getAttributeValue() == castOther.getAttributeValue()) || (this
						.getAttributeValue() != null
						&& castOther.getAttributeValue() != null && this
						.getAttributeValue().equals(
								castOther.getAttributeValue())))
				&& ((this.getNumberInSequence() == castOther
						.getNumberInSequence()) || (this.getNumberInSequence() != null
						&& castOther.getNumberInSequence() != null && this
						.getNumberInSequence().equals(
								castOther.getNumberInSequence())))
				&& ((this.getGlobal() == castOther.getGlobal()) || (this
						.getGlobal() != null && castOther.getGlobal() != null && this
						.getGlobal().equals(castOther.getGlobal())))
				&& ((this.getSubsidiaryId() == castOther.getSubsidiaryId()) || (this
						.getSubsidiaryId() != null
						&& castOther.getSubsidiaryId() != null && this
						.getSubsidiaryId().equals(castOther.getSubsidiaryId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAttributeName() == null ? 0 : this.getAttributeName()
						.hashCode());
		result = 37
				* result
				+ (getAttributeValue() == null ? 0 : this.getAttributeValue()
						.hashCode());
		result = 37
				* result
				+ (getNumberInSequence() == null ? 0 : this
						.getNumberInSequence().hashCode());
		result = 37 * result
				+ (getGlobal() == null ? 0 : this.getGlobal().hashCode());
		result = 37
				* result
				+ (getSubsidiaryId() == null ? 0 : this.getSubsidiaryId()
						.hashCode());
		return result;
	}

}
