package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * EventInfoViewId generated by hbm2java
 */
public class EventInfoViewId implements java.io.Serializable {

	private String eventName;
	private String eventDescription;
	private String objectType;
	private Boolean isWarning;
	private Date dateProcessed;
	private String processedBy;
	private String message;
	private String storedProcedure;
	private String procDescription;
	private String objectId;
	private BigDecimal eventId;
	private BigDecimal eventHandlerId;
	private BigDecimal eventSubscriptionId;
	private BigDecimal eventProcessId;
	private Date dateProcessedTrunc;

	public EventInfoViewId() {
	}

	public EventInfoViewId(String eventName, String eventDescription,
			String storedProcedure, BigDecimal eventId,
			BigDecimal eventHandlerId, BigDecimal eventSubscriptionId) {
		this.eventName = eventName;
		this.eventDescription = eventDescription;
		this.storedProcedure = storedProcedure;
		this.eventId = eventId;
		this.eventHandlerId = eventHandlerId;
		this.eventSubscriptionId = eventSubscriptionId;
	}

	public EventInfoViewId(String eventName, String eventDescription,
			String objectType, Boolean isWarning, Date dateProcessed,
			String processedBy, String message, String storedProcedure,
			String procDescription, String objectId, BigDecimal eventId,
			BigDecimal eventHandlerId, BigDecimal eventSubscriptionId,
			BigDecimal eventProcessId, Date dateProcessedTrunc) {
		this.eventName = eventName;
		this.eventDescription = eventDescription;
		this.objectType = objectType;
		this.isWarning = isWarning;
		this.dateProcessed = dateProcessed;
		this.processedBy = processedBy;
		this.message = message;
		this.storedProcedure = storedProcedure;
		this.procDescription = procDescription;
		this.objectId = objectId;
		this.eventId = eventId;
		this.eventHandlerId = eventHandlerId;
		this.eventSubscriptionId = eventSubscriptionId;
		this.eventProcessId = eventProcessId;
		this.dateProcessedTrunc = dateProcessedTrunc;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public String getEventDescription() {
		return this.eventDescription;
	}

	public void setEventDescription(String eventDescription) {
		this.eventDescription = eventDescription;
	}

	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	public Boolean getIsWarning() {
		return this.isWarning;
	}

	public void setIsWarning(Boolean isWarning) {
		this.isWarning = isWarning;
	}

	public Date getDateProcessed() {
		return this.dateProcessed;
	}

	public void setDateProcessed(Date dateProcessed) {
		this.dateProcessed = dateProcessed;
	}

	public String getProcessedBy() {
		return this.processedBy;
	}

	public void setProcessedBy(String processedBy) {
		this.processedBy = processedBy;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getStoredProcedure() {
		return this.storedProcedure;
	}

	public void setStoredProcedure(String storedProcedure) {
		this.storedProcedure = storedProcedure;
	}

	public String getProcDescription() {
		return this.procDescription;
	}

	public void setProcDescription(String procDescription) {
		this.procDescription = procDescription;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public BigDecimal getEventId() {
		return this.eventId;
	}

	public void setEventId(BigDecimal eventId) {
		this.eventId = eventId;
	}

	public BigDecimal getEventHandlerId() {
		return this.eventHandlerId;
	}

	public void setEventHandlerId(BigDecimal eventHandlerId) {
		this.eventHandlerId = eventHandlerId;
	}

	public BigDecimal getEventSubscriptionId() {
		return this.eventSubscriptionId;
	}

	public void setEventSubscriptionId(BigDecimal eventSubscriptionId) {
		this.eventSubscriptionId = eventSubscriptionId;
	}

	public BigDecimal getEventProcessId() {
		return this.eventProcessId;
	}

	public void setEventProcessId(BigDecimal eventProcessId) {
		this.eventProcessId = eventProcessId;
	}

	public Date getDateProcessedTrunc() {
		return this.dateProcessedTrunc;
	}

	public void setDateProcessedTrunc(Date dateProcessedTrunc) {
		this.dateProcessedTrunc = dateProcessedTrunc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EventInfoViewId))
			return false;
		EventInfoViewId castOther = (EventInfoViewId) other;

		return ((this.getEventName() == castOther.getEventName()) || (this
				.getEventName() != null && castOther.getEventName() != null && this
				.getEventName().equals(castOther.getEventName())))
				&& ((this.getEventDescription() == castOther
						.getEventDescription()) || (this.getEventDescription() != null
						&& castOther.getEventDescription() != null && this
						.getEventDescription().equals(
								castOther.getEventDescription())))
				&& ((this.getObjectType() == castOther.getObjectType()) || (this
						.getObjectType() != null
						&& castOther.getObjectType() != null && this
						.getObjectType().equals(castOther.getObjectType())))
				&& ((this.getIsWarning() == castOther.getIsWarning()) || (this
						.getIsWarning() != null
						&& castOther.getIsWarning() != null && this
						.getIsWarning().equals(castOther.getIsWarning())))
				&& ((this.getDateProcessed() == castOther.getDateProcessed()) || (this
						.getDateProcessed() != null
						&& castOther.getDateProcessed() != null && this
						.getDateProcessed()
						.equals(castOther.getDateProcessed())))
				&& ((this.getProcessedBy() == castOther.getProcessedBy()) || (this
						.getProcessedBy() != null
						&& castOther.getProcessedBy() != null && this
						.getProcessedBy().equals(castOther.getProcessedBy())))
				&& ((this.getMessage() == castOther.getMessage()) || (this
						.getMessage() != null && castOther.getMessage() != null && this
						.getMessage().equals(castOther.getMessage())))
				&& ((this.getStoredProcedure() == castOther
						.getStoredProcedure()) || (this.getStoredProcedure() != null
						&& castOther.getStoredProcedure() != null && this
						.getStoredProcedure().equals(
								castOther.getStoredProcedure())))
				&& ((this.getProcDescription() == castOther
						.getProcDescription()) || (this.getProcDescription() != null
						&& castOther.getProcDescription() != null && this
						.getProcDescription().equals(
								castOther.getProcDescription())))
				&& ((this.getObjectId() == castOther.getObjectId()) || (this
						.getObjectId() != null
						&& castOther.getObjectId() != null && this
						.getObjectId().equals(castOther.getObjectId())))
				&& ((this.getEventId() == castOther.getEventId()) || (this
						.getEventId() != null && castOther.getEventId() != null && this
						.getEventId().equals(castOther.getEventId())))
				&& ((this.getEventHandlerId() == castOther.getEventHandlerId()) || (this
						.getEventHandlerId() != null
						&& castOther.getEventHandlerId() != null && this
						.getEventHandlerId().equals(
								castOther.getEventHandlerId())))
				&& ((this.getEventSubscriptionId() == castOther
						.getEventSubscriptionId()) || (this
						.getEventSubscriptionId() != null
						&& castOther.getEventSubscriptionId() != null && this
						.getEventSubscriptionId().equals(
								castOther.getEventSubscriptionId())))
				&& ((this.getEventProcessId() == castOther.getEventProcessId()) || (this
						.getEventProcessId() != null
						&& castOther.getEventProcessId() != null && this
						.getEventProcessId().equals(
								castOther.getEventProcessId())))
				&& ((this.getDateProcessedTrunc() == castOther
						.getDateProcessedTrunc()) || (this
						.getDateProcessedTrunc() != null
						&& castOther.getDateProcessedTrunc() != null && this
						.getDateProcessedTrunc().equals(
								castOther.getDateProcessedTrunc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEventName() == null ? 0 : this.getEventName().hashCode());
		result = 37
				* result
				+ (getEventDescription() == null ? 0 : this
						.getEventDescription().hashCode());
		result = 37
				* result
				+ (getObjectType() == null ? 0 : this.getObjectType()
						.hashCode());
		result = 37 * result
				+ (getIsWarning() == null ? 0 : this.getIsWarning().hashCode());
		result = 37
				* result
				+ (getDateProcessed() == null ? 0 : this.getDateProcessed()
						.hashCode());
		result = 37
				* result
				+ (getProcessedBy() == null ? 0 : this.getProcessedBy()
						.hashCode());
		result = 37 * result
				+ (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37
				* result
				+ (getStoredProcedure() == null ? 0 : this.getStoredProcedure()
						.hashCode());
		result = 37
				* result
				+ (getProcDescription() == null ? 0 : this.getProcDescription()
						.hashCode());
		result = 37 * result
				+ (getObjectId() == null ? 0 : this.getObjectId().hashCode());
		result = 37 * result
				+ (getEventId() == null ? 0 : this.getEventId().hashCode());
		result = 37
				* result
				+ (getEventHandlerId() == null ? 0 : this.getEventHandlerId()
						.hashCode());
		result = 37
				* result
				+ (getEventSubscriptionId() == null ? 0 : this
						.getEventSubscriptionId().hashCode());
		result = 37
				* result
				+ (getEventProcessId() == null ? 0 : this.getEventProcessId()
						.hashCode());
		result = 37
				* result
				+ (getDateProcessedTrunc() == null ? 0 : this
						.getDateProcessedTrunc().hashCode());
		return result;
	}

}
