package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * FtaCardReaderView generated by hbm2java
 */
public class FtaCardReaderView implements java.io.Serializable {

	private FtaCardReaderViewId id;

	public FtaCardReaderView() {
	}

	public FtaCardReaderView(FtaCardReaderViewId id) {
		this.id = id;
	}

	public FtaCardReaderViewId getId() {
		return this.id;
	}

	public void setId(FtaCardReaderViewId id) {
		this.id = id;
	}

}
