package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * InformedConsentView generated by hbm2java
 */
public class InformedConsentView implements java.io.Serializable {

	private InformedConsentViewId id;

	public InformedConsentView() {
	}

	public InformedConsentView(InformedConsentViewId id) {
		this.id = id;
	}

	public InformedConsentViewId getId() {
		return this.id;
	}

	public void setId(InformedConsentViewId id) {
		this.id = id;
	}

}
