package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * MasterMixSetupViewId generated by hbm2java
 */
public class MasterMixSetupViewId implements java.io.Serializable {

	private String mixName;
	private String version;
	private String status;
	private String lastCol;
	private BigDecimal volume;
	private BigDecimal masterMixId;
	private String comments;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private String calculateBy;

	public MasterMixSetupViewId() {
	}

	public MasterMixSetupViewId(BigDecimal masterMixId, String createdBy,
			Date dateCreated) {
		this.masterMixId = masterMixId;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public MasterMixSetupViewId(String mixName, String version, String status,
			String lastCol, BigDecimal volume, BigDecimal masterMixId,
			String comments, String createdBy, Date dateCreated,
			String modifiedBy, Date dateModified, String calculateBy) {
		this.mixName = mixName;
		this.version = version;
		this.status = status;
		this.lastCol = lastCol;
		this.volume = volume;
		this.masterMixId = masterMixId;
		this.comments = comments;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.calculateBy = calculateBy;
	}

	public String getMixName() {
		return this.mixName;
	}

	public void setMixName(String mixName) {
		this.mixName = mixName;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getLastCol() {
		return this.lastCol;
	}

	public void setLastCol(String lastCol) {
		this.lastCol = lastCol;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public BigDecimal getMasterMixId() {
		return this.masterMixId;
	}

	public void setMasterMixId(BigDecimal masterMixId) {
		this.masterMixId = masterMixId;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getCalculateBy() {
		return this.calculateBy;
	}

	public void setCalculateBy(String calculateBy) {
		this.calculateBy = calculateBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MasterMixSetupViewId))
			return false;
		MasterMixSetupViewId castOther = (MasterMixSetupViewId) other;

		return ((this.getMixName() == castOther.getMixName()) || (this
				.getMixName() != null && castOther.getMixName() != null && this
				.getMixName().equals(castOther.getMixName())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getLastCol() == castOther.getLastCol()) || (this
						.getLastCol() != null && castOther.getLastCol() != null && this
						.getLastCol().equals(castOther.getLastCol())))
				&& ((this.getVolume() == castOther.getVolume()) || (this
						.getVolume() != null && castOther.getVolume() != null && this
						.getVolume().equals(castOther.getVolume())))
				&& ((this.getMasterMixId() == castOther.getMasterMixId()) || (this
						.getMasterMixId() != null
						&& castOther.getMasterMixId() != null && this
						.getMasterMixId().equals(castOther.getMasterMixId())))
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
						.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this
						.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getDateCreated() == castOther.getDateCreated()) || (this
						.getDateCreated() != null
						&& castOther.getDateCreated() != null && this
						.getDateCreated().equals(castOther.getDateCreated())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this
						.getModifiedBy() != null
						&& castOther.getModifiedBy() != null && this
						.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getDateModified() == castOther.getDateModified()) || (this
						.getDateModified() != null
						&& castOther.getDateModified() != null && this
						.getDateModified().equals(castOther.getDateModified())))
				&& ((this.getCalculateBy() == castOther.getCalculateBy()) || (this
						.getCalculateBy() != null
						&& castOther.getCalculateBy() != null && this
						.getCalculateBy().equals(castOther.getCalculateBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMixName() == null ? 0 : this.getMixName().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getLastCol() == null ? 0 : this.getLastCol().hashCode());
		result = 37 * result
				+ (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37
				* result
				+ (getMasterMixId() == null ? 0 : this.getMasterMixId()
						.hashCode());
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37 * result
				+ (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37
				* result
				+ (getDateCreated() == null ? 0 : this.getDateCreated()
						.hashCode());
		result = 37
				* result
				+ (getModifiedBy() == null ? 0 : this.getModifiedBy()
						.hashCode());
		result = 37
				* result
				+ (getDateModified() == null ? 0 : this.getDateModified()
						.hashCode());
		result = 37
				* result
				+ (getCalculateBy() == null ? 0 : this.getCalculateBy()
						.hashCode());
		return result;
	}

}
