package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * MdbGene generated by hbm2java
 */
public class MdbGene implements java.io.Serializable {

	private MdbGeneId id;

	public MdbGene() {
	}

	public MdbGene(MdbGeneId id) {
		this.id = id;
	}

	public MdbGeneId getId() {
		return this.id;
	}

	public void setId(MdbGeneId id) {
		this.id = id;
	}

}
