package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;

/**
 * MdbGeneId generated by hbm2java
 */
public class MdbGeneId implements java.io.Serializable {

	private BigDecimal geneId;
	private String name;
	private String hugoSymbol;
	private String description;
	private Clob sequence;
	private String organism;
	private String range;
	private String ensemblId;

	public MdbGeneId() {
	}

	public MdbGeneId(BigDecimal geneId, String name) {
		this.geneId = geneId;
		this.name = name;
	}

	public MdbGeneId(BigDecimal geneId, String name, String hugoSymbol,
			String description, Clob sequence, String organism, String range,
			String ensemblId) {
		this.geneId = geneId;
		this.name = name;
		this.hugoSymbol = hugoSymbol;
		this.description = description;
		this.sequence = sequence;
		this.organism = organism;
		this.range = range;
		this.ensemblId = ensemblId;
	}

	public BigDecimal getGeneId() {
		return this.geneId;
	}

	public void setGeneId(BigDecimal geneId) {
		this.geneId = geneId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHugoSymbol() {
		return this.hugoSymbol;
	}

	public void setHugoSymbol(String hugoSymbol) {
		this.hugoSymbol = hugoSymbol;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Clob getSequence() {
		return this.sequence;
	}

	public void setSequence(Clob sequence) {
		this.sequence = sequence;
	}

	public String getOrganism() {
		return this.organism;
	}

	public void setOrganism(String organism) {
		this.organism = organism;
	}

	public String getRange() {
		return this.range;
	}

	public void setRange(String range) {
		this.range = range;
	}

	public String getEnsemblId() {
		return this.ensemblId;
	}

	public void setEnsemblId(String ensemblId) {
		this.ensemblId = ensemblId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MdbGeneId))
			return false;
		MdbGeneId castOther = (MdbGeneId) other;

		return ((this.getGeneId() == castOther.getGeneId()) || (this
				.getGeneId() != null && castOther.getGeneId() != null && this
				.getGeneId().equals(castOther.getGeneId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getHugoSymbol() == castOther.getHugoSymbol()) || (this
						.getHugoSymbol() != null
						&& castOther.getHugoSymbol() != null && this
						.getHugoSymbol().equals(castOther.getHugoSymbol())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getSequence() == castOther.getSequence()) || (this
						.getSequence() != null
						&& castOther.getSequence() != null && this
						.getSequence().equals(castOther.getSequence())))
				&& ((this.getOrganism() == castOther.getOrganism()) || (this
						.getOrganism() != null
						&& castOther.getOrganism() != null && this
						.getOrganism().equals(castOther.getOrganism())))
				&& ((this.getRange() == castOther.getRange()) || (this
						.getRange() != null && castOther.getRange() != null && this
						.getRange().equals(castOther.getRange())))
				&& ((this.getEnsemblId() == castOther.getEnsemblId()) || (this
						.getEnsemblId() != null
						&& castOther.getEnsemblId() != null && this
						.getEnsemblId().equals(castOther.getEnsemblId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGeneId() == null ? 0 : this.getGeneId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getHugoSymbol() == null ? 0 : this.getHugoSymbol()
						.hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getSequence() == null ? 0 : this.getSequence().hashCode());
		result = 37 * result
				+ (getOrganism() == null ? 0 : this.getOrganism().hashCode());
		result = 37 * result
				+ (getRange() == null ? 0 : this.getRange().hashCode());
		result = 37 * result
				+ (getEnsemblId() == null ? 0 : this.getEnsemblId().hashCode());
		return result;
	}

}
