package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * MSampleReceptionViewId generated by hbm2java
 */
public class MSampleReceptionViewId implements java.io.Serializable {

	private BigDecimal sampleReceptionId;
	private BigDecimal shipmentNo;
	private BigDecimal checklistId;
	private Date dateShipmentExpected;
	private BigDecimal studyProtocolId;
	private BigDecimal noSampleExpected;
	private String shippedSampleType;
	private BigDecimal organizationId;
	private String trackingNumbers;
	private BigDecimal contactId;
	private String receivedBy;
	private Date dateReceived;
	private String studyNumber;
	private String sponsorStudyNumber;
	private String studyDirector;
	private String contactName;
	private String sampleCondition;
	private String volume;
	private Date dateAccessioned;
	private String accessionedBy;
	private String sampleTubeId;
	private String location;
	private String company;
	private BigDecimal autoaccessionLoadId;
	private BigDecimal pendingSampleId;
	private BigDecimal sampleId;
	private Date dateReceivedTrunc;
	private Date dateAccessionedTrunc;

	public MSampleReceptionViewId() {
	}

	public MSampleReceptionViewId(BigDecimal sampleReceptionId,
			BigDecimal shipmentNo, BigDecimal checklistId,
			String studyDirector, String contactName, String company) {
		this.sampleReceptionId = sampleReceptionId;
		this.shipmentNo = shipmentNo;
		this.checklistId = checklistId;
		this.studyDirector = studyDirector;
		this.contactName = contactName;
		this.company = company;
	}

	public MSampleReceptionViewId(BigDecimal sampleReceptionId,
			BigDecimal shipmentNo, BigDecimal checklistId,
			Date dateShipmentExpected, BigDecimal studyProtocolId,
			BigDecimal noSampleExpected, String shippedSampleType,
			BigDecimal organizationId, String trackingNumbers,
			BigDecimal contactId, String receivedBy, Date dateReceived,
			String studyNumber, String sponsorStudyNumber,
			String studyDirector, String contactName, String sampleCondition,
			String volume, Date dateAccessioned, String accessionedBy,
			String sampleTubeId, String location, String company,
			BigDecimal autoaccessionLoadId, BigDecimal pendingSampleId,
			BigDecimal sampleId, Date dateReceivedTrunc,
			Date dateAccessionedTrunc) {
		this.sampleReceptionId = sampleReceptionId;
		this.shipmentNo = shipmentNo;
		this.checklistId = checklistId;
		this.dateShipmentExpected = dateShipmentExpected;
		this.studyProtocolId = studyProtocolId;
		this.noSampleExpected = noSampleExpected;
		this.shippedSampleType = shippedSampleType;
		this.organizationId = organizationId;
		this.trackingNumbers = trackingNumbers;
		this.contactId = contactId;
		this.receivedBy = receivedBy;
		this.dateReceived = dateReceived;
		this.studyNumber = studyNumber;
		this.sponsorStudyNumber = sponsorStudyNumber;
		this.studyDirector = studyDirector;
		this.contactName = contactName;
		this.sampleCondition = sampleCondition;
		this.volume = volume;
		this.dateAccessioned = dateAccessioned;
		this.accessionedBy = accessionedBy;
		this.sampleTubeId = sampleTubeId;
		this.location = location;
		this.company = company;
		this.autoaccessionLoadId = autoaccessionLoadId;
		this.pendingSampleId = pendingSampleId;
		this.sampleId = sampleId;
		this.dateReceivedTrunc = dateReceivedTrunc;
		this.dateAccessionedTrunc = dateAccessionedTrunc;
	}

	public BigDecimal getSampleReceptionId() {
		return this.sampleReceptionId;
	}

	public void setSampleReceptionId(BigDecimal sampleReceptionId) {
		this.sampleReceptionId = sampleReceptionId;
	}

	public BigDecimal getShipmentNo() {
		return this.shipmentNo;
	}

	public void setShipmentNo(BigDecimal shipmentNo) {
		this.shipmentNo = shipmentNo;
	}

	public BigDecimal getChecklistId() {
		return this.checklistId;
	}

	public void setChecklistId(BigDecimal checklistId) {
		this.checklistId = checklistId;
	}

	public Date getDateShipmentExpected() {
		return this.dateShipmentExpected;
	}

	public void setDateShipmentExpected(Date dateShipmentExpected) {
		this.dateShipmentExpected = dateShipmentExpected;
	}

	public BigDecimal getStudyProtocolId() {
		return this.studyProtocolId;
	}

	public void setStudyProtocolId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public BigDecimal getNoSampleExpected() {
		return this.noSampleExpected;
	}

	public void setNoSampleExpected(BigDecimal noSampleExpected) {
		this.noSampleExpected = noSampleExpected;
	}

	public String getShippedSampleType() {
		return this.shippedSampleType;
	}

	public void setShippedSampleType(String shippedSampleType) {
		this.shippedSampleType = shippedSampleType;
	}

	public BigDecimal getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(BigDecimal organizationId) {
		this.organizationId = organizationId;
	}

	public String getTrackingNumbers() {
		return this.trackingNumbers;
	}

	public void setTrackingNumbers(String trackingNumbers) {
		this.trackingNumbers = trackingNumbers;
	}

	public BigDecimal getContactId() {
		return this.contactId;
	}

	public void setContactId(BigDecimal contactId) {
		this.contactId = contactId;
	}

	public String getReceivedBy() {
		return this.receivedBy;
	}

	public void setReceivedBy(String receivedBy) {
		this.receivedBy = receivedBy;
	}

	public Date getDateReceived() {
		return this.dateReceived;
	}

	public void setDateReceived(Date dateReceived) {
		this.dateReceived = dateReceived;
	}

	public String getStudyNumber() {
		return this.studyNumber;
	}

	public void setStudyNumber(String studyNumber) {
		this.studyNumber = studyNumber;
	}

	public String getSponsorStudyNumber() {
		return this.sponsorStudyNumber;
	}

	public void setSponsorStudyNumber(String sponsorStudyNumber) {
		this.sponsorStudyNumber = sponsorStudyNumber;
	}

	public String getStudyDirector() {
		return this.studyDirector;
	}

	public void setStudyDirector(String studyDirector) {
		this.studyDirector = studyDirector;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getSampleCondition() {
		return this.sampleCondition;
	}

	public void setSampleCondition(String sampleCondition) {
		this.sampleCondition = sampleCondition;
	}

	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	public Date getDateAccessioned() {
		return this.dateAccessioned;
	}

	public void setDateAccessioned(Date dateAccessioned) {
		this.dateAccessioned = dateAccessioned;
	}

	public String getAccessionedBy() {
		return this.accessionedBy;
	}

	public void setAccessionedBy(String accessionedBy) {
		this.accessionedBy = accessionedBy;
	}

	public String getSampleTubeId() {
		return this.sampleTubeId;
	}

	public void setSampleTubeId(String sampleTubeId) {
		this.sampleTubeId = sampleTubeId;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public BigDecimal getAutoaccessionLoadId() {
		return this.autoaccessionLoadId;
	}

	public void setAutoaccessionLoadId(BigDecimal autoaccessionLoadId) {
		this.autoaccessionLoadId = autoaccessionLoadId;
	}

	public BigDecimal getPendingSampleId() {
		return this.pendingSampleId;
	}

	public void setPendingSampleId(BigDecimal pendingSampleId) {
		this.pendingSampleId = pendingSampleId;
	}

	public BigDecimal getSampleId() {
		return this.sampleId;
	}

	public void setSampleId(BigDecimal sampleId) {
		this.sampleId = sampleId;
	}

	public Date getDateReceivedTrunc() {
		return this.dateReceivedTrunc;
	}

	public void setDateReceivedTrunc(Date dateReceivedTrunc) {
		this.dateReceivedTrunc = dateReceivedTrunc;
	}

	public Date getDateAccessionedTrunc() {
		return this.dateAccessionedTrunc;
	}

	public void setDateAccessionedTrunc(Date dateAccessionedTrunc) {
		this.dateAccessionedTrunc = dateAccessionedTrunc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MSampleReceptionViewId))
			return false;
		MSampleReceptionViewId castOther = (MSampleReceptionViewId) other;

		return ((this.getSampleReceptionId() == castOther
				.getSampleReceptionId()) || (this.getSampleReceptionId() != null
				&& castOther.getSampleReceptionId() != null && this
				.getSampleReceptionId()
				.equals(castOther.getSampleReceptionId())))
				&& ((this.getShipmentNo() == castOther.getShipmentNo()) || (this
						.getShipmentNo() != null
						&& castOther.getShipmentNo() != null && this
						.getShipmentNo().equals(castOther.getShipmentNo())))
				&& ((this.getChecklistId() == castOther.getChecklistId()) || (this
						.getChecklistId() != null
						&& castOther.getChecklistId() != null && this
						.getChecklistId().equals(castOther.getChecklistId())))
				&& ((this.getDateShipmentExpected() == castOther
						.getDateShipmentExpected()) || (this
						.getDateShipmentExpected() != null
						&& castOther.getDateShipmentExpected() != null && this
						.getDateShipmentExpected().equals(
								castOther.getDateShipmentExpected())))
				&& ((this.getStudyProtocolId() == castOther
						.getStudyProtocolId()) || (this.getStudyProtocolId() != null
						&& castOther.getStudyProtocolId() != null && this
						.getStudyProtocolId().equals(
								castOther.getStudyProtocolId())))
				&& ((this.getNoSampleExpected() == castOther
						.getNoSampleExpected()) || (this.getNoSampleExpected() != null
						&& castOther.getNoSampleExpected() != null && this
						.getNoSampleExpected().equals(
								castOther.getNoSampleExpected())))
				&& ((this.getShippedSampleType() == castOther
						.getShippedSampleType()) || (this
						.getShippedSampleType() != null
						&& castOther.getShippedSampleType() != null && this
						.getShippedSampleType().equals(
								castOther.getShippedSampleType())))
				&& ((this.getOrganizationId() == castOther.getOrganizationId()) || (this
						.getOrganizationId() != null
						&& castOther.getOrganizationId() != null && this
						.getOrganizationId().equals(
								castOther.getOrganizationId())))
				&& ((this.getTrackingNumbers() == castOther
						.getTrackingNumbers()) || (this.getTrackingNumbers() != null
						&& castOther.getTrackingNumbers() != null && this
						.getTrackingNumbers().equals(
								castOther.getTrackingNumbers())))
				&& ((this.getContactId() == castOther.getContactId()) || (this
						.getContactId() != null
						&& castOther.getContactId() != null && this
						.getContactId().equals(castOther.getContactId())))
				&& ((this.getReceivedBy() == castOther.getReceivedBy()) || (this
						.getReceivedBy() != null
						&& castOther.getReceivedBy() != null && this
						.getReceivedBy().equals(castOther.getReceivedBy())))
				&& ((this.getDateReceived() == castOther.getDateReceived()) || (this
						.getDateReceived() != null
						&& castOther.getDateReceived() != null && this
						.getDateReceived().equals(castOther.getDateReceived())))
				&& ((this.getStudyNumber() == castOther.getStudyNumber()) || (this
						.getStudyNumber() != null
						&& castOther.getStudyNumber() != null && this
						.getStudyNumber().equals(castOther.getStudyNumber())))
				&& ((this.getSponsorStudyNumber() == castOther
						.getSponsorStudyNumber()) || (this
						.getSponsorStudyNumber() != null
						&& castOther.getSponsorStudyNumber() != null && this
						.getSponsorStudyNumber().equals(
								castOther.getSponsorStudyNumber())))
				&& ((this.getStudyDirector() == castOther.getStudyDirector()) || (this
						.getStudyDirector() != null
						&& castOther.getStudyDirector() != null && this
						.getStudyDirector()
						.equals(castOther.getStudyDirector())))
				&& ((this.getContactName() == castOther.getContactName()) || (this
						.getContactName() != null
						&& castOther.getContactName() != null && this
						.getContactName().equals(castOther.getContactName())))
				&& ((this.getSampleCondition() == castOther
						.getSampleCondition()) || (this.getSampleCondition() != null
						&& castOther.getSampleCondition() != null && this
						.getSampleCondition().equals(
								castOther.getSampleCondition())))
				&& ((this.getVolume() == castOther.getVolume()) || (this
						.getVolume() != null && castOther.getVolume() != null && this
						.getVolume().equals(castOther.getVolume())))
				&& ((this.getDateAccessioned() == castOther
						.getDateAccessioned()) || (this.getDateAccessioned() != null
						&& castOther.getDateAccessioned() != null && this
						.getDateAccessioned().equals(
								castOther.getDateAccessioned())))
				&& ((this.getAccessionedBy() == castOther.getAccessionedBy()) || (this
						.getAccessionedBy() != null
						&& castOther.getAccessionedBy() != null && this
						.getAccessionedBy()
						.equals(castOther.getAccessionedBy())))
				&& ((this.getSampleTubeId() == castOther.getSampleTubeId()) || (this
						.getSampleTubeId() != null
						&& castOther.getSampleTubeId() != null && this
						.getSampleTubeId().equals(castOther.getSampleTubeId())))
				&& ((this.getLocation() == castOther.getLocation()) || (this
						.getLocation() != null
						&& castOther.getLocation() != null && this
						.getLocation().equals(castOther.getLocation())))
				&& ((this.getCompany() == castOther.getCompany()) || (this
						.getCompany() != null && castOther.getCompany() != null && this
						.getCompany().equals(castOther.getCompany())))
				&& ((this.getAutoaccessionLoadId() == castOther
						.getAutoaccessionLoadId()) || (this
						.getAutoaccessionLoadId() != null
						&& castOther.getAutoaccessionLoadId() != null && this
						.getAutoaccessionLoadId().equals(
								castOther.getAutoaccessionLoadId())))
				&& ((this.getPendingSampleId() == castOther
						.getPendingSampleId()) || (this.getPendingSampleId() != null
						&& castOther.getPendingSampleId() != null && this
						.getPendingSampleId().equals(
								castOther.getPendingSampleId())))
				&& ((this.getSampleId() == castOther.getSampleId()) || (this
						.getSampleId() != null
						&& castOther.getSampleId() != null && this
						.getSampleId().equals(castOther.getSampleId())))
				&& ((this.getDateReceivedTrunc() == castOther
						.getDateReceivedTrunc()) || (this
						.getDateReceivedTrunc() != null
						&& castOther.getDateReceivedTrunc() != null && this
						.getDateReceivedTrunc().equals(
								castOther.getDateReceivedTrunc())))
				&& ((this.getDateAccessionedTrunc() == castOther
						.getDateAccessionedTrunc()) || (this
						.getDateAccessionedTrunc() != null
						&& castOther.getDateAccessionedTrunc() != null && this
						.getDateAccessionedTrunc().equals(
								castOther.getDateAccessionedTrunc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSampleReceptionId() == null ? 0 : this
						.getSampleReceptionId().hashCode());
		result = 37
				* result
				+ (getShipmentNo() == null ? 0 : this.getShipmentNo()
						.hashCode());
		result = 37
				* result
				+ (getChecklistId() == null ? 0 : this.getChecklistId()
						.hashCode());
		result = 37
				* result
				+ (getDateShipmentExpected() == null ? 0 : this
						.getDateShipmentExpected().hashCode());
		result = 37
				* result
				+ (getStudyProtocolId() == null ? 0 : this.getStudyProtocolId()
						.hashCode());
		result = 37
				* result
				+ (getNoSampleExpected() == null ? 0 : this
						.getNoSampleExpected().hashCode());
		result = 37
				* result
				+ (getShippedSampleType() == null ? 0 : this
						.getShippedSampleType().hashCode());
		result = 37
				* result
				+ (getOrganizationId() == null ? 0 : this.getOrganizationId()
						.hashCode());
		result = 37
				* result
				+ (getTrackingNumbers() == null ? 0 : this.getTrackingNumbers()
						.hashCode());
		result = 37 * result
				+ (getContactId() == null ? 0 : this.getContactId().hashCode());
		result = 37
				* result
				+ (getReceivedBy() == null ? 0 : this.getReceivedBy()
						.hashCode());
		result = 37
				* result
				+ (getDateReceived() == null ? 0 : this.getDateReceived()
						.hashCode());
		result = 37
				* result
				+ (getStudyNumber() == null ? 0 : this.getStudyNumber()
						.hashCode());
		result = 37
				* result
				+ (getSponsorStudyNumber() == null ? 0 : this
						.getSponsorStudyNumber().hashCode());
		result = 37
				* result
				+ (getStudyDirector() == null ? 0 : this.getStudyDirector()
						.hashCode());
		result = 37
				* result
				+ (getContactName() == null ? 0 : this.getContactName()
						.hashCode());
		result = 37
				* result
				+ (getSampleCondition() == null ? 0 : this.getSampleCondition()
						.hashCode());
		result = 37 * result
				+ (getVolume() == null ? 0 : this.getVolume().hashCode());
		result = 37
				* result
				+ (getDateAccessioned() == null ? 0 : this.getDateAccessioned()
						.hashCode());
		result = 37
				* result
				+ (getAccessionedBy() == null ? 0 : this.getAccessionedBy()
						.hashCode());
		result = 37
				* result
				+ (getSampleTubeId() == null ? 0 : this.getSampleTubeId()
						.hashCode());
		result = 37 * result
				+ (getLocation() == null ? 0 : this.getLocation().hashCode());
		result = 37 * result
				+ (getCompany() == null ? 0 : this.getCompany().hashCode());
		result = 37
				* result
				+ (getAutoaccessionLoadId() == null ? 0 : this
						.getAutoaccessionLoadId().hashCode());
		result = 37
				* result
				+ (getPendingSampleId() == null ? 0 : this.getPendingSampleId()
						.hashCode());
		result = 37 * result
				+ (getSampleId() == null ? 0 : this.getSampleId().hashCode());
		result = 37
				* result
				+ (getDateReceivedTrunc() == null ? 0 : this
						.getDateReceivedTrunc().hashCode());
		result = 37
				* result
				+ (getDateAccessionedTrunc() == null ? 0 : this
						.getDateAccessionedTrunc().hashCode());
		return result;
	}

}
