package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * MSampleReceptionView generated by hbm2java
 */
public class MSampleReceptionView implements java.io.Serializable {

	private MSampleReceptionViewId id;

	public MSampleReceptionView() {
	}

	public MSampleReceptionView(MSampleReceptionViewId id) {
		this.id = id;
	}

	public MSampleReceptionViewId getId() {
		return this.id;
	}

	public void setId(MSampleReceptionViewId id) {
		this.id = id;
	}

}
