package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * NcpView generated by hbm2java
 */
public class NcpView implements java.io.Serializable {

	private NcpViewId id;

	public NcpView() {
	}

	public NcpView(NcpViewId id) {
		this.id = id;
	}

	public NcpViewId getId() {
		return this.id;
	}

	public void setId(NcpViewId id) {
		this.id = id;
	}

}
