package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * NcpViewId generated by hbm2java
 */
public class NcpViewId implements java.io.Serializable {

	private String assayName;
	private String normalizedCp;
	private Date dateCalculated;
	private Character lastCol;
	private BigDecimal parentSampleId;
	private BigDecimal checklistId;
	private BigDecimal stepTemplateId;
	private BigDecimal cpRunId;

	public NcpViewId() {
	}

	public NcpViewId(String assayName, String normalizedCp,
			Date dateCalculated, BigDecimal parentSampleId,
			BigDecimal checklistId, BigDecimal stepTemplateId,
			BigDecimal cpRunId) {
		this.assayName = assayName;
		this.normalizedCp = normalizedCp;
		this.dateCalculated = dateCalculated;
		this.parentSampleId = parentSampleId;
		this.checklistId = checklistId;
		this.stepTemplateId = stepTemplateId;
		this.cpRunId = cpRunId;
	}

	public NcpViewId(String assayName, String normalizedCp,
			Date dateCalculated, Character lastCol, BigDecimal parentSampleId,
			BigDecimal checklistId, BigDecimal stepTemplateId,
			BigDecimal cpRunId) {
		this.assayName = assayName;
		this.normalizedCp = normalizedCp;
		this.dateCalculated = dateCalculated;
		this.lastCol = lastCol;
		this.parentSampleId = parentSampleId;
		this.checklistId = checklistId;
		this.stepTemplateId = stepTemplateId;
		this.cpRunId = cpRunId;
	}

	public String getAssayName() {
		return this.assayName;
	}

	public void setAssayName(String assayName) {
		this.assayName = assayName;
	}

	public String getNormalizedCp() {
		return this.normalizedCp;
	}

	public void setNormalizedCp(String normalizedCp) {
		this.normalizedCp = normalizedCp;
	}

	public Date getDateCalculated() {
		return this.dateCalculated;
	}

	public void setDateCalculated(Date dateCalculated) {
		this.dateCalculated = dateCalculated;
	}

	public Character getLastCol() {
		return this.lastCol;
	}

	public void setLastCol(Character lastCol) {
		this.lastCol = lastCol;
	}

	public BigDecimal getParentSampleId() {
		return this.parentSampleId;
	}

	public void setParentSampleId(BigDecimal parentSampleId) {
		this.parentSampleId = parentSampleId;
	}

	public BigDecimal getChecklistId() {
		return this.checklistId;
	}

	public void setChecklistId(BigDecimal checklistId) {
		this.checklistId = checklistId;
	}

	public BigDecimal getStepTemplateId() {
		return this.stepTemplateId;
	}

	public void setStepTemplateId(BigDecimal stepTemplateId) {
		this.stepTemplateId = stepTemplateId;
	}

	public BigDecimal getCpRunId() {
		return this.cpRunId;
	}

	public void setCpRunId(BigDecimal cpRunId) {
		this.cpRunId = cpRunId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NcpViewId))
			return false;
		NcpViewId castOther = (NcpViewId) other;

		return ((this.getAssayName() == castOther.getAssayName()) || (this
				.getAssayName() != null && castOther.getAssayName() != null && this
				.getAssayName().equals(castOther.getAssayName())))
				&& ((this.getNormalizedCp() == castOther.getNormalizedCp()) || (this
						.getNormalizedCp() != null
						&& castOther.getNormalizedCp() != null && this
						.getNormalizedCp().equals(castOther.getNormalizedCp())))
				&& ((this.getDateCalculated() == castOther.getDateCalculated()) || (this
						.getDateCalculated() != null
						&& castOther.getDateCalculated() != null && this
						.getDateCalculated().equals(
								castOther.getDateCalculated())))
				&& ((this.getLastCol() == castOther.getLastCol()) || (this
						.getLastCol() != null && castOther.getLastCol() != null && this
						.getLastCol().equals(castOther.getLastCol())))
				&& ((this.getParentSampleId() == castOther.getParentSampleId()) || (this
						.getParentSampleId() != null
						&& castOther.getParentSampleId() != null && this
						.getParentSampleId().equals(
								castOther.getParentSampleId())))
				&& ((this.getChecklistId() == castOther.getChecklistId()) || (this
						.getChecklistId() != null
						&& castOther.getChecklistId() != null && this
						.getChecklistId().equals(castOther.getChecklistId())))
				&& ((this.getStepTemplateId() == castOther.getStepTemplateId()) || (this
						.getStepTemplateId() != null
						&& castOther.getStepTemplateId() != null && this
						.getStepTemplateId().equals(
								castOther.getStepTemplateId())))
				&& ((this.getCpRunId() == castOther.getCpRunId()) || (this
						.getCpRunId() != null && castOther.getCpRunId() != null && this
						.getCpRunId().equals(castOther.getCpRunId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAssayName() == null ? 0 : this.getAssayName().hashCode());
		result = 37
				* result
				+ (getNormalizedCp() == null ? 0 : this.getNormalizedCp()
						.hashCode());
		result = 37
				* result
				+ (getDateCalculated() == null ? 0 : this.getDateCalculated()
						.hashCode());
		result = 37 * result
				+ (getLastCol() == null ? 0 : this.getLastCol().hashCode());
		result = 37
				* result
				+ (getParentSampleId() == null ? 0 : this.getParentSampleId()
						.hashCode());
		result = 37
				* result
				+ (getChecklistId() == null ? 0 : this.getChecklistId()
						.hashCode());
		result = 37
				* result
				+ (getStepTemplateId() == null ? 0 : this.getStepTemplateId()
						.hashCode());
		result = 37 * result
				+ (getCpRunId() == null ? 0 : this.getCpRunId().hashCode());
		return result;
	}

}
