package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * PcrRobotscriptDestView generated by hbm2java
 */
public class PcrRobotscriptDestView implements java.io.Serializable {

	private PcrRobotscriptDestViewId id;

	public PcrRobotscriptDestView() {
	}

	public PcrRobotscriptDestView(PcrRobotscriptDestViewId id) {
		this.id = id;
	}

	public PcrRobotscriptDestViewId getId() {
		return this.id;
	}

	public void setId(PcrRobotscriptDestViewId id) {
		this.id = id;
	}

}
