package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * PcrReagentView generated by hbm2java
 */
public class PcrReagentView implements java.io.Serializable {

	private PcrReagentViewId id;

	public PcrReagentView() {
	}

	public PcrReagentView(PcrReagentViewId id) {
		this.id = id;
	}

	public PcrReagentViewId getId() {
		return this.id;
	}

	public void setId(PcrReagentViewId id) {
		this.id = id;
	}

}
