package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * PendingSampleAttributeView generated by hbm2java
 */
public class PendingSampleAttributeView implements java.io.Serializable {

	private PendingSampleAttributeViewId id;

	public PendingSampleAttributeView() {
	}

	public PendingSampleAttributeView(PendingSampleAttributeViewId id) {
		this.id = id;
	}

	public PendingSampleAttributeViewId getId() {
		return this.id;
	}

	public void setId(PendingSampleAttributeViewId id) {
		this.id = id;
	}

}
