package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * PendingSubjectAttributeName generated by hbm2java
 */
public class PendingSubjectAttributeName implements java.io.Serializable {

	private PendingSubjectAttributeNameId id;

	public PendingSubjectAttributeName() {
	}

	public PendingSubjectAttributeName(PendingSubjectAttributeNameId id) {
		this.id = id;
	}

	public PendingSubjectAttributeNameId getId() {
		return this.id;
	}

	public void setId(PendingSubjectAttributeNameId id) {
		this.id = id;
	}

}
