package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * PlateConditionView generated by hbm2java
 */
public class PlateConditionView implements java.io.Serializable {

	private PlateConditionViewId id;

	public PlateConditionView() {
	}

	public PlateConditionView(PlateConditionViewId id) {
		this.id = id;
	}

	public PlateConditionViewId getId() {
		return this.id;
	}

	public void setId(PlateConditionViewId id) {
		this.id = id;
	}

}
