package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * PlatePendingViewId generated by hbm2java
 */
public class PlatePendingViewId implements java.io.Serializable {

	private String plateNo;
	private BigDecimal noOfSamples;
	private String filename;
	private Character lastCol;
	private BigDecimal studyProtocolId;
	private BigDecimal autoaccessionLoadId;

	public PlatePendingViewId() {
	}

	public PlatePendingViewId(String filename, BigDecimal autoaccessionLoadId) {
		this.filename = filename;
		this.autoaccessionLoadId = autoaccessionLoadId;
	}

	public PlatePendingViewId(String plateNo, BigDecimal noOfSamples,
			String filename, Character lastCol, BigDecimal studyProtocolId,
			BigDecimal autoaccessionLoadId) {
		this.plateNo = plateNo;
		this.noOfSamples = noOfSamples;
		this.filename = filename;
		this.lastCol = lastCol;
		this.studyProtocolId = studyProtocolId;
		this.autoaccessionLoadId = autoaccessionLoadId;
	}

	public String getPlateNo() {
		return this.plateNo;
	}

	public void setPlateNo(String plateNo) {
		this.plateNo = plateNo;
	}

	public BigDecimal getNoOfSamples() {
		return this.noOfSamples;
	}

	public void setNoOfSamples(BigDecimal noOfSamples) {
		this.noOfSamples = noOfSamples;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public Character getLastCol() {
		return this.lastCol;
	}

	public void setLastCol(Character lastCol) {
		this.lastCol = lastCol;
	}

	public BigDecimal getStudyProtocolId() {
		return this.studyProtocolId;
	}

	public void setStudyProtocolId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public BigDecimal getAutoaccessionLoadId() {
		return this.autoaccessionLoadId;
	}

	public void setAutoaccessionLoadId(BigDecimal autoaccessionLoadId) {
		this.autoaccessionLoadId = autoaccessionLoadId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlatePendingViewId))
			return false;
		PlatePendingViewId castOther = (PlatePendingViewId) other;

		return ((this.getPlateNo() == castOther.getPlateNo()) || (this
				.getPlateNo() != null && castOther.getPlateNo() != null && this
				.getPlateNo().equals(castOther.getPlateNo())))
				&& ((this.getNoOfSamples() == castOther.getNoOfSamples()) || (this
						.getNoOfSamples() != null
						&& castOther.getNoOfSamples() != null && this
						.getNoOfSamples().equals(castOther.getNoOfSamples())))
				&& ((this.getFilename() == castOther.getFilename()) || (this
						.getFilename() != null
						&& castOther.getFilename() != null && this
						.getFilename().equals(castOther.getFilename())))
				&& ((this.getLastCol() == castOther.getLastCol()) || (this
						.getLastCol() != null && castOther.getLastCol() != null && this
						.getLastCol().equals(castOther.getLastCol())))
				&& ((this.getStudyProtocolId() == castOther
						.getStudyProtocolId()) || (this.getStudyProtocolId() != null
						&& castOther.getStudyProtocolId() != null && this
						.getStudyProtocolId().equals(
								castOther.getStudyProtocolId())))
				&& ((this.getAutoaccessionLoadId() == castOther
						.getAutoaccessionLoadId()) || (this
						.getAutoaccessionLoadId() != null
						&& castOther.getAutoaccessionLoadId() != null && this
						.getAutoaccessionLoadId().equals(
								castOther.getAutoaccessionLoadId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPlateNo() == null ? 0 : this.getPlateNo().hashCode());
		result = 37
				* result
				+ (getNoOfSamples() == null ? 0 : this.getNoOfSamples()
						.hashCode());
		result = 37 * result
				+ (getFilename() == null ? 0 : this.getFilename().hashCode());
		result = 37 * result
				+ (getLastCol() == null ? 0 : this.getLastCol().hashCode());
		result = 37
				* result
				+ (getStudyProtocolId() == null ? 0 : this.getStudyProtocolId()
						.hashCode());
		result = 37
				* result
				+ (getAutoaccessionLoadId() == null ? 0 : this
						.getAutoaccessionLoadId().hashCode());
		return result;
	}

}
