package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * QcNormalizationBaseView generated by hbm2java
 */
public class QcNormalizationBaseView implements java.io.Serializable {

	private QcNormalizationBaseViewId id;

	public QcNormalizationBaseView() {
	}

	public QcNormalizationBaseView(QcNormalizationBaseViewId id) {
		this.id = id;
	}

	public QcNormalizationBaseViewId getId() {
		return this.id;
	}

	public void setId(QcNormalizationBaseViewId id) {
		this.id = id;
	}

}
