package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * RoiSetupSelectionViewId generated by hbm2java
 */
public class RoiSetupSelectionViewId implements java.io.Serializable {

	private String roiName;
	private String geneName;
	private String geneRegion;
	private Character lastCol;
	private BigDecimal roiId;
	private BigDecimal geneId;
	private BigDecimal geneRegionId;

	public RoiSetupSelectionViewId() {
	}

	public RoiSetupSelectionViewId(String roiName, BigDecimal roiId) {
		this.roiName = roiName;
		this.roiId = roiId;
	}

	public RoiSetupSelectionViewId(String roiName, String geneName,
			String geneRegion, Character lastCol, BigDecimal roiId,
			BigDecimal geneId, BigDecimal geneRegionId) {
		this.roiName = roiName;
		this.geneName = geneName;
		this.geneRegion = geneRegion;
		this.lastCol = lastCol;
		this.roiId = roiId;
		this.geneId = geneId;
		this.geneRegionId = geneRegionId;
	}

	public String getRoiName() {
		return this.roiName;
	}

	public void setRoiName(String roiName) {
		this.roiName = roiName;
	}

	public String getGeneName() {
		return this.geneName;
	}

	public void setGeneName(String geneName) {
		this.geneName = geneName;
	}

	public String getGeneRegion() {
		return this.geneRegion;
	}

	public void setGeneRegion(String geneRegion) {
		this.geneRegion = geneRegion;
	}

	public Character getLastCol() {
		return this.lastCol;
	}

	public void setLastCol(Character lastCol) {
		this.lastCol = lastCol;
	}

	public BigDecimal getRoiId() {
		return this.roiId;
	}

	public void setRoiId(BigDecimal roiId) {
		this.roiId = roiId;
	}

	public BigDecimal getGeneId() {
		return this.geneId;
	}

	public void setGeneId(BigDecimal geneId) {
		this.geneId = geneId;
	}

	public BigDecimal getGeneRegionId() {
		return this.geneRegionId;
	}

	public void setGeneRegionId(BigDecimal geneRegionId) {
		this.geneRegionId = geneRegionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoiSetupSelectionViewId))
			return false;
		RoiSetupSelectionViewId castOther = (RoiSetupSelectionViewId) other;

		return ((this.getRoiName() == castOther.getRoiName()) || (this
				.getRoiName() != null && castOther.getRoiName() != null && this
				.getRoiName().equals(castOther.getRoiName())))
				&& ((this.getGeneName() == castOther.getGeneName()) || (this
						.getGeneName() != null
						&& castOther.getGeneName() != null && this
						.getGeneName().equals(castOther.getGeneName())))
				&& ((this.getGeneRegion() == castOther.getGeneRegion()) || (this
						.getGeneRegion() != null
						&& castOther.getGeneRegion() != null && this
						.getGeneRegion().equals(castOther.getGeneRegion())))
				&& ((this.getLastCol() == castOther.getLastCol()) || (this
						.getLastCol() != null && castOther.getLastCol() != null && this
						.getLastCol().equals(castOther.getLastCol())))
				&& ((this.getRoiId() == castOther.getRoiId()) || (this
						.getRoiId() != null && castOther.getRoiId() != null && this
						.getRoiId().equals(castOther.getRoiId())))
				&& ((this.getGeneId() == castOther.getGeneId()) || (this
						.getGeneId() != null && castOther.getGeneId() != null && this
						.getGeneId().equals(castOther.getGeneId())))
				&& ((this.getGeneRegionId() == castOther.getGeneRegionId()) || (this
						.getGeneRegionId() != null
						&& castOther.getGeneRegionId() != null && this
						.getGeneRegionId().equals(castOther.getGeneRegionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoiName() == null ? 0 : this.getRoiName().hashCode());
		result = 37 * result
				+ (getGeneName() == null ? 0 : this.getGeneName().hashCode());
		result = 37
				* result
				+ (getGeneRegion() == null ? 0 : this.getGeneRegion()
						.hashCode());
		result = 37 * result
				+ (getLastCol() == null ? 0 : this.getLastCol().hashCode());
		result = 37 * result
				+ (getRoiId() == null ? 0 : this.getRoiId().hashCode());
		result = 37 * result
				+ (getGeneId() == null ? 0 : this.getGeneId().hashCode());
		result = 37
				* result
				+ (getGeneRegionId() == null ? 0 : this.getGeneRegionId()
						.hashCode());
		return result;
	}

}
