package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * RoiView generated by hbm2java
 */
public class RoiView implements java.io.Serializable {

	private RoiViewId id;

	public RoiView() {
	}

	public RoiView(RoiViewId id) {
		this.id = id;
	}

	public RoiViewId getId() {
		return this.id;
	}

	public void setId(RoiViewId id) {
		this.id = id;
	}

}
