package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * RoiViewId generated by hbm2java
 */
public class RoiViewId implements java.io.Serializable {

	private String roiName;
	private String roiType;
	private String gene;
	private BigDecimal region;
	private String status;
	private String techniqueType;
	private Character lastCol;
	private BigDecimal geneId;
	private BigDecimal roiId;
	private BigDecimal geneRegionId;
	private BigDecimal techniqueTypeId;

	public RoiViewId() {
	}

	public RoiViewId(String roiName, String roiType, BigDecimal roiId) {
		this.roiName = roiName;
		this.roiType = roiType;
		this.roiId = roiId;
	}

	public RoiViewId(String roiName, String roiType, String gene,
			BigDecimal region, String status, String techniqueType,
			Character lastCol, BigDecimal geneId, BigDecimal roiId,
			BigDecimal geneRegionId, BigDecimal techniqueTypeId) {
		this.roiName = roiName;
		this.roiType = roiType;
		this.gene = gene;
		this.region = region;
		this.status = status;
		this.techniqueType = techniqueType;
		this.lastCol = lastCol;
		this.geneId = geneId;
		this.roiId = roiId;
		this.geneRegionId = geneRegionId;
		this.techniqueTypeId = techniqueTypeId;
	}

	public String getRoiName() {
		return this.roiName;
	}

	public void setRoiName(String roiName) {
		this.roiName = roiName;
	}

	public String getRoiType() {
		return this.roiType;
	}

	public void setRoiType(String roiType) {
		this.roiType = roiType;
	}

	public String getGene() {
		return this.gene;
	}

	public void setGene(String gene) {
		this.gene = gene;
	}

	public BigDecimal getRegion() {
		return this.region;
	}

	public void setRegion(BigDecimal region) {
		this.region = region;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTechniqueType() {
		return this.techniqueType;
	}

	public void setTechniqueType(String techniqueType) {
		this.techniqueType = techniqueType;
	}

	public Character getLastCol() {
		return this.lastCol;
	}

	public void setLastCol(Character lastCol) {
		this.lastCol = lastCol;
	}

	public BigDecimal getGeneId() {
		return this.geneId;
	}

	public void setGeneId(BigDecimal geneId) {
		this.geneId = geneId;
	}

	public BigDecimal getRoiId() {
		return this.roiId;
	}

	public void setRoiId(BigDecimal roiId) {
		this.roiId = roiId;
	}

	public BigDecimal getGeneRegionId() {
		return this.geneRegionId;
	}

	public void setGeneRegionId(BigDecimal geneRegionId) {
		this.geneRegionId = geneRegionId;
	}

	public BigDecimal getTechniqueTypeId() {
		return this.techniqueTypeId;
	}

	public void setTechniqueTypeId(BigDecimal techniqueTypeId) {
		this.techniqueTypeId = techniqueTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoiViewId))
			return false;
		RoiViewId castOther = (RoiViewId) other;

		return ((this.getRoiName() == castOther.getRoiName()) || (this
				.getRoiName() != null && castOther.getRoiName() != null && this
				.getRoiName().equals(castOther.getRoiName())))
				&& ((this.getRoiType() == castOther.getRoiType()) || (this
						.getRoiType() != null && castOther.getRoiType() != null && this
						.getRoiType().equals(castOther.getRoiType())))
				&& ((this.getGene() == castOther.getGene()) || (this.getGene() != null
						&& castOther.getGene() != null && this.getGene()
						.equals(castOther.getGene())))
				&& ((this.getRegion() == castOther.getRegion()) || (this
						.getRegion() != null && castOther.getRegion() != null && this
						.getRegion().equals(castOther.getRegion())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getTechniqueType() == castOther.getTechniqueType()) || (this
						.getTechniqueType() != null
						&& castOther.getTechniqueType() != null && this
						.getTechniqueType()
						.equals(castOther.getTechniqueType())))
				&& ((this.getLastCol() == castOther.getLastCol()) || (this
						.getLastCol() != null && castOther.getLastCol() != null && this
						.getLastCol().equals(castOther.getLastCol())))
				&& ((this.getGeneId() == castOther.getGeneId()) || (this
						.getGeneId() != null && castOther.getGeneId() != null && this
						.getGeneId().equals(castOther.getGeneId())))
				&& ((this.getRoiId() == castOther.getRoiId()) || (this
						.getRoiId() != null && castOther.getRoiId() != null && this
						.getRoiId().equals(castOther.getRoiId())))
				&& ((this.getGeneRegionId() == castOther.getGeneRegionId()) || (this
						.getGeneRegionId() != null
						&& castOther.getGeneRegionId() != null && this
						.getGeneRegionId().equals(castOther.getGeneRegionId())))
				&& ((this.getTechniqueTypeId() == castOther
						.getTechniqueTypeId()) || (this.getTechniqueTypeId() != null
						&& castOther.getTechniqueTypeId() != null && this
						.getTechniqueTypeId().equals(
								castOther.getTechniqueTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoiName() == null ? 0 : this.getRoiName().hashCode());
		result = 37 * result
				+ (getRoiType() == null ? 0 : this.getRoiType().hashCode());
		result = 37 * result
				+ (getGene() == null ? 0 : this.getGene().hashCode());
		result = 37 * result
				+ (getRegion() == null ? 0 : this.getRegion().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37
				* result
				+ (getTechniqueType() == null ? 0 : this.getTechniqueType()
						.hashCode());
		result = 37 * result
				+ (getLastCol() == null ? 0 : this.getLastCol().hashCode());
		result = 37 * result
				+ (getGeneId() == null ? 0 : this.getGeneId().hashCode());
		result = 37 * result
				+ (getRoiId() == null ? 0 : this.getRoiId().hashCode());
		result = 37
				* result
				+ (getGeneRegionId() == null ? 0 : this.getGeneRegionId()
						.hashCode());
		result = 37
				* result
				+ (getTechniqueTypeId() == null ? 0 : this.getTechniqueTypeId()
						.hashCode());
		return result;
	}

}
