package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * SampleVariableView generated by hbm2java
 */
public class SampleVariableView implements java.io.Serializable {

	private SampleVariableViewId id;

	public SampleVariableView() {
	}

	public SampleVariableView(SampleVariableViewId id) {
		this.id = id;
	}

	public SampleVariableViewId getId() {
		return this.id;
	}

	public void setId(SampleVariableViewId id) {
		this.id = id;
	}

}
