package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SearchAttributeViewId generated by hbm2java
 */
public class SearchAttributeViewId implements java.io.Serializable {

	private String variableName;
	private String controlType;
	private String listSql;
	private BigDecimal useId;
	private String joinTable;
	private String joinField;
	private String compareField;
	private String attributeLevelId;
	private BigDecimal numberInSequence;

	public SearchAttributeViewId() {
	}

	public SearchAttributeViewId(String variableName,
			BigDecimal numberInSequence) {
		this.variableName = variableName;
		this.numberInSequence = numberInSequence;
	}

	public SearchAttributeViewId(String variableName, String controlType,
			String listSql, BigDecimal useId, String joinTable,
			String joinField, String compareField, String attributeLevelId,
			BigDecimal numberInSequence) {
		this.variableName = variableName;
		this.controlType = controlType;
		this.listSql = listSql;
		this.useId = useId;
		this.joinTable = joinTable;
		this.joinField = joinField;
		this.compareField = compareField;
		this.attributeLevelId = attributeLevelId;
		this.numberInSequence = numberInSequence;
	}

	public String getVariableName() {
		return this.variableName;
	}

	public void setVariableName(String variableName) {
		this.variableName = variableName;
	}

	public String getControlType() {
		return this.controlType;
	}

	public void setControlType(String controlType) {
		this.controlType = controlType;
	}

	public String getListSql() {
		return this.listSql;
	}

	public void setListSql(String listSql) {
		this.listSql = listSql;
	}

	public BigDecimal getUseId() {
		return this.useId;
	}

	public void setUseId(BigDecimal useId) {
		this.useId = useId;
	}

	public String getJoinTable() {
		return this.joinTable;
	}

	public void setJoinTable(String joinTable) {
		this.joinTable = joinTable;
	}

	public String getJoinField() {
		return this.joinField;
	}

	public void setJoinField(String joinField) {
		this.joinField = joinField;
	}

	public String getCompareField() {
		return this.compareField;
	}

	public void setCompareField(String compareField) {
		this.compareField = compareField;
	}

	public String getAttributeLevelId() {
		return this.attributeLevelId;
	}

	public void setAttributeLevelId(String attributeLevelId) {
		this.attributeLevelId = attributeLevelId;
	}

	public BigDecimal getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(BigDecimal numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SearchAttributeViewId))
			return false;
		SearchAttributeViewId castOther = (SearchAttributeViewId) other;

		return ((this.getVariableName() == castOther.getVariableName()) || (this
				.getVariableName() != null
				&& castOther.getVariableName() != null && this
				.getVariableName().equals(castOther.getVariableName())))
				&& ((this.getControlType() == castOther.getControlType()) || (this
						.getControlType() != null
						&& castOther.getControlType() != null && this
						.getControlType().equals(castOther.getControlType())))
				&& ((this.getListSql() == castOther.getListSql()) || (this
						.getListSql() != null && castOther.getListSql() != null && this
						.getListSql().equals(castOther.getListSql())))
				&& ((this.getUseId() == castOther.getUseId()) || (this
						.getUseId() != null && castOther.getUseId() != null && this
						.getUseId().equals(castOther.getUseId())))
				&& ((this.getJoinTable() == castOther.getJoinTable()) || (this
						.getJoinTable() != null
						&& castOther.getJoinTable() != null && this
						.getJoinTable().equals(castOther.getJoinTable())))
				&& ((this.getJoinField() == castOther.getJoinField()) || (this
						.getJoinField() != null
						&& castOther.getJoinField() != null && this
						.getJoinField().equals(castOther.getJoinField())))
				&& ((this.getCompareField() == castOther.getCompareField()) || (this
						.getCompareField() != null
						&& castOther.getCompareField() != null && this
						.getCompareField().equals(castOther.getCompareField())))
				&& ((this.getAttributeLevelId() == castOther
						.getAttributeLevelId()) || (this.getAttributeLevelId() != null
						&& castOther.getAttributeLevelId() != null && this
						.getAttributeLevelId().equals(
								castOther.getAttributeLevelId())))
				&& ((this.getNumberInSequence() == castOther
						.getNumberInSequence()) || (this.getNumberInSequence() != null
						&& castOther.getNumberInSequence() != null && this
						.getNumberInSequence().equals(
								castOther.getNumberInSequence())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getVariableName() == null ? 0 : this.getVariableName()
						.hashCode());
		result = 37
				* result
				+ (getControlType() == null ? 0 : this.getControlType()
						.hashCode());
		result = 37 * result
				+ (getListSql() == null ? 0 : this.getListSql().hashCode());
		result = 37 * result
				+ (getUseId() == null ? 0 : this.getUseId().hashCode());
		result = 37 * result
				+ (getJoinTable() == null ? 0 : this.getJoinTable().hashCode());
		result = 37 * result
				+ (getJoinField() == null ? 0 : this.getJoinField().hashCode());
		result = 37
				* result
				+ (getCompareField() == null ? 0 : this.getCompareField()
						.hashCode());
		result = 37
				* result
				+ (getAttributeLevelId() == null ? 0 : this
						.getAttributeLevelId().hashCode());
		result = 37
				* result
				+ (getNumberInSequence() == null ? 0 : this
						.getNumberInSequence().hashCode());
		return result;
	}

}
