package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * SeqSetupQcView generated by hbm2java
 */
public class SeqSetupQcView implements java.io.Serializable {

	private SeqSetupQcViewId id;

	public SeqSetupQcView() {
	}

	public SeqSetupQcView(SeqSetupQcViewId id) {
		this.id = id;
	}

	public SeqSetupQcViewId getId() {
		return this.id;
	}

	public void setId(SeqSetupQcViewId id) {
		this.id = id;
	}

}
