package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * SpecimenDetailsView generated by hbm2java
 */
public class SpecimenDetailsView implements java.io.Serializable {

	private SpecimenDetailsViewId id;

	public SpecimenDetailsView() {
	}

	public SpecimenDetailsView(SpecimenDetailsViewId id) {
		this.id = id;
	}

	public SpecimenDetailsViewId getId() {
		return this.id;
	}

	public void setId(SpecimenDetailsViewId id) {
		this.id = id;
	}

}
