package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * StorageConsentView generated by hbm2java
 */
public class StorageConsentView implements java.io.Serializable {

	private StorageConsentViewId id;

	public StorageConsentView() {
	}

	public StorageConsentView(StorageConsentViewId id) {
		this.id = id;
	}

	public StorageConsentViewId getId() {
		return this.id;
	}

	public void setId(StorageConsentViewId id) {
		this.id = id;
	}

}
