package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * StudyProtocolViewId generated by hbm2java
 */
public class StudyProtocolViewId implements java.io.Serializable {

	private BigDecimal studyProtocolId;
	private String studyNumber;
	private String sponsorStudyNumber;
	private String studyTitle;
	private String studyDirector;
	private String sponsorStudyTitle;
	private BigDecimal contactId;
	private Boolean cascadeAccessionNumber;
	private BigDecimal barcodeLength;
	private String finalTubeBarcodeLowValue;
	private String finalTubeBarcodeHighValue;
	private Boolean studyClosed;
	private Boolean shipDnaBack;
	private BigDecimal accessionVarOcx;
	private BigDecimal studyVarOcx;
	private BigDecimal patientVarOcx;
	private String studyUrl;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal subsidiaryId;
	private String studyType;
	private BigDecimal organizationId;
	private String company;
	private String name;

	public StudyProtocolViewId() {
	}

	public StudyProtocolViewId(BigDecimal studyProtocolId, String studyDirector) {
		this.studyProtocolId = studyProtocolId;
		this.studyDirector = studyDirector;
	}

	public StudyProtocolViewId(BigDecimal studyProtocolId, String studyNumber,
			String sponsorStudyNumber, String studyTitle, String studyDirector,
			String sponsorStudyTitle, BigDecimal contactId,
			Boolean cascadeAccessionNumber, BigDecimal barcodeLength,
			String finalTubeBarcodeLowValue, String finalTubeBarcodeHighValue,
			Boolean studyClosed, Boolean shipDnaBack,
			BigDecimal accessionVarOcx, BigDecimal studyVarOcx,
			BigDecimal patientVarOcx, String studyUrl, String createdBy,
			Date dateCreated, String modifiedBy, Date dateModified,
			BigDecimal subsidiaryId, String studyType,
			BigDecimal organizationId, String company, String name) {
		this.studyProtocolId = studyProtocolId;
		this.studyNumber = studyNumber;
		this.sponsorStudyNumber = sponsorStudyNumber;
		this.studyTitle = studyTitle;
		this.studyDirector = studyDirector;
		this.sponsorStudyTitle = sponsorStudyTitle;
		this.contactId = contactId;
		this.cascadeAccessionNumber = cascadeAccessionNumber;
		this.barcodeLength = barcodeLength;
		this.finalTubeBarcodeLowValue = finalTubeBarcodeLowValue;
		this.finalTubeBarcodeHighValue = finalTubeBarcodeHighValue;
		this.studyClosed = studyClosed;
		this.shipDnaBack = shipDnaBack;
		this.accessionVarOcx = accessionVarOcx;
		this.studyVarOcx = studyVarOcx;
		this.patientVarOcx = patientVarOcx;
		this.studyUrl = studyUrl;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.subsidiaryId = subsidiaryId;
		this.studyType = studyType;
		this.organizationId = organizationId;
		this.company = company;
		this.name = name;
	}

	public BigDecimal getStudyProtocolId() {
		return this.studyProtocolId;
	}

	public void setStudyProtocolId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public String getStudyNumber() {
		return this.studyNumber;
	}

	public void setStudyNumber(String studyNumber) {
		this.studyNumber = studyNumber;
	}

	public String getSponsorStudyNumber() {
		return this.sponsorStudyNumber;
	}

	public void setSponsorStudyNumber(String sponsorStudyNumber) {
		this.sponsorStudyNumber = sponsorStudyNumber;
	}

	public String getStudyTitle() {
		return this.studyTitle;
	}

	public void setStudyTitle(String studyTitle) {
		this.studyTitle = studyTitle;
	}

	public String getStudyDirector() {
		return this.studyDirector;
	}

	public void setStudyDirector(String studyDirector) {
		this.studyDirector = studyDirector;
	}

	public String getSponsorStudyTitle() {
		return this.sponsorStudyTitle;
	}

	public void setSponsorStudyTitle(String sponsorStudyTitle) {
		this.sponsorStudyTitle = sponsorStudyTitle;
	}

	public BigDecimal getContactId() {
		return this.contactId;
	}

	public void setContactId(BigDecimal contactId) {
		this.contactId = contactId;
	}

	public Boolean getCascadeAccessionNumber() {
		return this.cascadeAccessionNumber;
	}

	public void setCascadeAccessionNumber(Boolean cascadeAccessionNumber) {
		this.cascadeAccessionNumber = cascadeAccessionNumber;
	}

	public BigDecimal getBarcodeLength() {
		return this.barcodeLength;
	}

	public void setBarcodeLength(BigDecimal barcodeLength) {
		this.barcodeLength = barcodeLength;
	}

	public String getFinalTubeBarcodeLowValue() {
		return this.finalTubeBarcodeLowValue;
	}

	public void setFinalTubeBarcodeLowValue(String finalTubeBarcodeLowValue) {
		this.finalTubeBarcodeLowValue = finalTubeBarcodeLowValue;
	}

	public String getFinalTubeBarcodeHighValue() {
		return this.finalTubeBarcodeHighValue;
	}

	public void setFinalTubeBarcodeHighValue(String finalTubeBarcodeHighValue) {
		this.finalTubeBarcodeHighValue = finalTubeBarcodeHighValue;
	}

	public Boolean getStudyClosed() {
		return this.studyClosed;
	}

	public void setStudyClosed(Boolean studyClosed) {
		this.studyClosed = studyClosed;
	}

	public Boolean getShipDnaBack() {
		return this.shipDnaBack;
	}

	public void setShipDnaBack(Boolean shipDnaBack) {
		this.shipDnaBack = shipDnaBack;
	}

	public BigDecimal getAccessionVarOcx() {
		return this.accessionVarOcx;
	}

	public void setAccessionVarOcx(BigDecimal accessionVarOcx) {
		this.accessionVarOcx = accessionVarOcx;
	}

	public BigDecimal getStudyVarOcx() {
		return this.studyVarOcx;
	}

	public void setStudyVarOcx(BigDecimal studyVarOcx) {
		this.studyVarOcx = studyVarOcx;
	}

	public BigDecimal getPatientVarOcx() {
		return this.patientVarOcx;
	}

	public void setPatientVarOcx(BigDecimal patientVarOcx) {
		this.patientVarOcx = patientVarOcx;
	}

	public String getStudyUrl() {
		return this.studyUrl;
	}

	public void setStudyUrl(String studyUrl) {
		this.studyUrl = studyUrl;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

	public String getStudyType() {
		return this.studyType;
	}

	public void setStudyType(String studyType) {
		this.studyType = studyType;
	}

	public BigDecimal getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(BigDecimal organizationId) {
		this.organizationId = organizationId;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudyProtocolViewId))
			return false;
		StudyProtocolViewId castOther = (StudyProtocolViewId) other;

		return ((this.getStudyProtocolId() == castOther.getStudyProtocolId()) || (this
				.getStudyProtocolId() != null
				&& castOther.getStudyProtocolId() != null && this
				.getStudyProtocolId().equals(castOther.getStudyProtocolId())))
				&& ((this.getStudyNumber() == castOther.getStudyNumber()) || (this
						.getStudyNumber() != null
						&& castOther.getStudyNumber() != null && this
						.getStudyNumber().equals(castOther.getStudyNumber())))
				&& ((this.getSponsorStudyNumber() == castOther
						.getSponsorStudyNumber()) || (this
						.getSponsorStudyNumber() != null
						&& castOther.getSponsorStudyNumber() != null && this
						.getSponsorStudyNumber().equals(
								castOther.getSponsorStudyNumber())))
				&& ((this.getStudyTitle() == castOther.getStudyTitle()) || (this
						.getStudyTitle() != null
						&& castOther.getStudyTitle() != null && this
						.getStudyTitle().equals(castOther.getStudyTitle())))
				&& ((this.getStudyDirector() == castOther.getStudyDirector()) || (this
						.getStudyDirector() != null
						&& castOther.getStudyDirector() != null && this
						.getStudyDirector()
						.equals(castOther.getStudyDirector())))
				&& ((this.getSponsorStudyTitle() == castOther
						.getSponsorStudyTitle()) || (this
						.getSponsorStudyTitle() != null
						&& castOther.getSponsorStudyTitle() != null && this
						.getSponsorStudyTitle().equals(
								castOther.getSponsorStudyTitle())))
				&& ((this.getContactId() == castOther.getContactId()) || (this
						.getContactId() != null
						&& castOther.getContactId() != null && this
						.getContactId().equals(castOther.getContactId())))
				&& ((this.getCascadeAccessionNumber() == castOther
						.getCascadeAccessionNumber()) || (this
						.getCascadeAccessionNumber() != null
						&& castOther.getCascadeAccessionNumber() != null && this
						.getCascadeAccessionNumber().equals(
								castOther.getCascadeAccessionNumber())))
				&& ((this.getBarcodeLength() == castOther.getBarcodeLength()) || (this
						.getBarcodeLength() != null
						&& castOther.getBarcodeLength() != null && this
						.getBarcodeLength()
						.equals(castOther.getBarcodeLength())))
				&& ((this.getFinalTubeBarcodeLowValue() == castOther
						.getFinalTubeBarcodeLowValue()) || (this
						.getFinalTubeBarcodeLowValue() != null
						&& castOther.getFinalTubeBarcodeLowValue() != null && this
						.getFinalTubeBarcodeLowValue().equals(
								castOther.getFinalTubeBarcodeLowValue())))
				&& ((this.getFinalTubeBarcodeHighValue() == castOther
						.getFinalTubeBarcodeHighValue()) || (this
						.getFinalTubeBarcodeHighValue() != null
						&& castOther.getFinalTubeBarcodeHighValue() != null && this
						.getFinalTubeBarcodeHighValue().equals(
								castOther.getFinalTubeBarcodeHighValue())))
				&& ((this.getStudyClosed() == castOther.getStudyClosed()) || (this
						.getStudyClosed() != null
						&& castOther.getStudyClosed() != null && this
						.getStudyClosed().equals(castOther.getStudyClosed())))
				&& ((this.getShipDnaBack() == castOther.getShipDnaBack()) || (this
						.getShipDnaBack() != null
						&& castOther.getShipDnaBack() != null && this
						.getShipDnaBack().equals(castOther.getShipDnaBack())))
				&& ((this.getAccessionVarOcx() == castOther
						.getAccessionVarOcx()) || (this.getAccessionVarOcx() != null
						&& castOther.getAccessionVarOcx() != null && this
						.getAccessionVarOcx().equals(
								castOther.getAccessionVarOcx())))
				&& ((this.getStudyVarOcx() == castOther.getStudyVarOcx()) || (this
						.getStudyVarOcx() != null
						&& castOther.getStudyVarOcx() != null && this
						.getStudyVarOcx().equals(castOther.getStudyVarOcx())))
				&& ((this.getPatientVarOcx() == castOther.getPatientVarOcx()) || (this
						.getPatientVarOcx() != null
						&& castOther.getPatientVarOcx() != null && this
						.getPatientVarOcx()
						.equals(castOther.getPatientVarOcx())))
				&& ((this.getStudyUrl() == castOther.getStudyUrl()) || (this
						.getStudyUrl() != null
						&& castOther.getStudyUrl() != null && this
						.getStudyUrl().equals(castOther.getStudyUrl())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
						.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this
						.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getDateCreated() == castOther.getDateCreated()) || (this
						.getDateCreated() != null
						&& castOther.getDateCreated() != null && this
						.getDateCreated().equals(castOther.getDateCreated())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this
						.getModifiedBy() != null
						&& castOther.getModifiedBy() != null && this
						.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getDateModified() == castOther.getDateModified()) || (this
						.getDateModified() != null
						&& castOther.getDateModified() != null && this
						.getDateModified().equals(castOther.getDateModified())))
				&& ((this.getSubsidiaryId() == castOther.getSubsidiaryId()) || (this
						.getSubsidiaryId() != null
						&& castOther.getSubsidiaryId() != null && this
						.getSubsidiaryId().equals(castOther.getSubsidiaryId())))
				&& ((this.getStudyType() == castOther.getStudyType()) || (this
						.getStudyType() != null
						&& castOther.getStudyType() != null && this
						.getStudyType().equals(castOther.getStudyType())))
				&& ((this.getOrganizationId() == castOther.getOrganizationId()) || (this
						.getOrganizationId() != null
						&& castOther.getOrganizationId() != null && this
						.getOrganizationId().equals(
								castOther.getOrganizationId())))
				&& ((this.getCompany() == castOther.getCompany()) || (this
						.getCompany() != null && castOther.getCompany() != null && this
						.getCompany().equals(castOther.getCompany())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getStudyProtocolId() == null ? 0 : this.getStudyProtocolId()
						.hashCode());
		result = 37
				* result
				+ (getStudyNumber() == null ? 0 : this.getStudyNumber()
						.hashCode());
		result = 37
				* result
				+ (getSponsorStudyNumber() == null ? 0 : this
						.getSponsorStudyNumber().hashCode());
		result = 37
				* result
				+ (getStudyTitle() == null ? 0 : this.getStudyTitle()
						.hashCode());
		result = 37
				* result
				+ (getStudyDirector() == null ? 0 : this.getStudyDirector()
						.hashCode());
		result = 37
				* result
				+ (getSponsorStudyTitle() == null ? 0 : this
						.getSponsorStudyTitle().hashCode());
		result = 37 * result
				+ (getContactId() == null ? 0 : this.getContactId().hashCode());
		result = 37
				* result
				+ (getCascadeAccessionNumber() == null ? 0 : this
						.getCascadeAccessionNumber().hashCode());
		result = 37
				* result
				+ (getBarcodeLength() == null ? 0 : this.getBarcodeLength()
						.hashCode());
		result = 37
				* result
				+ (getFinalTubeBarcodeLowValue() == null ? 0 : this
						.getFinalTubeBarcodeLowValue().hashCode());
		result = 37
				* result
				+ (getFinalTubeBarcodeHighValue() == null ? 0 : this
						.getFinalTubeBarcodeHighValue().hashCode());
		result = 37
				* result
				+ (getStudyClosed() == null ? 0 : this.getStudyClosed()
						.hashCode());
		result = 37
				* result
				+ (getShipDnaBack() == null ? 0 : this.getShipDnaBack()
						.hashCode());
		result = 37
				* result
				+ (getAccessionVarOcx() == null ? 0 : this.getAccessionVarOcx()
						.hashCode());
		result = 37
				* result
				+ (getStudyVarOcx() == null ? 0 : this.getStudyVarOcx()
						.hashCode());
		result = 37
				* result
				+ (getPatientVarOcx() == null ? 0 : this.getPatientVarOcx()
						.hashCode());
		result = 37 * result
				+ (getStudyUrl() == null ? 0 : this.getStudyUrl().hashCode());
		result = 37 * result
				+ (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37
				* result
				+ (getDateCreated() == null ? 0 : this.getDateCreated()
						.hashCode());
		result = 37
				* result
				+ (getModifiedBy() == null ? 0 : this.getModifiedBy()
						.hashCode());
		result = 37
				* result
				+ (getDateModified() == null ? 0 : this.getDateModified()
						.hashCode());
		result = 37
				* result
				+ (getSubsidiaryId() == null ? 0 : this.getSubsidiaryId()
						.hashCode());
		result = 37 * result
				+ (getStudyType() == null ? 0 : this.getStudyType().hashCode());
		result = 37
				* result
				+ (getOrganizationId() == null ? 0 : this.getOrganizationId()
						.hashCode());
		result = 37 * result
				+ (getCompany() == null ? 0 : this.getCompany().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
