package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * TestSetupAttrView generated by hbm2java
 */
public class TestSetupAttrView implements java.io.Serializable {

	private TestSetupAttrViewId id;

	public TestSetupAttrView() {
	}

	public TestSetupAttrView(TestSetupAttrViewId id) {
		this.id = id;
	}

	public TestSetupAttrViewId getId() {
		return this.id;
	}

	public void setId(TestSetupAttrViewId id) {
		this.id = id;
	}

}
