package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TestSetupAttrViewId generated by hbm2java
 */
public class TestSetupAttrViewId implements java.io.Serializable {

	private String testNumber;
	private String testName;
	private String description;
	private Character lastCol;
	private Character attrValues;
	private BigDecimal testSetupId;
	private BigDecimal studyProtocolId;

	public TestSetupAttrViewId() {
	}

	public TestSetupAttrViewId(String testNumber, String testName,
			BigDecimal testSetupId, BigDecimal studyProtocolId) {
		this.testNumber = testNumber;
		this.testName = testName;
		this.testSetupId = testSetupId;
		this.studyProtocolId = studyProtocolId;
	}

	public TestSetupAttrViewId(String testNumber, String testName,
			String description, Character lastCol, Character attrValues,
			BigDecimal testSetupId, BigDecimal studyProtocolId) {
		this.testNumber = testNumber;
		this.testName = testName;
		this.description = description;
		this.lastCol = lastCol;
		this.attrValues = attrValues;
		this.testSetupId = testSetupId;
		this.studyProtocolId = studyProtocolId;
	}

	public String getTestNumber() {
		return this.testNumber;
	}

	public void setTestNumber(String testNumber) {
		this.testNumber = testNumber;
	}

	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Character getLastCol() {
		return this.lastCol;
	}

	public void setLastCol(Character lastCol) {
		this.lastCol = lastCol;
	}

	public Character getAttrValues() {
		return this.attrValues;
	}

	public void setAttrValues(Character attrValues) {
		this.attrValues = attrValues;
	}

	public BigDecimal getTestSetupId() {
		return this.testSetupId;
	}

	public void setTestSetupId(BigDecimal testSetupId) {
		this.testSetupId = testSetupId;
	}

	public BigDecimal getStudyProtocolId() {
		return this.studyProtocolId;
	}

	public void setStudyProtocolId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestSetupAttrViewId))
			return false;
		TestSetupAttrViewId castOther = (TestSetupAttrViewId) other;

		return ((this.getTestNumber() == castOther.getTestNumber()) || (this
				.getTestNumber() != null && castOther.getTestNumber() != null && this
				.getTestNumber().equals(castOther.getTestNumber())))
				&& ((this.getTestName() == castOther.getTestName()) || (this
						.getTestName() != null
						&& castOther.getTestName() != null && this
						.getTestName().equals(castOther.getTestName())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getLastCol() == castOther.getLastCol()) || (this
						.getLastCol() != null && castOther.getLastCol() != null && this
						.getLastCol().equals(castOther.getLastCol())))
				&& ((this.getAttrValues() == castOther.getAttrValues()) || (this
						.getAttrValues() != null
						&& castOther.getAttrValues() != null && this
						.getAttrValues().equals(castOther.getAttrValues())))
				&& ((this.getTestSetupId() == castOther.getTestSetupId()) || (this
						.getTestSetupId() != null
						&& castOther.getTestSetupId() != null && this
						.getTestSetupId().equals(castOther.getTestSetupId())))
				&& ((this.getStudyProtocolId() == castOther
						.getStudyProtocolId()) || (this.getStudyProtocolId() != null
						&& castOther.getStudyProtocolId() != null && this
						.getStudyProtocolId().equals(
								castOther.getStudyProtocolId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTestNumber() == null ? 0 : this.getTestNumber()
						.hashCode());
		result = 37 * result
				+ (getTestName() == null ? 0 : this.getTestName().hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getLastCol() == null ? 0 : this.getLastCol().hashCode());
		result = 37
				* result
				+ (getAttrValues() == null ? 0 : this.getAttrValues()
						.hashCode());
		result = 37
				* result
				+ (getTestSetupId() == null ? 0 : this.getTestSetupId()
						.hashCode());
		result = 37
				* result
				+ (getStudyProtocolId() == null ? 0 : this.getStudyProtocolId()
						.hashCode());
		return result;
	}

}
