package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * TrgeCase generated by hbm2java
 */
public class TrgeCase implements java.io.Serializable {

	private TrgeCaseId id;

	public TrgeCase() {
	}

	public TrgeCase(TrgeCaseId id) {
		this.id = id;
	}

	public TrgeCaseId getId() {
		return this.id;
	}

	public void setId(TrgeCaseId id) {
		this.id = id;
	}

}
