package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TrgeLiteratureId generated by hbm2java
 */
public class TrgeLiteratureId implements java.io.Serializable {

	private BigDecimal literatureId;
	private String authors;
	private String title;
	private String synopsis;
	private Date year;
	private String citation;
	private String pubmedId;

	public TrgeLiteratureId() {
	}

	public TrgeLiteratureId(BigDecimal literatureId, String authors,
			String title, Date year) {
		this.literatureId = literatureId;
		this.authors = authors;
		this.title = title;
		this.year = year;
	}

	public TrgeLiteratureId(BigDecimal literatureId, String authors,
			String title, String synopsis, Date year, String citation,
			String pubmedId) {
		this.literatureId = literatureId;
		this.authors = authors;
		this.title = title;
		this.synopsis = synopsis;
		this.year = year;
		this.citation = citation;
		this.pubmedId = pubmedId;
	}

	public BigDecimal getLiteratureId() {
		return this.literatureId;
	}

	public void setLiteratureId(BigDecimal literatureId) {
		this.literatureId = literatureId;
	}

	public String getAuthors() {
		return this.authors;
	}

	public void setAuthors(String authors) {
		this.authors = authors;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSynopsis() {
		return this.synopsis;
	}

	public void setSynopsis(String synopsis) {
		this.synopsis = synopsis;
	}

	public Date getYear() {
		return this.year;
	}

	public void setYear(Date year) {
		this.year = year;
	}

	public String getCitation() {
		return this.citation;
	}

	public void setCitation(String citation) {
		this.citation = citation;
	}

	public String getPubmedId() {
		return this.pubmedId;
	}

	public void setPubmedId(String pubmedId) {
		this.pubmedId = pubmedId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrgeLiteratureId))
			return false;
		TrgeLiteratureId castOther = (TrgeLiteratureId) other;

		return ((this.getLiteratureId() == castOther.getLiteratureId()) || (this
				.getLiteratureId() != null
				&& castOther.getLiteratureId() != null && this
				.getLiteratureId().equals(castOther.getLiteratureId())))
				&& ((this.getAuthors() == castOther.getAuthors()) || (this
						.getAuthors() != null && castOther.getAuthors() != null && this
						.getAuthors().equals(castOther.getAuthors())))
				&& ((this.getTitle() == castOther.getTitle()) || (this
						.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getSynopsis() == castOther.getSynopsis()) || (this
						.getSynopsis() != null
						&& castOther.getSynopsis() != null && this
						.getSynopsis().equals(castOther.getSynopsis())))
				&& ((this.getYear() == castOther.getYear()) || (this.getYear() != null
						&& castOther.getYear() != null && this.getYear()
						.equals(castOther.getYear())))
				&& ((this.getCitation() == castOther.getCitation()) || (this
						.getCitation() != null
						&& castOther.getCitation() != null && this
						.getCitation().equals(castOther.getCitation())))
				&& ((this.getPubmedId() == castOther.getPubmedId()) || (this
						.getPubmedId() != null
						&& castOther.getPubmedId() != null && this
						.getPubmedId().equals(castOther.getPubmedId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getLiteratureId() == null ? 0 : this.getLiteratureId()
						.hashCode());
		result = 37 * result
				+ (getAuthors() == null ? 0 : this.getAuthors().hashCode());
		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result
				+ (getSynopsis() == null ? 0 : this.getSynopsis().hashCode());
		result = 37 * result
				+ (getYear() == null ? 0 : this.getYear().hashCode());
		result = 37 * result
				+ (getCitation() == null ? 0 : this.getCitation().hashCode());
		result = 37 * result
				+ (getPubmedId() == null ? 0 : this.getPubmedId().hashCode());
		return result;
	}

}
