package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TrgeVarLitRelId generated by hbm2java
 */
public class TrgeVarLitRelId implements java.io.Serializable {

	private BigDecimal variantLiteratureId;
	private BigDecimal variantId;
	private BigDecimal literatureId;

	public TrgeVarLitRelId() {
	}

	public TrgeVarLitRelId(BigDecimal variantLiteratureId,
			BigDecimal variantId, BigDecimal literatureId) {
		this.variantLiteratureId = variantLiteratureId;
		this.variantId = variantId;
		this.literatureId = literatureId;
	}

	public BigDecimal getVariantLiteratureId() {
		return this.variantLiteratureId;
	}

	public void setVariantLiteratureId(BigDecimal variantLiteratureId) {
		this.variantLiteratureId = variantLiteratureId;
	}

	public BigDecimal getVariantId() {
		return this.variantId;
	}

	public void setVariantId(BigDecimal variantId) {
		this.variantId = variantId;
	}

	public BigDecimal getLiteratureId() {
		return this.literatureId;
	}

	public void setLiteratureId(BigDecimal literatureId) {
		this.literatureId = literatureId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrgeVarLitRelId))
			return false;
		TrgeVarLitRelId castOther = (TrgeVarLitRelId) other;

		return ((this.getVariantLiteratureId() == castOther
				.getVariantLiteratureId()) || (this.getVariantLiteratureId() != null
				&& castOther.getVariantLiteratureId() != null && this
				.getVariantLiteratureId().equals(
						castOther.getVariantLiteratureId())))
				&& ((this.getVariantId() == castOther.getVariantId()) || (this
						.getVariantId() != null
						&& castOther.getVariantId() != null && this
						.getVariantId().equals(castOther.getVariantId())))
				&& ((this.getLiteratureId() == castOther.getLiteratureId()) || (this
						.getLiteratureId() != null
						&& castOther.getLiteratureId() != null && this
						.getLiteratureId().equals(castOther.getLiteratureId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getVariantLiteratureId() == null ? 0 : this
						.getVariantLiteratureId().hashCode());
		result = 37 * result
				+ (getVariantId() == null ? 0 : this.getVariantId().hashCode());
		result = 37
				* result
				+ (getLiteratureId() == null ? 0 : this.getLiteratureId()
						.hashCode());
		return result;
	}

}
