package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * TrgeMinorAlleleFreq generated by hbm2java
 */
public class TrgeMinorAlleleFreq implements java.io.Serializable {

	private TrgeMinorAlleleFreqId id;

	public TrgeMinorAlleleFreq() {
	}

	public TrgeMinorAlleleFreq(TrgeMinorAlleleFreqId id) {
		this.id = id;
	}

	public TrgeMinorAlleleFreqId getId() {
		return this.id;
	}

	public void setId(TrgeMinorAlleleFreqId id) {
		this.id = id;
	}

}
