package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * TrgeTest generated by hbm2java
 */
public class TrgeTest implements java.io.Serializable {

	private TrgeTestId id;

	public TrgeTest() {
	}

	public TrgeTest(TrgeTestId id) {
		this.id = id;
	}

	public TrgeTestId getId() {
		return this.id;
	}

	public void setId(TrgeTestId id) {
		this.id = id;
	}

}
