package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TrgeClassificationId generated by hbm2java
 */
public class TrgeClassificationId implements java.io.Serializable {

	private BigDecimal classificationId;
	private String name;
	private String description;
	private String testClass;

	public TrgeClassificationId() {
	}

	public TrgeClassificationId(BigDecimal classificationId) {
		this.classificationId = classificationId;
	}

	public TrgeClassificationId(BigDecimal classificationId, String name,
			String description, String testClass) {
		this.classificationId = classificationId;
		this.name = name;
		this.description = description;
		this.testClass = testClass;
	}

	public BigDecimal getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(BigDecimal classificationId) {
		this.classificationId = classificationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTestClass() {
		return this.testClass;
	}

	public void setTestClass(String testClass) {
		this.testClass = testClass;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrgeClassificationId))
			return false;
		TrgeClassificationId castOther = (TrgeClassificationId) other;

		return ((this.getClassificationId() == castOther.getClassificationId()) || (this
				.getClassificationId() != null
				&& castOther.getClassificationId() != null && this
				.getClassificationId().equals(castOther.getClassificationId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getTestClass() == castOther.getTestClass()) || (this
						.getTestClass() != null
						&& castOther.getTestClass() != null && this
						.getTestClass().equals(castOther.getTestClass())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getClassificationId() == null ? 0 : this
						.getClassificationId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getTestClass() == null ? 0 : this.getTestClass().hashCode());
		return result;
	}

}
