package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * TrgeGeneRegion generated by hbm2java
 */
public class TrgeGeneRegion implements java.io.Serializable {

	private TrgeGeneRegionId id;

	public TrgeGeneRegion() {
	}

	public TrgeGeneRegion(TrgeGeneRegionId id) {
		this.id = id;
	}

	public TrgeGeneRegionId getId() {
		return this.id;
	}

	public void setId(TrgeGeneRegionId id) {
		this.id = id;
	}

}
