package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * VariantTestnameViewId generated by hbm2java
 */
public class VariantTestnameViewId implements java.io.Serializable {

	private BigDecimal testSetupId;
	private String caseId;
	private BigDecimal roiId;
	private String testName;
	private String testNumber;

	public VariantTestnameViewId() {
	}

	public VariantTestnameViewId(String testName, String testNumber) {
		this.testName = testName;
		this.testNumber = testNumber;
	}

	public VariantTestnameViewId(BigDecimal testSetupId, String caseId,
			BigDecimal roiId, String testName, String testNumber) {
		this.testSetupId = testSetupId;
		this.caseId = caseId;
		this.roiId = roiId;
		this.testName = testName;
		this.testNumber = testNumber;
	}

	public BigDecimal getTestSetupId() {
		return this.testSetupId;
	}

	public void setTestSetupId(BigDecimal testSetupId) {
		this.testSetupId = testSetupId;
	}

	public String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public BigDecimal getRoiId() {
		return this.roiId;
	}

	public void setRoiId(BigDecimal roiId) {
		this.roiId = roiId;
	}

	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	public String getTestNumber() {
		return this.testNumber;
	}

	public void setTestNumber(String testNumber) {
		this.testNumber = testNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VariantTestnameViewId))
			return false;
		VariantTestnameViewId castOther = (VariantTestnameViewId) other;

		return ((this.getTestSetupId() == castOther.getTestSetupId()) || (this
				.getTestSetupId() != null && castOther.getTestSetupId() != null && this
				.getTestSetupId().equals(castOther.getTestSetupId())))
				&& ((this.getCaseId() == castOther.getCaseId()) || (this
						.getCaseId() != null && castOther.getCaseId() != null && this
						.getCaseId().equals(castOther.getCaseId())))
				&& ((this.getRoiId() == castOther.getRoiId()) || (this
						.getRoiId() != null && castOther.getRoiId() != null && this
						.getRoiId().equals(castOther.getRoiId())))
				&& ((this.getTestName() == castOther.getTestName()) || (this
						.getTestName() != null
						&& castOther.getTestName() != null && this
						.getTestName().equals(castOther.getTestName())))
				&& ((this.getTestNumber() == castOther.getTestNumber()) || (this
						.getTestNumber() != null
						&& castOther.getTestNumber() != null && this
						.getTestNumber().equals(castOther.getTestNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTestSetupId() == null ? 0 : this.getTestSetupId()
						.hashCode());
		result = 37 * result
				+ (getCaseId() == null ? 0 : this.getCaseId().hashCode());
		result = 37 * result
				+ (getRoiId() == null ? 0 : this.getRoiId().hashCode());
		result = 37 * result
				+ (getTestName() == null ? 0 : this.getTestName().hashCode());
		result = 37
				* result
				+ (getTestNumber() == null ? 0 : this.getTestNumber()
						.hashCode());
		return result;
	}

}
