package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * VariantCaseRoiView generated by hbm2java
 */
public class VariantCaseRoiView implements java.io.Serializable {

	private VariantCaseRoiViewId id;

	public VariantCaseRoiView() {
	}

	public VariantCaseRoiView(VariantCaseRoiViewId id) {
		this.id = id;
	}

	public VariantCaseRoiViewId getId() {
		return this.id;
	}

	public void setId(VariantCaseRoiViewId id) {
		this.id = id;
	}

}
