package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * VendProjStudyDtlsViewId generated by hbm2java
 */
public class VendProjStudyDtlsViewId implements java.io.Serializable {

	private BigDecimal projectId;
	private String company;
	private BigDecimal organizationId;
	private BigDecimal studyProtocolId;
	private String studyNumber;
	private String sponsorStudyNumber;
	private String containerId;
	private BigDecimal totalSampleNo;
	private String geneName;
	private String alleles;
	private BigDecimal assayNo;
	private String fgid;
	private String fpi;
	private String lpi;
	private String lpo;
	private String dbl;
	private String genotypingReport;
	private String samplePreparation;
	private String businessUnit;

	public VendProjStudyDtlsViewId() {
	}

	public VendProjStudyDtlsViewId(String company, BigDecimal organizationId,
			BigDecimal studyProtocolId, String geneName) {
		this.company = company;
		this.organizationId = organizationId;
		this.studyProtocolId = studyProtocolId;
		this.geneName = geneName;
	}

	public VendProjStudyDtlsViewId(BigDecimal projectId, String company,
			BigDecimal organizationId, BigDecimal studyProtocolId,
			String studyNumber, String sponsorStudyNumber, String containerId,
			BigDecimal totalSampleNo, String geneName, String alleles,
			BigDecimal assayNo, String fgid, String fpi, String lpi,
			String lpo, String dbl, String genotypingReport,
			String samplePreparation, String businessUnit) {
		this.projectId = projectId;
		this.company = company;
		this.organizationId = organizationId;
		this.studyProtocolId = studyProtocolId;
		this.studyNumber = studyNumber;
		this.sponsorStudyNumber = sponsorStudyNumber;
		this.containerId = containerId;
		this.totalSampleNo = totalSampleNo;
		this.geneName = geneName;
		this.alleles = alleles;
		this.assayNo = assayNo;
		this.fgid = fgid;
		this.fpi = fpi;
		this.lpi = lpi;
		this.lpo = lpo;
		this.dbl = dbl;
		this.genotypingReport = genotypingReport;
		this.samplePreparation = samplePreparation;
		this.businessUnit = businessUnit;
	}

	public BigDecimal getProjectId() {
		return this.projectId;
	}

	public void setProjectId(BigDecimal projectId) {
		this.projectId = projectId;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public BigDecimal getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(BigDecimal organizationId) {
		this.organizationId = organizationId;
	}

	public BigDecimal getStudyProtocolId() {
		return this.studyProtocolId;
	}

	public void setStudyProtocolId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public String getStudyNumber() {
		return this.studyNumber;
	}

	public void setStudyNumber(String studyNumber) {
		this.studyNumber = studyNumber;
	}

	public String getSponsorStudyNumber() {
		return this.sponsorStudyNumber;
	}

	public void setSponsorStudyNumber(String sponsorStudyNumber) {
		this.sponsorStudyNumber = sponsorStudyNumber;
	}

	public String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(String containerId) {
		this.containerId = containerId;
	}

	public BigDecimal getTotalSampleNo() {
		return this.totalSampleNo;
	}

	public void setTotalSampleNo(BigDecimal totalSampleNo) {
		this.totalSampleNo = totalSampleNo;
	}

	public String getGeneName() {
		return this.geneName;
	}

	public void setGeneName(String geneName) {
		this.geneName = geneName;
	}

	public String getAlleles() {
		return this.alleles;
	}

	public void setAlleles(String alleles) {
		this.alleles = alleles;
	}

	public BigDecimal getAssayNo() {
		return this.assayNo;
	}

	public void setAssayNo(BigDecimal assayNo) {
		this.assayNo = assayNo;
	}

	public String getFgid() {
		return this.fgid;
	}

	public void setFgid(String fgid) {
		this.fgid = fgid;
	}

	public String getFpi() {
		return this.fpi;
	}

	public void setFpi(String fpi) {
		this.fpi = fpi;
	}

	public String getLpi() {
		return this.lpi;
	}

	public void setLpi(String lpi) {
		this.lpi = lpi;
	}

	public String getLpo() {
		return this.lpo;
	}

	public void setLpo(String lpo) {
		this.lpo = lpo;
	}

	public String getDbl() {
		return this.dbl;
	}

	public void setDbl(String dbl) {
		this.dbl = dbl;
	}

	public String getGenotypingReport() {
		return this.genotypingReport;
	}

	public void setGenotypingReport(String genotypingReport) {
		this.genotypingReport = genotypingReport;
	}

	public String getSamplePreparation() {
		return this.samplePreparation;
	}

	public void setSamplePreparation(String samplePreparation) {
		this.samplePreparation = samplePreparation;
	}

	public String getBusinessUnit() {
		return this.businessUnit;
	}

	public void setBusinessUnit(String businessUnit) {
		this.businessUnit = businessUnit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VendProjStudyDtlsViewId))
			return false;
		VendProjStudyDtlsViewId castOther = (VendProjStudyDtlsViewId) other;

		return ((this.getProjectId() == castOther.getProjectId()) || (this
				.getProjectId() != null && castOther.getProjectId() != null && this
				.getProjectId().equals(castOther.getProjectId())))
				&& ((this.getCompany() == castOther.getCompany()) || (this
						.getCompany() != null && castOther.getCompany() != null && this
						.getCompany().equals(castOther.getCompany())))
				&& ((this.getOrganizationId() == castOther.getOrganizationId()) || (this
						.getOrganizationId() != null
						&& castOther.getOrganizationId() != null && this
						.getOrganizationId().equals(
								castOther.getOrganizationId())))
				&& ((this.getStudyProtocolId() == castOther
						.getStudyProtocolId()) || (this.getStudyProtocolId() != null
						&& castOther.getStudyProtocolId() != null && this
						.getStudyProtocolId().equals(
								castOther.getStudyProtocolId())))
				&& ((this.getStudyNumber() == castOther.getStudyNumber()) || (this
						.getStudyNumber() != null
						&& castOther.getStudyNumber() != null && this
						.getStudyNumber().equals(castOther.getStudyNumber())))
				&& ((this.getSponsorStudyNumber() == castOther
						.getSponsorStudyNumber()) || (this
						.getSponsorStudyNumber() != null
						&& castOther.getSponsorStudyNumber() != null && this
						.getSponsorStudyNumber().equals(
								castOther.getSponsorStudyNumber())))
				&& ((this.getContainerId() == castOther.getContainerId()) || (this
						.getContainerId() != null
						&& castOther.getContainerId() != null && this
						.getContainerId().equals(castOther.getContainerId())))
				&& ((this.getTotalSampleNo() == castOther.getTotalSampleNo()) || (this
						.getTotalSampleNo() != null
						&& castOther.getTotalSampleNo() != null && this
						.getTotalSampleNo()
						.equals(castOther.getTotalSampleNo())))
				&& ((this.getGeneName() == castOther.getGeneName()) || (this
						.getGeneName() != null
						&& castOther.getGeneName() != null && this
						.getGeneName().equals(castOther.getGeneName())))
				&& ((this.getAlleles() == castOther.getAlleles()) || (this
						.getAlleles() != null && castOther.getAlleles() != null && this
						.getAlleles().equals(castOther.getAlleles())))
				&& ((this.getAssayNo() == castOther.getAssayNo()) || (this
						.getAssayNo() != null && castOther.getAssayNo() != null && this
						.getAssayNo().equals(castOther.getAssayNo())))
				&& ((this.getFgid() == castOther.getFgid()) || (this.getFgid() != null
						&& castOther.getFgid() != null && this.getFgid()
						.equals(castOther.getFgid())))
				&& ((this.getFpi() == castOther.getFpi()) || (this.getFpi() != null
						&& castOther.getFpi() != null && this.getFpi().equals(
						castOther.getFpi())))
				&& ((this.getLpi() == castOther.getLpi()) || (this.getLpi() != null
						&& castOther.getLpi() != null && this.getLpi().equals(
						castOther.getLpi())))
				&& ((this.getLpo() == castOther.getLpo()) || (this.getLpo() != null
						&& castOther.getLpo() != null && this.getLpo().equals(
						castOther.getLpo())))
				&& ((this.getDbl() == castOther.getDbl()) || (this.getDbl() != null
						&& castOther.getDbl() != null && this.getDbl().equals(
						castOther.getDbl())))
				&& ((this.getGenotypingReport() == castOther
						.getGenotypingReport()) || (this.getGenotypingReport() != null
						&& castOther.getGenotypingReport() != null && this
						.getGenotypingReport().equals(
								castOther.getGenotypingReport())))
				&& ((this.getSamplePreparation() == castOther
						.getSamplePreparation()) || (this
						.getSamplePreparation() != null
						&& castOther.getSamplePreparation() != null && this
						.getSamplePreparation().equals(
								castOther.getSamplePreparation())))
				&& ((this.getBusinessUnit() == castOther.getBusinessUnit()) || (this
						.getBusinessUnit() != null
						&& castOther.getBusinessUnit() != null && this
						.getBusinessUnit().equals(castOther.getBusinessUnit())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProjectId() == null ? 0 : this.getProjectId().hashCode());
		result = 37 * result
				+ (getCompany() == null ? 0 : this.getCompany().hashCode());
		result = 37
				* result
				+ (getOrganizationId() == null ? 0 : this.getOrganizationId()
						.hashCode());
		result = 37
				* result
				+ (getStudyProtocolId() == null ? 0 : this.getStudyProtocolId()
						.hashCode());
		result = 37
				* result
				+ (getStudyNumber() == null ? 0 : this.getStudyNumber()
						.hashCode());
		result = 37
				* result
				+ (getSponsorStudyNumber() == null ? 0 : this
						.getSponsorStudyNumber().hashCode());
		result = 37
				* result
				+ (getContainerId() == null ? 0 : this.getContainerId()
						.hashCode());
		result = 37
				* result
				+ (getTotalSampleNo() == null ? 0 : this.getTotalSampleNo()
						.hashCode());
		result = 37 * result
				+ (getGeneName() == null ? 0 : this.getGeneName().hashCode());
		result = 37 * result
				+ (getAlleles() == null ? 0 : this.getAlleles().hashCode());
		result = 37 * result
				+ (getAssayNo() == null ? 0 : this.getAssayNo().hashCode());
		result = 37 * result
				+ (getFgid() == null ? 0 : this.getFgid().hashCode());
		result = 37 * result
				+ (getFpi() == null ? 0 : this.getFpi().hashCode());
		result = 37 * result
				+ (getLpi() == null ? 0 : this.getLpi().hashCode());
		result = 37 * result
				+ (getLpo() == null ? 0 : this.getLpo().hashCode());
		result = 37 * result
				+ (getDbl() == null ? 0 : this.getDbl().hashCode());
		result = 37
				* result
				+ (getGenotypingReport() == null ? 0 : this
						.getGenotypingReport().hashCode());
		result = 37
				* result
				+ (getSamplePreparation() == null ? 0 : this
						.getSamplePreparation().hashCode());
		result = 37
				* result
				+ (getBusinessUnit() == null ? 0 : this.getBusinessUnit()
						.hashCode());
		return result;
	}

}
