package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkflowCaseTraceItemView generated by hbm2java
 */
public class WorkflowCaseTraceItemView implements java.io.Serializable {

	private WorkflowCaseTraceItemViewId id;

	public WorkflowCaseTraceItemView() {
	}

	public WorkflowCaseTraceItemView(WorkflowCaseTraceItemViewId id) {
		this.id = id;
	}

	public WorkflowCaseTraceItemViewId getId() {
		return this.id;
	}

	public void setId(WorkflowCaseTraceItemViewId id) {
		this.id = id;
	}

}
