package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * WorkflowNodeViewId generated by hbm2java
 */
public class WorkflowNodeViewId implements java.io.Serializable {

	private BigDecimal workflowItemId;
	private BigDecimal workflowNodeId;
	private BigDecimal workflowId;
	private String nodeName;
	private String nodeType;
	private String status;
	private BigDecimal traverseCount;
	private BigDecimal checklistId;
	private String assignedTo;
	private String procedureName;
	private String sopNumber;
	private String sopVersion;

	public WorkflowNodeViewId() {
	}

	public WorkflowNodeViewId(BigDecimal workflowNodeId) {
		this.workflowNodeId = workflowNodeId;
	}

	public WorkflowNodeViewId(BigDecimal workflowItemId,
			BigDecimal workflowNodeId, BigDecimal workflowId, String nodeName,
			String nodeType, String status, BigDecimal traverseCount,
			BigDecimal checklistId, String assignedTo, String procedureName,
			String sopNumber, String sopVersion) {
		this.workflowItemId = workflowItemId;
		this.workflowNodeId = workflowNodeId;
		this.workflowId = workflowId;
		this.nodeName = nodeName;
		this.nodeType = nodeType;
		this.status = status;
		this.traverseCount = traverseCount;
		this.checklistId = checklistId;
		this.assignedTo = assignedTo;
		this.procedureName = procedureName;
		this.sopNumber = sopNumber;
		this.sopVersion = sopVersion;
	}

	public BigDecimal getWorkflowItemId() {
		return this.workflowItemId;
	}

	public void setWorkflowItemId(BigDecimal workflowItemId) {
		this.workflowItemId = workflowItemId;
	}

	public BigDecimal getWorkflowNodeId() {
		return this.workflowNodeId;
	}

	public void setWorkflowNodeId(BigDecimal workflowNodeId) {
		this.workflowNodeId = workflowNodeId;
	}

	public BigDecimal getWorkflowId() {
		return this.workflowId;
	}

	public void setWorkflowId(BigDecimal workflowId) {
		this.workflowId = workflowId;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getNodeType() {
		return this.nodeType;
	}

	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getTraverseCount() {
		return this.traverseCount;
	}

	public void setTraverseCount(BigDecimal traverseCount) {
		this.traverseCount = traverseCount;
	}

	public BigDecimal getChecklistId() {
		return this.checklistId;
	}

	public void setChecklistId(BigDecimal checklistId) {
		this.checklistId = checklistId;
	}

	public String getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(String assignedTo) {
		this.assignedTo = assignedTo;
	}

	public String getProcedureName() {
		return this.procedureName;
	}

	public void setProcedureName(String procedureName) {
		this.procedureName = procedureName;
	}

	public String getSopNumber() {
		return this.sopNumber;
	}

	public void setSopNumber(String sopNumber) {
		this.sopNumber = sopNumber;
	}

	public String getSopVersion() {
		return this.sopVersion;
	}

	public void setSopVersion(String sopVersion) {
		this.sopVersion = sopVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WorkflowNodeViewId))
			return false;
		WorkflowNodeViewId castOther = (WorkflowNodeViewId) other;

		return ((this.getWorkflowItemId() == castOther.getWorkflowItemId()) || (this
				.getWorkflowItemId() != null
				&& castOther.getWorkflowItemId() != null && this
				.getWorkflowItemId().equals(castOther.getWorkflowItemId())))
				&& ((this.getWorkflowNodeId() == castOther.getWorkflowNodeId()) || (this
						.getWorkflowNodeId() != null
						&& castOther.getWorkflowNodeId() != null && this
						.getWorkflowNodeId().equals(
								castOther.getWorkflowNodeId())))
				&& ((this.getWorkflowId() == castOther.getWorkflowId()) || (this
						.getWorkflowId() != null
						&& castOther.getWorkflowId() != null && this
						.getWorkflowId().equals(castOther.getWorkflowId())))
				&& ((this.getNodeName() == castOther.getNodeName()) || (this
						.getNodeName() != null
						&& castOther.getNodeName() != null && this
						.getNodeName().equals(castOther.getNodeName())))
				&& ((this.getNodeType() == castOther.getNodeType()) || (this
						.getNodeType() != null
						&& castOther.getNodeType() != null && this
						.getNodeType().equals(castOther.getNodeType())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getTraverseCount() == castOther.getTraverseCount()) || (this
						.getTraverseCount() != null
						&& castOther.getTraverseCount() != null && this
						.getTraverseCount()
						.equals(castOther.getTraverseCount())))
				&& ((this.getChecklistId() == castOther.getChecklistId()) || (this
						.getChecklistId() != null
						&& castOther.getChecklistId() != null && this
						.getChecklistId().equals(castOther.getChecklistId())))
				&& ((this.getAssignedTo() == castOther.getAssignedTo()) || (this
						.getAssignedTo() != null
						&& castOther.getAssignedTo() != null && this
						.getAssignedTo().equals(castOther.getAssignedTo())))
				&& ((this.getProcedureName() == castOther.getProcedureName()) || (this
						.getProcedureName() != null
						&& castOther.getProcedureName() != null && this
						.getProcedureName()
						.equals(castOther.getProcedureName())))
				&& ((this.getSopNumber() == castOther.getSopNumber()) || (this
						.getSopNumber() != null
						&& castOther.getSopNumber() != null && this
						.getSopNumber().equals(castOther.getSopNumber())))
				&& ((this.getSopVersion() == castOther.getSopVersion()) || (this
						.getSopVersion() != null
						&& castOther.getSopVersion() != null && this
						.getSopVersion().equals(castOther.getSopVersion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getWorkflowItemId() == null ? 0 : this.getWorkflowItemId()
						.hashCode());
		result = 37
				* result
				+ (getWorkflowNodeId() == null ? 0 : this.getWorkflowNodeId()
						.hashCode());
		result = 37
				* result
				+ (getWorkflowId() == null ? 0 : this.getWorkflowId()
						.hashCode());
		result = 37 * result
				+ (getNodeName() == null ? 0 : this.getNodeName().hashCode());
		result = 37 * result
				+ (getNodeType() == null ? 0 : this.getNodeType().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37
				* result
				+ (getTraverseCount() == null ? 0 : this.getTraverseCount()
						.hashCode());
		result = 37
				* result
				+ (getChecklistId() == null ? 0 : this.getChecklistId()
						.hashCode());
		result = 37
				* result
				+ (getAssignedTo() == null ? 0 : this.getAssignedTo()
						.hashCode());
		result = 37
				* result
				+ (getProcedureName() == null ? 0 : this.getProcedureName()
						.hashCode());
		result = 37 * result
				+ (getSopNumber() == null ? 0 : this.getSopNumber().hashCode());
		result = 37
				* result
				+ (getSopVersion() == null ? 0 : this.getSopVersion()
						.hashCode());
		return result;
	}

}
