package com.cardiodx.db.waban.view;

// Generated Jul 14, 2011 1:33:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkflowCaseSeqItemView generated by hbm2java
 */
public class WorkflowCaseSeqItemView implements java.io.Serializable {

	private WorkflowCaseSeqItemViewId id;

	public WorkflowCaseSeqItemView() {
	}

	public WorkflowCaseSeqItemView(WorkflowCaseSeqItemViewId id) {
		this.id = id;
	}

	public WorkflowCaseSeqItemViewId getId() {
		return this.id;
	}

	public void setId(WorkflowCaseSeqItemViewId id) {
		this.id = id;
	}

}
