
-- entity type
truncate table entity_type;
insert into entity_type values ('1', 'Individual');
insert into entity_type values ('2', 'Organization');


-- sole proprietor
truncate table sole_proprietor;
insert into sole_proprietor values ('X', 'Not Answered');
insert into sole_proprietor values ('Y', 'Yes');
insert into sole_proprietor values ('N', 'No');


-- Subpart Codes
truncate table subpart;
insert into subpart values ('X', 'Not Answered');
insert into subpart values ('Y', 'Yes');
insert into subpart values ('N', 'No');


-- Gender Codes
truncate table gender;
insert into gender values ('M', 'Male');
insert into gender values ('F', 'Female');


-- Deactivation Reason Codes
truncate table deactivation_reason;
insert into deactivation_reason values ('DT', 'Death');
insert into deactivation_reason values ('DB', 'Disbandment');
insert into deactivation_reason values ('FR', 'Fraud');
insert into deactivation_reason values ('OT', 'Other');


-- Other Provider Name Type Codes
truncate table other_provider_name_type;
insert into other_provider_name_type values ('1', 'Former Name', 'I');
insert into other_provider_name_type values ('2', 'Professional Name', 'I');
insert into other_provider_name_type values ('3', 'Doing Business As', 'O');
insert into other_provider_name_type values ('4', 'Former Legal Business Name', 'O');
insert into other_provider_name_type values ('5', 'Other Name', 'B');


-- Name Prefix Codes
truncate table name_prefix;
insert into name_prefix values ('Ms.', 'Ms.');
insert into name_prefix values ('Mr.', 'Mr.');
insert into name_prefix values ('Miss', 'Miss');
insert into name_prefix values ('Dr.', 'Dr.');
insert into name_prefix values ('Prof.', 'Prof.');


-- Name Suffix Codes
truncate table name_suffix;
insert into name_suffix values ('Jr.', 'Jr.');
insert into name_suffix values ('Sr.', 'Sr.');
insert into name_suffix values ('I', 'I');
insert into name_suffix values ('II', 'II');
insert into name_suffix values ('III', 'III');
insert into name_suffix values ('IV', 'IV');
insert into name_suffix values ('V', 'V');
insert into name_suffix values ('VI', 'VI');
insert into name_suffix values ('VII', 'VII');
insert into name_suffix values ('VIII', 'VIII');
insert into name_suffix values ('IX', 'IX');


-- State Codes
truncate table state;
insert into state values ('AK', 'ALASKA', 'S');
insert into state values ('AL', 'ALABAMA', 'S');
insert into state values ('AR', 'ARKANSAS', 'S');
insert into state values ('AS', 'AMERICAN SAMOA', 'T');
insert into state values ('AZ', 'ARIZONA', 'S');
insert into state values ('CA', 'CALIFORNIA', 'S');
insert into state values ('CO', 'COLORADO', 'S');
insert into state values ('CT', 'CONNECTICUT', 'S');
insert into state values ('DC', 'DISTRICT OF COLUMBIA', 'T');
insert into state values ('DE', 'DELAWARE', 'S');
insert into state values ('FL', 'FLORIDA', 'S');
insert into state values ('FM', 'MICRONESIA, FEDERATED STATES OF', 'T');
insert into state values ('GA', 'GEORGIA', 'S');
insert into state values ('GU', 'GUAM', 'T');
insert into state values ('HI', 'HAWAII', 'S');
insert into state values ('IA', 'IOWA', 'S');
insert into state values ('ID', 'IDAHO', 'S');
insert into state values ('IL', 'ILLINOIS', 'S');
insert into state values ('IN', 'INDIANA', 'S');
insert into state values ('KS', 'KANSAS', 'S');
insert into state values ('KY', 'KENTUCKY', 'S');
insert into state values ('LA', 'LOUISIANA', 'S');
insert into state values ('MA', 'MASSACHUSETTS', 'S');
insert into state values ('MD', 'MARYLAND', 'S');
insert into state values ('ME', 'MAINE', 'S');
insert into state values ('MH', 'MARSHALL ISLANDS', 'T');
insert into state values ('MI', 'MICHIGAN', 'S');
insert into state values ('MN', 'MINNESOTA', 'S');
insert into state values ('MO', 'MISSOURI', 'S');
insert into state values ('MP', 'MARIANA ISLANDS, NORTHERN', 'T');
insert into state values ('MS', 'MISSISSIPPI', 'S');
insert into state values ('MT', 'MONTANA', 'S');
insert into state values ('NC', 'NORTH CAROLINA', 'S');
insert into state values ('ND', 'NORTH DAKOTA', 'S');
insert into state values ('NE', 'NEBRASKA', 'S');
insert into state values ('NH', 'NEW HAMPSHIRE', 'S');
insert into state values ('NJ', 'NEW JERSEY', 'S');
insert into state values ('NM', 'NEW MEXICO', 'S');
insert into state values ('NV', 'NEVADA', 'S');
insert into state values ('NY', 'NEW YORK', 'S');
insert into state values ('OH', 'OHIO', 'S');
insert into state values ('OK', 'OKLAHOMA', 'S');
insert into state values ('OR', 'OREGON', 'S');
insert into state values ('PA', 'PENNSYLVANIA', 'S');
insert into state values ('PR', 'PUERTO RICO', 'T');
insert into state values ('PW', 'PALAU', 'T');
insert into state values ('RI', 'RHODE ISLAND', 'S');
insert into state values ('SC', 'SOUTH CAROLINA', 'S');
insert into state values ('SD', 'SOUTH DAKOTA', 'S');
insert into state values ('TN', 'TENNESSEE', 'S');
insert into state values ('TX', 'TEXAS', 'S');
insert into state values ('UT', 'UTAH', 'S');
insert into state values ('VA', 'VIRGINIA', 'S');
insert into state values ('VI', 'VIRGIN ISLANDS', 'T');
insert into state values ('VT', 'VERMONT', 'S');
insert into state values ('WA', 'WASHINGTON', 'S');
insert into state values ('WI', 'WISCONSIN', 'S');
insert into state values ('WV', 'WEST VIRGINIA', 'S');
insert into state values ('WY', 'WYOMING', 'S');
insert into state values ('ZZ', 'Foreign Country', 'T');


-- Country Codes
truncate table country;
insert into country values ('AD', 'ANDORRA');
insert into country values ('AE', 'UNITED ARAB EMIRATES');
insert into country values ('AF', 'AFGHANISTAN');
insert into country values ('AG', 'ANTIGUA AND BARBUDA');
insert into country values ('AI', 'ANGUILLA');
insert into country values ('AL', 'ALBANIA');
insert into country values ('AM', 'ARMENIA');
insert into country values ('AN', 'NETHERLANDS ANTILLES');
insert into country values ('AO', 'ANGOLA');
insert into country values ('AQ', 'ANTARCTICA');
insert into country values ('AR', 'ARGENTINA');
insert into country values ('AT', 'AUSTRIA');
insert into country values ('AU', 'AUSTRALIA');
insert into country values ('AW', 'ARUBA');
insert into country values ('AX', 'ALAND ISLANDS');
insert into country values ('AZ', 'AZERBAIJAN');
insert into country values ('BA', 'BOSNIA AND HERZEGOVINA');
insert into country values ('BB', 'BARBADOS');
insert into country values ('BD', 'BANGLADESH');
insert into country values ('BE', 'BELGIUM');
insert into country values ('BF', 'BURKINA FASO');
insert into country values ('BG', 'BULGARIA');
insert into country values ('BH', 'BAHRAIN');
insert into country values ('BI', 'BURUNDI');
insert into country values ('BJ', 'BENIN');
insert into country values ('BM', 'BERMUDA');
insert into country values ('BN', 'BRUNEI DARUSSALAM');
insert into country values ('BO', 'BOLIVIA');
insert into country values ('BR', 'BRAZIL');
insert into country values ('BS', 'BAHAMAS');
insert into country values ('BT', 'BHUTAN');
insert into country values ('BV', 'BOUVET ISLAND');
insert into country values ('BW', 'BOTSWANA');
insert into country values ('BY', 'BELARUS');
insert into country values ('BZ', 'BELIZE');
insert into country values ('CA', 'CANADA');
insert into country values ('CC', 'COCOS (KEELING) ISLANDS');
insert into country values ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE');
insert into country values ('CF', 'CENTRAL AFRICAN REPUBLIC');
insert into country values ('CG', 'CONGO');
insert into country values ('CH', 'SWITZERLAND');
insert into country values ('CI', 'CÔTE D\'IVOIRE');
insert into country values ('CK', 'COOK ISLANDS');
insert into country values ('CL', 'CHILE');
insert into country values ('CM', 'CAMEROON');
insert into country values ('CN', 'CHINA');
insert into country values ('CO', 'COLOMBIA');
insert into country values ('CR', 'COSTA RICA');
insert into country values ('CS', 'SERBIA AND MONTENEGRO');
insert into country values ('CU', 'CUBA');
insert into country values ('CV', 'CAPE VERDE');
insert into country values ('CX', 'CHRISTMAS ISLAND');
insert into country values ('CY', 'CYPRUS');
insert into country values ('CZ', 'CZECH REPUBLIC');
insert into country values ('DE', 'GERMANY');
insert into country values ('DJ', 'DJIBOUTI');
insert into country values ('DK', 'DENMARK');
insert into country values ('DM', 'DOMINICA');
insert into country values ('DO', 'DOMINICAN REPUBLIC');
insert into country values ('DZ', 'ALGERIA');
insert into country values ('EC', 'ECUADOR');
insert into country values ('EE', 'ESTONIA');
insert into country values ('EG', 'EGYPT');
insert into country values ('EH', 'WESTERN SAHARA');
insert into country values ('ER', 'ERITREA');
insert into country values ('ES', 'SPAIN');
insert into country values ('ET', 'ETHIOPIA');
insert into country values ('FI', 'FINLAND');
insert into country values ('FJ', 'FIJI');
insert into country values ('FK', 'FALKLAND ISLANDS (MALVINAS)');
insert into country values ('FO', 'FAROE ISLANDS');
insert into country values ('FR', 'FRANCE');
insert into country values ('GA', 'GABON');
insert into country values ('GB', 'GREAT BRITAIN (UK)');
insert into country values ('GD', 'GRENADA');
insert into country values ('GE', 'GEORGIA');
insert into country values ('GF', 'FRENCH GUIANA');
insert into country values ('GG', 'GUERNSEY');
insert into country values ('GH', 'GHANA');
insert into country values ('GI', 'GIBRALTAR');
insert into country values ('GL', 'GREENLAND');
insert into country values ('GM', 'GAMBIA');
insert into country values ('GN', 'GUINEA');
insert into country values ('GP', 'GUADELOUPE');
insert into country values ('GQ', 'EQUATORIAL GUINEA');
insert into country values ('GR', 'GREECE');
insert into country values ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
insert into country values ('GT', 'GUATEMALA');
insert into country values ('GW', 'GUINEA-BISSAU');
insert into country values ('GY', 'GUYANA');
insert into country values ('HK', 'HONG KONG');
insert into country values ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS');
insert into country values ('HN', 'HONDURAS');
insert into country values ('HR', 'CROATIA');
insert into country values ('HT', 'HAITI');
insert into country values ('HU', 'HUNGARY');
insert into country values ('ID', 'INDONESIA');
insert into country values ('IE', 'IRELAND');
insert into country values ('IL', 'ISRAEL');
insert into country values ('IM', 'ISLE OF MAN');
insert into country values ('IN', 'INDIA');
insert into country values ('IO', 'BRITISH INDIAN OCEAN TERRITORY');
insert into country values ('IQ', 'IRAQ');
insert into country values ('IR', 'IRAN, ISLAMIC REPUBLIC OF');
insert into country values ('IS', 'ICELAND');
insert into country values ('IT', 'ITALY');
insert into country values ('JE', 'JERSEY');
insert into country values ('JM', 'JAMAICA');
insert into country values ('JO', 'JORDAN');
insert into country values ('JP', 'JAPAN');
insert into country values ('KE', 'KENYA');
insert into country values ('KG', 'KYRGYZSTAN');
insert into country values ('KH', 'CAMBODIA');
insert into country values ('KI', 'KIRIBATI');
insert into country values ('KM', 'COMOROS');
insert into country values ('KN', 'SAINT KITTS AND NEVIS');
insert into country values ('KP', 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF');
insert into country values ('KR', 'KOREA, REPUBLIC OF');
insert into country values ('KW', 'KUWAIT');
insert into country values ('KY', 'CAYMAN ISLANDS');
insert into country values ('KZ', 'KAZAKHSTAN');
insert into country values ('LA', 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC');
insert into country values ('LB', 'LEBANON');
insert into country values ('LC', 'SAINT LUCIA');
insert into country values ('LI', 'LIECHTENSTEIN');
insert into country values ('LK', 'SRI LANKA');
insert into country values ('LR', 'LIBERIA');
insert into country values ('LS', 'LESOTHO');
insert into country values ('LT', 'LITHUANIA');
insert into country values ('LU', 'LUXEMBOURG');
insert into country values ('LV', 'LATVIA');
insert into country values ('LY', 'LIBYAN ARAB JAMAHIRIYA');
insert into country values ('MA', 'MOROCCO');
insert into country values ('MC', 'MONACO');
insert into country values ('MD', 'MOLDOVA, REPUBLIC OF');
insert into country values ('MG', 'MADAGASCAR');
insert into country values ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF');
insert into country values ('ML', 'MALI');
insert into country values ('MM', 'MYANMAR');
insert into country values ('MN', 'MONGOLIA');
insert into country values ('MO', 'MACAO');
insert into country values ('MQ', 'MARTINIQUE');
insert into country values ('MR', 'MAURITANIA');
insert into country values ('MS', 'MONTSERRAT');
insert into country values ('MT', 'MALTA');
insert into country values ('MU', 'MAURITIUS');
insert into country values ('MV', 'MALDIVES');
insert into country values ('MW', 'MALAWI');
insert into country values ('MX', 'MEXICO');
insert into country values ('MY', 'MALAYSIA');
insert into country values ('MZ', 'MOZAMBIQUE');
insert into country values ('NA', 'NAMIBIA');
insert into country values ('NC', 'NEW CALEDONIA');
insert into country values ('NE', 'NIGER');
insert into country values ('NF', 'NORFOLK ISLAND');
insert into country values ('NG', 'NIGERIA');
insert into country values ('NI', 'NICARAGUA');
insert into country values ('NL', 'NETHERLANDS');
insert into country values ('NO', 'NORWAY');
insert into country values ('NP', 'NEPAL');
insert into country values ('NR', 'NAURU');
insert into country values ('NU', 'NIUE');
insert into country values ('NZ', 'NEW ZEALAND');
insert into country values ('OM', 'OMAN');
insert into country values ('PA', 'PANAMA');
insert into country values ('PE', 'PERU');
insert into country values ('PF', 'FRENCH POLYNESIA');
insert into country values ('PG', 'PAPUA NEW GUINEA');
insert into country values ('PH', 'PHILIPPINES');
insert into country values ('PK', 'PAKISTAN');
insert into country values ('PL', 'POLAND');
insert into country values ('PM', 'SAINT PIERRE AND MIQUELON');
insert into country values ('PN', 'PITCAIRN');
insert into country values ('PS', 'PALESTINIAN TERRITORY, OCCUPIED');
insert into country values ('PT', 'PORTUGAL');
insert into country values ('PY', 'PARAGUAY');
insert into country values ('QA', 'QATAR');
insert into country values ('RE', 'REUNION');
insert into country values ('RO', 'ROMANIA');
insert into country values ('RU', 'RUSSIAN FEDERATION');
insert into country values ('RW', 'RWANDA');
insert into country values ('SA', 'SAUDI ARABIA');
insert into country values ('SB', 'SOLOMON ISLANDS');
insert into country values ('SC', 'SEYCHELLES');
insert into country values ('SD', 'SUDAN');
insert into country values ('SE', 'SWEDEN');
insert into country values ('SG', 'SINGAPORE');
insert into country values ('SH', 'SAINT HELENA');
insert into country values ('SI', 'SLOVENIA');
insert into country values ('SJ', 'SVALBARD AND JAN MAYEN');
insert into country values ('SK', 'SLOVAKIA');
insert into country values ('SL', 'SIERRA LEONE');
insert into country values ('SM', 'SAN MARINO');
insert into country values ('SN', 'SENEGAL');
insert into country values ('SO', 'SOMALIA');
insert into country values ('SR', 'SURINAME');
insert into country values ('ST', 'SAO TOME AND PRINCIPE');
insert into country values ('SV', 'EL SALVADOR');
insert into country values ('SY', 'SYRIAN ARAB REPUBLIC');
insert into country values ('SZ', 'SWAZILAND');
insert into country values ('TC', 'TURKS AND CAICOS ISLANDS');
insert into country values ('TD', 'CHAD');
insert into country values ('TF', 'FRENCH SOUTHERN TERRITORIES');
insert into country values ('TG', 'TOGO');
insert into country values ('TH', 'THAILAND');
insert into country values ('TJ', 'TAJIKISTAN');
insert into country values ('TK', 'TOKELAU');
insert into country values ('TL', 'TIMOR-LESTE');
insert into country values ('TM', 'TURKMENISTAN');
insert into country values ('TN', 'TUNISIA');
insert into country values ('TO', 'TONGA');
insert into country values ('TR', 'TURKEY');
insert into country values ('TT', 'TRINIDAD AND TOBAGO');
insert into country values ('TV', 'TUVALU');
insert into country values ('TW', 'TAIWAN');
insert into country values ('TZ', 'TANZANIA, UNITED REPUBLIC OF');
insert into country values ('UA', 'UKRAINE');
insert into country values ('UG', 'UGANDA');
insert into country values ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS');
insert into country values ('US', 'UNITED STATES');
insert into country values ('UY', 'URUGUAY');
insert into country values ('UZ', 'UZBEKISTAN');
insert into country values ('VA', 'HOLY SEE (VATICAN CITY STATE)');
insert into country values ('VC', 'SAINT VINCENT AND THE GRENADINES');
insert into country values ('VE', 'VENEZUELA');
insert into country values ('VG', 'VIRGIN ISLANDS, BRITISH');
insert into country values ('VN', 'VIET NAM');
insert into country values ('VU', 'VANUATU');
insert into country values ('WF', 'WALLIS AND FUTUNA');
insert into country values ('WS', 'SAMOA');
insert into country values ('YE', 'YEMEN');
insert into country values ('YT', 'MAYOTTE');
insert into country values ('ZA', 'SOUTH AFRICA');
insert into country values ('ZM', 'ZAMBIA');
insert into country values ('ZW', 'ZIMBABWE');

-- Other Provider Identifier Issuer Codes');
truncate table other_provider_identifier_issuer;
insert into other_provider_identifier_issuer values ('01', 'OTHER');
insert into other_provider_identifier_issuer values ('02', 'MEDICARE UPIN');
insert into other_provider_identifier_issuer values ('04', 'MEDICARE ID-TYPE UNSPECIFIED');
insert into other_provider_identifier_issuer values ('05', 'MEDICAID');
insert into other_provider_identifier_issuer values ('06', 'MEDICARE OSCAR/CERTIFICATION');
insert into other_provider_identifier_issuer values ('07', 'MEDICARE NSC');
insert into other_provider_identifier_issuer values ('08', 'MEDICARE PIN');


-- Taxonomy Codes

-- Primary Taxonomy
truncate table primary_taxonomy;
insert into primary_taxonomy values ('X', 'Not Answered');
insert into primary_taxonomy values ('Y', 'Yes');
insert into primary_taxonomy values ('N', 'No');
