package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudAssignInstrument generated by hbm2java
 */
public class AudAssignInstrument implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal instrumentId;
	private String containerId;
	private BigDecimal checklistId;
	private BigDecimal stepTemplateId;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal checklistRow;
	private String changedBy;
	private Date dateChanged;
	private String changeType;
	private BigDecimal subsidiaryId;
	private BigDecimal assignInstrumentId;

	public AudAssignInstrument() {
	}

	public AudAssignInstrument(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public AudAssignInstrument(BigDecimal auditId, BigDecimal changeReasonId,
			BigDecimal instrumentId, String containerId,
			BigDecimal checklistId, BigDecimal stepTemplateId,
			String createdBy, Date dateCreated, String modifiedBy,
			Date dateModified, BigDecimal checklistRow, String changedBy,
			Date dateChanged, String changeType, BigDecimal subsidiaryId,
			BigDecimal assignInstrumentId) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.instrumentId = instrumentId;
		this.containerId = containerId;
		this.checklistId = checklistId;
		this.stepTemplateId = stepTemplateId;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.checklistRow = checklistRow;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
		this.subsidiaryId = subsidiaryId;
		this.assignInstrumentId = assignInstrumentId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(BigDecimal instrumentId) {
		this.instrumentId = instrumentId;
	}

	public String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(String containerId) {
		this.containerId = containerId;
	}

	public BigDecimal getChecklistId() {
		return this.checklistId;
	}

	public void setChecklistId(BigDecimal checklistId) {
		this.checklistId = checklistId;
	}

	public BigDecimal getStepTemplateId() {
		return this.stepTemplateId;
	}

	public void setStepTemplateId(BigDecimal stepTemplateId) {
		this.stepTemplateId = stepTemplateId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getChecklistRow() {
		return this.checklistRow;
	}

	public void setChecklistRow(BigDecimal checklistRow) {
		this.checklistRow = checklistRow;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getAssignInstrumentId() {
		return this.assignInstrumentId;
	}

	public void setAssignInstrumentId(BigDecimal assignInstrumentId) {
		this.assignInstrumentId = assignInstrumentId;
	}

}
