package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudCpValue generated by hbm2java
 */
public class AudCpValue implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal cpValueId;
	private BigDecimal cpRunId;
	private BigDecimal oligoId;
	private BigDecimal sampleId;
	private BigDecimal parentSampleId;
	private String cpValue;
	private String createdBy;
	private Date dateCreated;
	private String changedBy;
	private Date dateChanged;
	private String changeType;
	private BigDecimal subsidiaryId;

	public AudCpValue() {
	}

	public AudCpValue(BigDecimal auditId, BigDecimal cpRunId,
			BigDecimal oligoId, BigDecimal sampleId, BigDecimal parentSampleId,
			String cpValue, String createdBy, Date dateCreated) {
		this.auditId = auditId;
		this.cpRunId = cpRunId;
		this.oligoId = oligoId;
		this.sampleId = sampleId;
		this.parentSampleId = parentSampleId;
		this.cpValue = cpValue;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public AudCpValue(BigDecimal auditId, BigDecimal changeReasonId,
			BigDecimal cpValueId, BigDecimal cpRunId, BigDecimal oligoId,
			BigDecimal sampleId, BigDecimal parentSampleId, String cpValue,
			String createdBy, Date dateCreated, String changedBy,
			Date dateChanged, String changeType, BigDecimal subsidiaryId) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.cpValueId = cpValueId;
		this.cpRunId = cpRunId;
		this.oligoId = oligoId;
		this.sampleId = sampleId;
		this.parentSampleId = parentSampleId;
		this.cpValue = cpValue;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getCpValueId() {
		return this.cpValueId;
	}

	public void setCpValueId(BigDecimal cpValueId) {
		this.cpValueId = cpValueId;
	}

	public BigDecimal getCpRunId() {
		return this.cpRunId;
	}

	public void setCpRunId(BigDecimal cpRunId) {
		this.cpRunId = cpRunId;
	}

	public BigDecimal getOligoId() {
		return this.oligoId;
	}

	public void setOligoId(BigDecimal oligoId) {
		this.oligoId = oligoId;
	}

	public BigDecimal getSampleId() {
		return this.sampleId;
	}

	public void setSampleId(BigDecimal sampleId) {
		this.sampleId = sampleId;
	}

	public BigDecimal getParentSampleId() {
		return this.parentSampleId;
	}

	public void setParentSampleId(BigDecimal parentSampleId) {
		this.parentSampleId = parentSampleId;
	}

	public String getCpValue() {
		return this.cpValue;
	}

	public void setCpValue(String cpValue) {
		this.cpValue = cpValue;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
