package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AudCaseRoiR generated by hbm2java
 */
public class AudCaseRoiR implements java.io.Serializable {

	private AudCaseRoiRId id;
	private BigDecimal databaseId;

	public AudCaseRoiR() {
	}

	public AudCaseRoiR(AudCaseRoiRId id) {
		this.id = id;
	}

	public AudCaseRoiR(AudCaseRoiRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public AudCaseRoiRId getId() {
		return this.id;
	}

	public void setId(AudCaseRoiRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
