package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudCdxCpRunBatch generated by hbm2java
 */
public class AudCdxCpRunBatch implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal cdxCpRunBatchId;
	private BigDecimal cpRunId;
	private String batch;
	private String changedBy;
	private Date dateChanged;
	private String changeType;

	public AudCdxCpRunBatch() {
	}

	public AudCdxCpRunBatch(BigDecimal auditId, BigDecimal cdxCpRunBatchId,
			BigDecimal cpRunId, String batch) {
		this.auditId = auditId;
		this.cdxCpRunBatchId = cdxCpRunBatchId;
		this.cpRunId = cpRunId;
		this.batch = batch;
	}

	public AudCdxCpRunBatch(BigDecimal auditId, BigDecimal changeReasonId,
			BigDecimal cdxCpRunBatchId, BigDecimal cpRunId, String batch,
			String changedBy, Date dateChanged, String changeType) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.cdxCpRunBatchId = cdxCpRunBatchId;
		this.cpRunId = cpRunId;
		this.batch = batch;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getCdxCpRunBatchId() {
		return this.cdxCpRunBatchId;
	}

	public void setCdxCpRunBatchId(BigDecimal cdxCpRunBatchId) {
		this.cdxCpRunBatchId = cdxCpRunBatchId;
	}

	public BigDecimal getCpRunId() {
		return this.cpRunId;
	}

	public void setCpRunId(BigDecimal cpRunId) {
		this.cpRunId = cpRunId;
	}

	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

}
