package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudGeneInterpretation generated by hbm2java
 */
public class AudGeneInterpretation implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal geneInterprDefinitionId;
	private BigDecimal geneId;
	private BigDecimal numberInSequence;
	private String changedBy;
	private Date dateChanged;
	private String changeType;

	public AudGeneInterpretation() {
	}

	public AudGeneInterpretation(BigDecimal auditId,
			BigDecimal geneInterprDefinitionId, BigDecimal geneId) {
		this.auditId = auditId;
		this.geneInterprDefinitionId = geneInterprDefinitionId;
		this.geneId = geneId;
	}

	public AudGeneInterpretation(BigDecimal auditId, BigDecimal changeReasonId,
			BigDecimal geneInterprDefinitionId, BigDecimal geneId,
			BigDecimal numberInSequence, String changedBy, Date dateChanged,
			String changeType) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.geneInterprDefinitionId = geneInterprDefinitionId;
		this.geneId = geneId;
		this.numberInSequence = numberInSequence;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getGeneInterprDefinitionId() {
		return this.geneInterprDefinitionId;
	}

	public void setGeneInterprDefinitionId(BigDecimal geneInterprDefinitionId) {
		this.geneInterprDefinitionId = geneInterprDefinitionId;
	}

	public BigDecimal getGeneId() {
		return this.geneId;
	}

	public void setGeneId(BigDecimal geneId) {
		this.geneId = geneId;
	}

	public BigDecimal getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(BigDecimal numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

}
