package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudInstrument generated by hbm2java
 */
public class AudInstrument implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal instrumentId;
	private BigDecimal testingFacilityId;
	private BigDecimal organizationId;
	private String instrumentNumber;
	private String status;
	private String type;
	private String objectClass;
	private String instrumentDescription;
	private String checkoutBy;
	private Date dateCheckout;
	private Date dateScheduled;
	private BigDecimal isStorage;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private String changedBy;
	private Date dateChanged;
	private String changeType;
	private BigDecimal subsidiaryId;

	public AudInstrument() {
	}

	public AudInstrument(BigDecimal auditId, BigDecimal instrumentId) {
		this.auditId = auditId;
		this.instrumentId = instrumentId;
	}

	public AudInstrument(BigDecimal auditId, BigDecimal changeReasonId,
			BigDecimal instrumentId, BigDecimal testingFacilityId,
			BigDecimal organizationId, String instrumentNumber, String status,
			String type, String objectClass, String instrumentDescription,
			String checkoutBy, Date dateCheckout, Date dateScheduled,
			BigDecimal isStorage, String createdBy, Date dateCreated,
			String modifiedBy, Date dateModified, String changedBy,
			Date dateChanged, String changeType, BigDecimal subsidiaryId) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.instrumentId = instrumentId;
		this.testingFacilityId = testingFacilityId;
		this.organizationId = organizationId;
		this.instrumentNumber = instrumentNumber;
		this.status = status;
		this.type = type;
		this.objectClass = objectClass;
		this.instrumentDescription = instrumentDescription;
		this.checkoutBy = checkoutBy;
		this.dateCheckout = dateCheckout;
		this.dateScheduled = dateScheduled;
		this.isStorage = isStorage;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(BigDecimal instrumentId) {
		this.instrumentId = instrumentId;
	}

	public BigDecimal getTestingFacilityId() {
		return this.testingFacilityId;
	}

	public void setTestingFacilityId(BigDecimal testingFacilityId) {
		this.testingFacilityId = testingFacilityId;
	}

	public BigDecimal getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(BigDecimal organizationId) {
		this.organizationId = organizationId;
	}

	public String getInstrumentNumber() {
		return this.instrumentNumber;
	}

	public void setInstrumentNumber(String instrumentNumber) {
		this.instrumentNumber = instrumentNumber;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getObjectClass() {
		return this.objectClass;
	}

	public void setObjectClass(String objectClass) {
		this.objectClass = objectClass;
	}

	public String getInstrumentDescription() {
		return this.instrumentDescription;
	}

	public void setInstrumentDescription(String instrumentDescription) {
		this.instrumentDescription = instrumentDescription;
	}

	public String getCheckoutBy() {
		return this.checkoutBy;
	}

	public void setCheckoutBy(String checkoutBy) {
		this.checkoutBy = checkoutBy;
	}

	public Date getDateCheckout() {
		return this.dateCheckout;
	}

	public void setDateCheckout(Date dateCheckout) {
		this.dateCheckout = dateCheckout;
	}

	public Date getDateScheduled() {
		return this.dateScheduled;
	}

	public void setDateScheduled(Date dateScheduled) {
		this.dateScheduled = dateScheduled;
	}

	public BigDecimal getIsStorage() {
		return this.isStorage;
	}

	public void setIsStorage(BigDecimal isStorage) {
		this.isStorage = isStorage;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
