package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudInstrumentSetup generated by hbm2java
 */
public class AudInstrumentSetup implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal instrumentSetupId;
	private BigDecimal instrumentId;
	private BigDecimal duration;
	private String username;
	private BigDecimal notificationLeadTime;
	private BigDecimal maintenanceGap;
	private String createdBy;
	private Date dateCreated;
	private String changedBy;
	private Date dateChanged;
	private String changeType;
	private BigDecimal subsidiaryId;

	public AudInstrumentSetup() {
	}

	public AudInstrumentSetup(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public AudInstrumentSetup(BigDecimal auditId, BigDecimal changeReasonId,
			BigDecimal instrumentSetupId, BigDecimal instrumentId,
			BigDecimal duration, String username,
			BigDecimal notificationLeadTime, BigDecimal maintenanceGap,
			String createdBy, Date dateCreated, String changedBy,
			Date dateChanged, String changeType, BigDecimal subsidiaryId) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.instrumentSetupId = instrumentSetupId;
		this.instrumentId = instrumentId;
		this.duration = duration;
		this.username = username;
		this.notificationLeadTime = notificationLeadTime;
		this.maintenanceGap = maintenanceGap;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getInstrumentSetupId() {
		return this.instrumentSetupId;
	}

	public void setInstrumentSetupId(BigDecimal instrumentSetupId) {
		this.instrumentSetupId = instrumentSetupId;
	}

	public BigDecimal getInstrumentId() {
		return this.instrumentId;
	}

	public void setInstrumentId(BigDecimal instrumentId) {
		this.instrumentId = instrumentId;
	}

	public BigDecimal getDuration() {
		return this.duration;
	}

	public void setDuration(BigDecimal duration) {
		this.duration = duration;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public BigDecimal getNotificationLeadTime() {
		return this.notificationLeadTime;
	}

	public void setNotificationLeadTime(BigDecimal notificationLeadTime) {
		this.notificationLeadTime = notificationLeadTime;
	}

	public BigDecimal getMaintenanceGap() {
		return this.maintenanceGap;
	}

	public void setMaintenanceGap(BigDecimal maintenanceGap) {
		this.maintenanceGap = maintenanceGap;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
