package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudIdentifiedSample generated by hbm2java
 */
public class AudIdentifiedSample implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal identifiedSampleId;
	private String sponsorSampleTubeId;
	private String sponsorAccessionId;
	private boolean pending;
	private String sourceType;
	private String createdBy;
	private Date dateCreated;
	private String accessionedBy;
	private Date dateAccessioned;
	private String changedBy;
	private Date dateChanged;
	private String changeType;
	private BigDecimal changeReasonId;
	private BigDecimal subsidiaryId;

	public AudIdentifiedSample() {
	}

	public AudIdentifiedSample(BigDecimal auditId,
			BigDecimal identifiedSampleId, boolean pending, String createdBy,
			Date dateCreated) {
		this.auditId = auditId;
		this.identifiedSampleId = identifiedSampleId;
		this.pending = pending;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public AudIdentifiedSample(BigDecimal auditId,
			BigDecimal identifiedSampleId, String sponsorSampleTubeId,
			String sponsorAccessionId, boolean pending, String sourceType,
			String createdBy, Date dateCreated, String accessionedBy,
			Date dateAccessioned, String changedBy, Date dateChanged,
			String changeType, BigDecimal changeReasonId,
			BigDecimal subsidiaryId) {
		this.auditId = auditId;
		this.identifiedSampleId = identifiedSampleId;
		this.sponsorSampleTubeId = sponsorSampleTubeId;
		this.sponsorAccessionId = sponsorAccessionId;
		this.pending = pending;
		this.sourceType = sourceType;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.accessionedBy = accessionedBy;
		this.dateAccessioned = dateAccessioned;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
		this.changeReasonId = changeReasonId;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getIdentifiedSampleId() {
		return this.identifiedSampleId;
	}

	public void setIdentifiedSampleId(BigDecimal identifiedSampleId) {
		this.identifiedSampleId = identifiedSampleId;
	}

	public String getSponsorSampleTubeId() {
		return this.sponsorSampleTubeId;
	}

	public void setSponsorSampleTubeId(String sponsorSampleTubeId) {
		this.sponsorSampleTubeId = sponsorSampleTubeId;
	}

	public String getSponsorAccessionId() {
		return this.sponsorAccessionId;
	}

	public void setSponsorAccessionId(String sponsorAccessionId) {
		this.sponsorAccessionId = sponsorAccessionId;
	}

	public boolean isPending() {
		return this.pending;
	}

	public void setPending(boolean pending) {
		this.pending = pending;
	}

	public String getSourceType() {
		return this.sourceType;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getAccessionedBy() {
		return this.accessionedBy;
	}

	public void setAccessionedBy(String accessionedBy) {
		this.accessionedBy = accessionedBy;
	}

	public Date getDateAccessioned() {
		return this.dateAccessioned;
	}

	public void setDateAccessioned(Date dateAccessioned) {
		this.dateAccessioned = dateAccessioned;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
