package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudProtocolAlleleValue generated by hbm2java
 */
public class AudProtocolAlleleValue implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal protocolAlleleId;
	private BigDecimal numberInSequence;
	private String result;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal studyProtocolId;
	private String changedBy;
	private Date dateChanged;
	private String changeType;
	private BigDecimal subsidiaryId;

	public AudProtocolAlleleValue() {
	}

	public AudProtocolAlleleValue(BigDecimal auditId,
			BigDecimal protocolAlleleId, BigDecimal numberInSequence,
			BigDecimal studyProtocolId) {
		this.auditId = auditId;
		this.protocolAlleleId = protocolAlleleId;
		this.numberInSequence = numberInSequence;
		this.studyProtocolId = studyProtocolId;
	}

	public AudProtocolAlleleValue(BigDecimal auditId,
			BigDecimal changeReasonId, BigDecimal protocolAlleleId,
			BigDecimal numberInSequence, String result, String modifiedBy,
			Date dateModified, BigDecimal studyProtocolId, String changedBy,
			Date dateChanged, String changeType, BigDecimal subsidiaryId) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.protocolAlleleId = protocolAlleleId;
		this.numberInSequence = numberInSequence;
		this.result = result;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.studyProtocolId = studyProtocolId;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getProtocolAlleleId() {
		return this.protocolAlleleId;
	}

	public void setProtocolAlleleId(BigDecimal protocolAlleleId) {
		this.protocolAlleleId = protocolAlleleId;
	}

	public BigDecimal getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(BigDecimal numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getStudyProtocolId() {
		return this.studyProtocolId;
	}

	public void setStudyProtocolId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
