package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AudShipmentPackageR generated by hbm2java
 */
public class AudShipmentPackageR implements java.io.Serializable {

	private AudShipmentPackageRId id;
	private BigDecimal databaseId;

	public AudShipmentPackageR() {
	}

	public AudShipmentPackageR(AudShipmentPackageRId id) {
		this.id = id;
	}

	public AudShipmentPackageR(AudShipmentPackageRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public AudShipmentPackageRId getId() {
		return this.id;
	}

	public void setId(AudShipmentPackageRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
