package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudStudyProtocol generated by hbm2java
 */
public class AudStudyProtocol implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal studyProtocolId;
	private String studyNumber;
	private String sponsorStudyNumber;
	private String studyTitle;
	private String studyDirector;
	private String sponsorStudyTitle;
	private BigDecimal contactId;
	private Boolean cascadeAccessionNumber;
	private BigDecimal barcodeLength;
	private String finalTubeBarcodeLowValue;
	private String finalTubeBarcodeHighValue;
	private Boolean studyClosed;
	private Boolean shipDnaBack;
	private BigDecimal accessionVarOcx;
	private BigDecimal studyVarOcx;
	private BigDecimal patientVarOcx;
	private String studyUrl;
	private BigDecimal organizationId;
	private String company;
	private String studyType;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private String changedBy;
	private Date dateChanged;
	private String changeType;
	private BigDecimal subsidiaryId;

	public AudStudyProtocol() {
	}

	public AudStudyProtocol(BigDecimal auditId, BigDecimal studyProtocolId,
			String studyDirector) {
		this.auditId = auditId;
		this.studyProtocolId = studyProtocolId;
		this.studyDirector = studyDirector;
	}

	public AudStudyProtocol(BigDecimal auditId, BigDecimal changeReasonId,
			BigDecimal studyProtocolId, String studyNumber,
			String sponsorStudyNumber, String studyTitle, String studyDirector,
			String sponsorStudyTitle, BigDecimal contactId,
			Boolean cascadeAccessionNumber, BigDecimal barcodeLength,
			String finalTubeBarcodeLowValue, String finalTubeBarcodeHighValue,
			Boolean studyClosed, Boolean shipDnaBack,
			BigDecimal accessionVarOcx, BigDecimal studyVarOcx,
			BigDecimal patientVarOcx, String studyUrl,
			BigDecimal organizationId, String company, String studyType,
			String createdBy, Date dateCreated, String modifiedBy,
			Date dateModified, String changedBy, Date dateChanged,
			String changeType, BigDecimal subsidiaryId) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.studyProtocolId = studyProtocolId;
		this.studyNumber = studyNumber;
		this.sponsorStudyNumber = sponsorStudyNumber;
		this.studyTitle = studyTitle;
		this.studyDirector = studyDirector;
		this.sponsorStudyTitle = sponsorStudyTitle;
		this.contactId = contactId;
		this.cascadeAccessionNumber = cascadeAccessionNumber;
		this.barcodeLength = barcodeLength;
		this.finalTubeBarcodeLowValue = finalTubeBarcodeLowValue;
		this.finalTubeBarcodeHighValue = finalTubeBarcodeHighValue;
		this.studyClosed = studyClosed;
		this.shipDnaBack = shipDnaBack;
		this.accessionVarOcx = accessionVarOcx;
		this.studyVarOcx = studyVarOcx;
		this.patientVarOcx = patientVarOcx;
		this.studyUrl = studyUrl;
		this.organizationId = organizationId;
		this.company = company;
		this.studyType = studyType;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getStudyProtocolId() {
		return this.studyProtocolId;
	}

	public void setStudyProtocolId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public String getStudyNumber() {
		return this.studyNumber;
	}

	public void setStudyNumber(String studyNumber) {
		this.studyNumber = studyNumber;
	}

	public String getSponsorStudyNumber() {
		return this.sponsorStudyNumber;
	}

	public void setSponsorStudyNumber(String sponsorStudyNumber) {
		this.sponsorStudyNumber = sponsorStudyNumber;
	}

	public String getStudyTitle() {
		return this.studyTitle;
	}

	public void setStudyTitle(String studyTitle) {
		this.studyTitle = studyTitle;
	}

	public String getStudyDirector() {
		return this.studyDirector;
	}

	public void setStudyDirector(String studyDirector) {
		this.studyDirector = studyDirector;
	}

	public String getSponsorStudyTitle() {
		return this.sponsorStudyTitle;
	}

	public void setSponsorStudyTitle(String sponsorStudyTitle) {
		this.sponsorStudyTitle = sponsorStudyTitle;
	}

	public BigDecimal getContactId() {
		return this.contactId;
	}

	public void setContactId(BigDecimal contactId) {
		this.contactId = contactId;
	}

	public Boolean getCascadeAccessionNumber() {
		return this.cascadeAccessionNumber;
	}

	public void setCascadeAccessionNumber(Boolean cascadeAccessionNumber) {
		this.cascadeAccessionNumber = cascadeAccessionNumber;
	}

	public BigDecimal getBarcodeLength() {
		return this.barcodeLength;
	}

	public void setBarcodeLength(BigDecimal barcodeLength) {
		this.barcodeLength = barcodeLength;
	}

	public String getFinalTubeBarcodeLowValue() {
		return this.finalTubeBarcodeLowValue;
	}

	public void setFinalTubeBarcodeLowValue(String finalTubeBarcodeLowValue) {
		this.finalTubeBarcodeLowValue = finalTubeBarcodeLowValue;
	}

	public String getFinalTubeBarcodeHighValue() {
		return this.finalTubeBarcodeHighValue;
	}

	public void setFinalTubeBarcodeHighValue(String finalTubeBarcodeHighValue) {
		this.finalTubeBarcodeHighValue = finalTubeBarcodeHighValue;
	}

	public Boolean getStudyClosed() {
		return this.studyClosed;
	}

	public void setStudyClosed(Boolean studyClosed) {
		this.studyClosed = studyClosed;
	}

	public Boolean getShipDnaBack() {
		return this.shipDnaBack;
	}

	public void setShipDnaBack(Boolean shipDnaBack) {
		this.shipDnaBack = shipDnaBack;
	}

	public BigDecimal getAccessionVarOcx() {
		return this.accessionVarOcx;
	}

	public void setAccessionVarOcx(BigDecimal accessionVarOcx) {
		this.accessionVarOcx = accessionVarOcx;
	}

	public BigDecimal getStudyVarOcx() {
		return this.studyVarOcx;
	}

	public void setStudyVarOcx(BigDecimal studyVarOcx) {
		this.studyVarOcx = studyVarOcx;
	}

	public BigDecimal getPatientVarOcx() {
		return this.patientVarOcx;
	}

	public void setPatientVarOcx(BigDecimal patientVarOcx) {
		this.patientVarOcx = patientVarOcx;
	}

	public String getStudyUrl() {
		return this.studyUrl;
	}

	public void setStudyUrl(String studyUrl) {
		this.studyUrl = studyUrl;
	}

	public BigDecimal getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(BigDecimal organizationId) {
		this.organizationId = organizationId;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getStudyType() {
		return this.studyType;
	}

	public void setStudyType(String studyType) {
		this.studyType = studyType;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
