package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudSpecimenRequest generated by hbm2java
 */
public class AudSpecimenRequest implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal specimenRequestId;
	private String requestId;
	private String requestor;
	private Date requestDate;
	private Date dueDate;
	private String status;
	private String referenceRequestNumber;
	private String otherPurpose;
	private BigDecimal subsidiaryId;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal changeReasonId;
	private String changeType;
	private String changedBy;
	private Date dateChanged;

	public AudSpecimenRequest() {
	}

	public AudSpecimenRequest(BigDecimal auditId, BigDecimal specimenRequestId,
			String requestId, String requestor, Date requestDate, Date dueDate,
			String status, String createdBy, Date dateCreated) {
		this.auditId = auditId;
		this.specimenRequestId = specimenRequestId;
		this.requestId = requestId;
		this.requestor = requestor;
		this.requestDate = requestDate;
		this.dueDate = dueDate;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public AudSpecimenRequest(BigDecimal auditId, BigDecimal specimenRequestId,
			String requestId, String requestor, Date requestDate, Date dueDate,
			String status, String referenceRequestNumber, String otherPurpose,
			BigDecimal subsidiaryId, String createdBy, Date dateCreated,
			String modifiedBy, Date dateModified, BigDecimal changeReasonId,
			String changeType, String changedBy, Date dateChanged) {
		this.auditId = auditId;
		this.specimenRequestId = specimenRequestId;
		this.requestId = requestId;
		this.requestor = requestor;
		this.requestDate = requestDate;
		this.dueDate = dueDate;
		this.status = status;
		this.referenceRequestNumber = referenceRequestNumber;
		this.otherPurpose = otherPurpose;
		this.subsidiaryId = subsidiaryId;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.changeReasonId = changeReasonId;
		this.changeType = changeType;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getSpecimenRequestId() {
		return this.specimenRequestId;
	}

	public void setSpecimenRequestId(BigDecimal specimenRequestId) {
		this.specimenRequestId = specimenRequestId;
	}

	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public String getRequestor() {
		return this.requestor;
	}

	public void setRequestor(String requestor) {
		this.requestor = requestor;
	}

	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReferenceRequestNumber() {
		return this.referenceRequestNumber;
	}

	public void setReferenceRequestNumber(String referenceRequestNumber) {
		this.referenceRequestNumber = referenceRequestNumber;
	}

	public String getOtherPurpose() {
		return this.otherPurpose;
	}

	public void setOtherPurpose(String otherPurpose) {
		this.otherPurpose = otherPurpose;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

}
