package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AudSpecimenShipmentR generated by hbm2java
 */
public class AudSpecimenShipmentR implements java.io.Serializable {

	private AudSpecimenShipmentRId id;
	private BigDecimal databaseId;

	public AudSpecimenShipmentR() {
	}

	public AudSpecimenShipmentR(AudSpecimenShipmentRId id) {
		this.id = id;
	}

	public AudSpecimenShipmentR(AudSpecimenShipmentRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public AudSpecimenShipmentRId getId() {
		return this.id;
	}

	public void setId(AudSpecimenShipmentRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
