package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudSpecimenShipmentAirbill generated by hbm2java
 */
public class AudSpecimenShipmentAirbill implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal shipmentAirbillId;
	private String airbillNumber;
	private BigDecimal shipmentId;
	private BigDecimal courierOrgId;
	private Date courierDate;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private String changedBy;
	private Date dateChanged;
	private String changeType;
	private BigDecimal subsidiaryId;

	public AudSpecimenShipmentAirbill() {
	}

	public AudSpecimenShipmentAirbill(BigDecimal auditId,
			BigDecimal shipmentAirbillId) {
		this.auditId = auditId;
		this.shipmentAirbillId = shipmentAirbillId;
	}

	public AudSpecimenShipmentAirbill(BigDecimal auditId,
			BigDecimal changeReasonId, BigDecimal shipmentAirbillId,
			String airbillNumber, BigDecimal shipmentId,
			BigDecimal courierOrgId, Date courierDate, String createdBy,
			Date dateCreated, String modifiedBy, Date dateModified,
			String changedBy, Date dateChanged, String changeType,
			BigDecimal subsidiaryId) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.shipmentAirbillId = shipmentAirbillId;
		this.airbillNumber = airbillNumber;
		this.shipmentId = shipmentId;
		this.courierOrgId = courierOrgId;
		this.courierDate = courierDate;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getShipmentAirbillId() {
		return this.shipmentAirbillId;
	}

	public void setShipmentAirbillId(BigDecimal shipmentAirbillId) {
		this.shipmentAirbillId = shipmentAirbillId;
	}

	public String getAirbillNumber() {
		return this.airbillNumber;
	}

	public void setAirbillNumber(String airbillNumber) {
		this.airbillNumber = airbillNumber;
	}

	public BigDecimal getShipmentId() {
		return this.shipmentId;
	}

	public void setShipmentId(BigDecimal shipmentId) {
		this.shipmentId = shipmentId;
	}

	public BigDecimal getCourierOrgId() {
		return this.courierOrgId;
	}

	public void setCourierOrgId(BigDecimal courierOrgId) {
		this.courierOrgId = courierOrgId;
	}

	public Date getCourierDate() {
		return this.courierDate;
	}

	public void setCourierDate(Date courierDate) {
		this.courierDate = courierDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
