package com.cardiodx.db.waban.audit;

// Generated Jul 14, 2011 1:32:59 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AudVendorResultMap generated by hbm2java
 */
public class AudVendorResultMap implements java.io.Serializable {

	private BigDecimal auditId;
	private BigDecimal changeReasonId;
	private BigDecimal vendorResultMapId;
	private BigDecimal vendorAssayMapId;
	private String systemResultValue;
	private String vendorResultValue;
	private String changedBy;
	private Date dateChanged;
	private String changeType;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal subsidiaryId;

	public AudVendorResultMap() {
	}

	public AudVendorResultMap(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public AudVendorResultMap(BigDecimal auditId, BigDecimal changeReasonId,
			BigDecimal vendorResultMapId, BigDecimal vendorAssayMapId,
			String systemResultValue, String vendorResultValue,
			String changedBy, Date dateChanged, String changeType,
			String createdBy, Date dateCreated, String modifiedBy,
			Date dateModified, BigDecimal subsidiaryId) {
		this.auditId = auditId;
		this.changeReasonId = changeReasonId;
		this.vendorResultMapId = vendorResultMapId;
		this.vendorAssayMapId = vendorAssayMapId;
		this.systemResultValue = systemResultValue;
		this.vendorResultValue = vendorResultValue;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
		this.changeType = changeType;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public BigDecimal getChangeReasonId() {
		return this.changeReasonId;
	}

	public void setChangeReasonId(BigDecimal changeReasonId) {
		this.changeReasonId = changeReasonId;
	}

	public BigDecimal getVendorResultMapId() {
		return this.vendorResultMapId;
	}

	public void setVendorResultMapId(BigDecimal vendorResultMapId) {
		this.vendorResultMapId = vendorResultMapId;
	}

	public BigDecimal getVendorAssayMapId() {
		return this.vendorAssayMapId;
	}

	public void setVendorAssayMapId(BigDecimal vendorAssayMapId) {
		this.vendorAssayMapId = vendorAssayMapId;
	}

	public String getSystemResultValue() {
		return this.systemResultValue;
	}

	public void setSystemResultValue(String systemResultValue) {
		this.systemResultValue = systemResultValue;
	}

	public String getVendorResultValue() {
		return this.vendorResultValue;
	}

	public void setVendorResultValue(String vendorResultValue) {
		this.vendorResultValue = vendorResultValue;
	}

	public String getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return this.dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public String getChangeType() {
		return this.changeType;
	}

	public void setChangeType(String changeType) {
		this.changeType = changeType;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
