create unique index cms6060n_NPI on cms6060n(NPI);

create index cms6060n_Entity_Type_Code on cms6060n(Entity_Type_Code);
create index cms6060n_Is_Organization_Subpart on cms6060n(Is_Organization_Subpart);
create index cms6060n_Provider_Gender_Code on cms6060n(Provider_Gender_Code);
create index cms6060n_NPI_Deactivation_Reason_Code on cms6060n(NPI_Deactivation_Reason_Code);
create index cms6060n_Provider_Other_Organization_Name_Type_Code on cms6060n(Provider_Other_Organization_Name_Type_Code);
create index cms6060n_Provider_Name_Prefix_Text on cms6060n(Provider_Name_Prefix_Text);
create index cms6060n_Provider_Other_Name_Prefix_Text on cms6060n(Provider_Other_Name_Prefix_Text);
create index cms6060n_Provider_Name_Suffix_Text on cms6060n(Provider_Name_Suffix_Text);
create index cms6060n_Provider_Other_Name_Suffix_Text on cms6060n(Provider_Other_Name_Suffix_Text);
create index cms6060n_Provider_Business_Mailing_Address_State_Name on cms6060n(Provider_Business_Mailing_Address_State_Name);
create index cms6060n_Provider_Business_Practice_Location_Address_State_Name on cms6060n(Provider_Business_Practice_Location_Address_State_Name);

create index cms6060n_Provider_License_Number_State_Code_1 on cms6060n(Provider_License_Number_State_Code_1);
create index cms6060n_Provider_License_Number_State_Code_2 on cms6060n(Provider_License_Number_State_Code_2);
create index cms6060n_Provider_License_Number_State_Code_3 on cms6060n(Provider_License_Number_State_Code_3);
create index cms6060n_Provider_License_Number_State_Code_4 on cms6060n(Provider_License_Number_State_Code_4);
create index cms6060n_Provider_License_Number_State_Code_5 on cms6060n(Provider_License_Number_State_Code_5);
create index cms6060n_Provider_License_Number_State_Code_6 on cms6060n(Provider_License_Number_State_Code_6);
create index cms6060n_Provider_License_Number_State_Code_7 on cms6060n(Provider_License_Number_State_Code_7);
create index cms6060n_Provider_License_Number_State_Code_8 on cms6060n(Provider_License_Number_State_Code_8);
create index cms6060n_Provider_License_Number_State_Code_9 on cms6060n(Provider_License_Number_State_Code_9);
create index cms6060n_Provider_License_Number_State_Code_10 on cms6060n(Provider_License_Number_State_Code_10);
create index cms6060n_Provider_License_Number_State_Code_11 on cms6060n(Provider_License_Number_State_Code_11);
create index cms6060n_Provider_License_Number_State_Code_12 on cms6060n(Provider_License_Number_State_Code_12);
create index cms6060n_Provider_License_Number_State_Code_13 on cms6060n(Provider_License_Number_State_Code_13);
create index cms6060n_Provider_License_Number_State_Code_14 on cms6060n(Provider_License_Number_State_Code_14);
create index cms6060n_Provider_License_Number_State_Code_15 on cms6060n(Provider_License_Number_State_Code_15);

create index cms6060n_Other_Provider_Identifier_State_1 on cms6060n(Other_Provider_Identifier_State_1);
create index cms6060n_Other_Provider_Identifier_State_2 on cms6060n(Other_Provider_Identifier_State_2);
create index cms6060n_Other_Provider_Identifier_State_3 on cms6060n(Other_Provider_Identifier_State_3);
create index cms6060n_Other_Provider_Identifier_State_4 on cms6060n(Other_Provider_Identifier_State_4);
create index cms6060n_Other_Provider_Identifier_State_5 on cms6060n(Other_Provider_Identifier_State_5);
create index cms6060n_Other_Provider_Identifier_State_6 on cms6060n(Other_Provider_Identifier_State_6);
create index cms6060n_Other_Provider_Identifier_State_7 on cms6060n(Other_Provider_Identifier_State_7);
create index cms6060n_Other_Provider_Identifier_State_8 on cms6060n(Other_Provider_Identifier_State_8);
create index cms6060n_Other_Provider_Identifier_State_9 on cms6060n(Other_Provider_Identifier_State_9);
create index cms6060n_Other_Provider_Identifier_State_10 on cms6060n(Other_Provider_Identifier_State_10);
create index cms6060n_Provider_Business_Mailing_Address_Country_outside_US on cms6060n(Provider_Business_Mailing_Address_Country_outside_US);
create index cms6060n_Provider_Business_Practice_Location_Address_Country_outside_US on cms6060n(Provider_Business_Practice_Location_Address_Country_outside_US);

create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_1 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_1);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_2 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_2);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_3 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_3);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_4 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_4);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_5 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_5);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_6 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_6);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_7 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_7);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_8 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_8);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_9 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_9);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_10 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_10);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_11 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_11);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_12 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_12);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_13 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_13);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_14 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_14);
create index cms6060n_Healthcare_Provider_Primary_Taxonomy_Switch_15 on cms6060n(Healthcare_Provider_Primary_Taxonomy_Switch_15);

create index cms6060n_Healthcare_Provider_Taxonomy_Code_1 on cms6060n(Healthcare_Provider_Taxonomy_Code_1);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_2 on cms6060n(Healthcare_Provider_Taxonomy_Code_2);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_3 on cms6060n(Healthcare_Provider_Taxonomy_Code_3);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_4 on cms6060n(Healthcare_Provider_Taxonomy_Code_4);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_5 on cms6060n(Healthcare_Provider_Taxonomy_Code_5);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_6 on cms6060n(Healthcare_Provider_Taxonomy_Code_6);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_7 on cms6060n(Healthcare_Provider_Taxonomy_Code_7);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_8 on cms6060n(Healthcare_Provider_Taxonomy_Code_8);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_9 on cms6060n(Healthcare_Provider_Taxonomy_Code_9);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_10 on cms6060n(Healthcare_Provider_Taxonomy_Code_10);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_11 on cms6060n(Healthcare_Provider_Taxonomy_Code_11);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_12 on cms6060n(Healthcare_Provider_Taxonomy_Code_12);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_13 on cms6060n(Healthcare_Provider_Taxonomy_Code_13);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_14 on cms6060n(Healthcare_Provider_Taxonomy_Code_14);
create index cms6060n_Healthcare_Provider_Taxonomy_Code_15 on cms6060n(Healthcare_Provider_Taxonomy_Code_15);


create index cms6060n_Provider_Business_Practice_Location_Address_State_Name on cms6060n(Provider_Business_Practice_Location_Address_State_Name);

create index cms6060n_lat_lng on cms6060n(lat, lng);
create index cms6060n_Current_Healthcare_Provider_Taxonomy_Code on cms6060n(Current_Healthcare_Provider_Taxonomy_Code);





