package com.demo.demo.model.dao.demo.impl;

import java.io.Serializable;
import com.demo.persistence.impl.GenericHibernateDaoImpl;
import com.demo.demo.model.obj.demo.Stock;
import org.springframework.stereotype.Repository;
import com.demo.demo.model.dao.demo.StockDao;

/**
 * DAO for table: Stock.
 * @author autogenerated
 */
@Repository
public class StockDaoImpl extends GenericHibernateDaoImpl<Stock, Serializable> implements StockDao {
	
	/** Constructor method. */
		public StockDaoImpl() {
			super(Stock.class);
		}
	}

