package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AccessionR generated by hbm2java
 */
public class AccessionR implements java.io.Serializable {

	private AccessionRId id;
	private BigDecimal databaseId;

	public AccessionR() {
	}

	public AccessionR(AccessionRId id) {
		this.id = id;
	}

	public AccessionR(AccessionRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public AccessionRId getId() {
		return this.id;
	}

	public void setId(AccessionRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
