package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AlleleR generated by hbm2java
 */
public class AlleleR implements java.io.Serializable {

	private AlleleRId id;
	private BigDecimal databaseId;

	public AlleleR() {
	}

	public AlleleR(AlleleRId id) {
		this.id = id;
	}

	public AlleleR(AlleleRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public AlleleRId getId() {
		return this.id;
	}

	public void setId(AlleleRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
