package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AnonymizedLabAccessionNo generated by hbm2java
 */
public class AnonymizedLabAccessionNo implements java.io.Serializable {

	private BigDecimal anonymizedLabAccessionNo;
	private Accession accession;

	public AnonymizedLabAccessionNo() {
	}

	public AnonymizedLabAccessionNo(BigDecimal anonymizedLabAccessionNo) {
		this.anonymizedLabAccessionNo = anonymizedLabAccessionNo;
	}

	public AnonymizedLabAccessionNo(BigDecimal anonymizedLabAccessionNo,
			Accession accession) {
		this.anonymizedLabAccessionNo = anonymizedLabAccessionNo;
		this.accession = accession;
	}

	public BigDecimal getAnonymizedLabAccessionNo() {
		return this.anonymizedLabAccessionNo;
	}

	public void setAnonymizedLabAccessionNo(BigDecimal anonymizedLabAccessionNo) {
		this.anonymizedLabAccessionNo = anonymizedLabAccessionNo;
	}

	public Accession getAccession() {
		return this.accession;
	}

	public void setAccession(Accession accession) {
		this.accession = accession;
	}

}
