package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AnonymizationRequestR generated by hbm2java
 */
public class AnonymizationRequestR implements java.io.Serializable {

	private AnonymizationRequestRId id;
	private BigDecimal databaseId;

	public AnonymizationRequestR() {
	}

	public AnonymizationRequestR(AnonymizationRequestRId id) {
		this.id = id;
	}

	public AnonymizationRequestR(AnonymizationRequestRId id,
			BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public AnonymizationRequestRId getId() {
		return this.id;
	}

	public void setId(AnonymizationRequestRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
