package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * AssignInstrumentR generated by hbm2java
 */
public class AssignInstrumentR implements java.io.Serializable {

	private AssignInstrumentRId id;
	private BigDecimal databaseId;

	public AssignInstrumentR() {
	}

	public AssignInstrumentR(AssignInstrumentRId id) {
		this.id = id;
	}

	public AssignInstrumentR(AssignInstrumentRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public AssignInstrumentRId getId() {
		return this.id;
	}

	public void setId(AssignInstrumentRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
