package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * AutocallGenotype generated by hbm2java
 */
public class AutocallGenotype implements java.io.Serializable {

	private AutocallGenotypeId id;
	private Subsidiary subsidiary;

	public AutocallGenotype() {
	}

	public AutocallGenotype(AutocallGenotypeId id) {
		this.id = id;
	}

	public AutocallGenotype(AutocallGenotypeId id, Subsidiary subsidiary) {
		this.id = id;
		this.subsidiary = subsidiary;
	}

	public AutocallGenotypeId getId() {
		return this.id;
	}

	public void setId(AutocallGenotypeId id) {
		this.id = id;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

}
