package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CaseRoi generated by hbm2java
 */
public class CaseRoi implements java.io.Serializable {

	private BigDecimal caseRoiId;
	private RoiSelection roiSelection;
	private Roi roi;
	private TestAccession testAccession;
	private Subsidiary subsidiary;
	private String caseId;
	private String status;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private Set<PcrSetupPlaceRoi> pcrSetupPlaceRois = new HashSet<PcrSetupPlaceRoi>(
			0);

	public CaseRoi() {
	}

	public CaseRoi(BigDecimal caseRoiId, TestAccession testAccession) {
		this.caseRoiId = caseRoiId;
		this.testAccession = testAccession;
	}

	public CaseRoi(BigDecimal caseRoiId, RoiSelection roiSelection, Roi roi,
			TestAccession testAccession, Subsidiary subsidiary, String caseId,
			String status, String createdBy, Date dateCreated,
			String modifiedBy, Date dateModified,
			Set<PcrSetupPlaceRoi> pcrSetupPlaceRois) {
		this.caseRoiId = caseRoiId;
		this.roiSelection = roiSelection;
		this.roi = roi;
		this.testAccession = testAccession;
		this.subsidiary = subsidiary;
		this.caseId = caseId;
		this.status = status;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.pcrSetupPlaceRois = pcrSetupPlaceRois;
	}

	public BigDecimal getCaseRoiId() {
		return this.caseRoiId;
	}

	public void setCaseRoiId(BigDecimal caseRoiId) {
		this.caseRoiId = caseRoiId;
	}

	public RoiSelection getRoiSelection() {
		return this.roiSelection;
	}

	public void setRoiSelection(RoiSelection roiSelection) {
		this.roiSelection = roiSelection;
	}

	public Roi getRoi() {
		return this.roi;
	}

	public void setRoi(Roi roi) {
		this.roi = roi;
	}

	public TestAccession getTestAccession() {
		return this.testAccession;
	}

	public void setTestAccession(TestAccession testAccession) {
		this.testAccession = testAccession;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public String getCaseId() {
		return this.caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public Set<PcrSetupPlaceRoi> getPcrSetupPlaceRois() {
		return this.pcrSetupPlaceRois;
	}

	public void setPcrSetupPlaceRois(Set<PcrSetupPlaceRoi> pcrSetupPlaceRois) {
		this.pcrSetupPlaceRois = pcrSetupPlaceRois;
	}

}
