package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * CaseHistory generated by hbm2java
 */
public class CaseHistory implements java.io.Serializable {

	private BigDecimal caseHistId;
	private CaseStatus caseStatus;
	private TestAccession testAccession;
	private StepTemplate stepTemplate;
	private Subsidiary subsidiary;
	private BigDecimal checklistId;
	private String procedureName;
	private String createdBy;
	private Date dateCreated;

	public CaseHistory() {
	}

	public CaseHistory(BigDecimal caseHistId, TestAccession testAccession) {
		this.caseHistId = caseHistId;
		this.testAccession = testAccession;
	}

	public CaseHistory(BigDecimal caseHistId, CaseStatus caseStatus,
			TestAccession testAccession, StepTemplate stepTemplate,
			Subsidiary subsidiary, BigDecimal checklistId,
			String procedureName, String createdBy, Date dateCreated) {
		this.caseHistId = caseHistId;
		this.caseStatus = caseStatus;
		this.testAccession = testAccession;
		this.stepTemplate = stepTemplate;
		this.subsidiary = subsidiary;
		this.checklistId = checklistId;
		this.procedureName = procedureName;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public BigDecimal getCaseHistId() {
		return this.caseHistId;
	}

	public void setCaseHistId(BigDecimal caseHistId) {
		this.caseHistId = caseHistId;
	}

	public CaseStatus getCaseStatus() {
		return this.caseStatus;
	}

	public void setCaseStatus(CaseStatus caseStatus) {
		this.caseStatus = caseStatus;
	}

	public TestAccession getTestAccession() {
		return this.testAccession;
	}

	public void setTestAccession(TestAccession testAccession) {
		this.testAccession = testAccession;
	}

	public StepTemplate getStepTemplate() {
		return this.stepTemplate;
	}

	public void setStepTemplate(StepTemplate stepTemplate) {
		this.stepTemplate = stepTemplate;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public BigDecimal getChecklistId() {
		return this.checklistId;
	}

	public void setChecklistId(BigDecimal checklistId) {
		this.checklistId = checklistId;
	}

	public String getProcedureName() {
		return this.procedureName;
	}

	public void setProcedureName(String procedureName) {
		this.procedureName = procedureName;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
