package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * CdxCpRunQc generated by hbm2java
 */
public class CdxCpRunQc implements java.io.Serializable {

	private BigDecimal cdxCpRunQcId;
	private CpRun cpRun;
	private String runQcStatus;
	private String pbmcData;
	private String pbmcStatus;
	private String negcontrolData;
	private String negcontrolStatus;
	private String expProfileData;
	private String expProfileStatus;
	private String genomicData;
	private String genomicStatus;
	private String sdData;
	private String sdStatus;
	private String cpData;
	private String cpStatus;

	public CdxCpRunQc() {
	}

	public CdxCpRunQc(BigDecimal cdxCpRunQcId, CpRun cpRun) {
		this.cdxCpRunQcId = cdxCpRunQcId;
		this.cpRun = cpRun;
	}

	public CdxCpRunQc(BigDecimal cdxCpRunQcId, CpRun cpRun, String runQcStatus,
			String pbmcData, String pbmcStatus, String negcontrolData,
			String negcontrolStatus, String expProfileData,
			String expProfileStatus, String genomicData, String genomicStatus,
			String sdData, String sdStatus, String cpData, String cpStatus) {
		this.cdxCpRunQcId = cdxCpRunQcId;
		this.cpRun = cpRun;
		this.runQcStatus = runQcStatus;
		this.pbmcData = pbmcData;
		this.pbmcStatus = pbmcStatus;
		this.negcontrolData = negcontrolData;
		this.negcontrolStatus = negcontrolStatus;
		this.expProfileData = expProfileData;
		this.expProfileStatus = expProfileStatus;
		this.genomicData = genomicData;
		this.genomicStatus = genomicStatus;
		this.sdData = sdData;
		this.sdStatus = sdStatus;
		this.cpData = cpData;
		this.cpStatus = cpStatus;
	}

	public BigDecimal getCdxCpRunQcId() {
		return this.cdxCpRunQcId;
	}

	public void setCdxCpRunQcId(BigDecimal cdxCpRunQcId) {
		this.cdxCpRunQcId = cdxCpRunQcId;
	}

	public CpRun getCpRun() {
		return this.cpRun;
	}

	public void setCpRun(CpRun cpRun) {
		this.cpRun = cpRun;
	}

	public String getRunQcStatus() {
		return this.runQcStatus;
	}

	public void setRunQcStatus(String runQcStatus) {
		this.runQcStatus = runQcStatus;
	}

	public String getPbmcData() {
		return this.pbmcData;
	}

	public void setPbmcData(String pbmcData) {
		this.pbmcData = pbmcData;
	}

	public String getPbmcStatus() {
		return this.pbmcStatus;
	}

	public void setPbmcStatus(String pbmcStatus) {
		this.pbmcStatus = pbmcStatus;
	}

	public String getNegcontrolData() {
		return this.negcontrolData;
	}

	public void setNegcontrolData(String negcontrolData) {
		this.negcontrolData = negcontrolData;
	}

	public String getNegcontrolStatus() {
		return this.negcontrolStatus;
	}

	public void setNegcontrolStatus(String negcontrolStatus) {
		this.negcontrolStatus = negcontrolStatus;
	}

	public String getExpProfileData() {
		return this.expProfileData;
	}

	public void setExpProfileData(String expProfileData) {
		this.expProfileData = expProfileData;
	}

	public String getExpProfileStatus() {
		return this.expProfileStatus;
	}

	public void setExpProfileStatus(String expProfileStatus) {
		this.expProfileStatus = expProfileStatus;
	}

	public String getGenomicData() {
		return this.genomicData;
	}

	public void setGenomicData(String genomicData) {
		this.genomicData = genomicData;
	}

	public String getGenomicStatus() {
		return this.genomicStatus;
	}

	public void setGenomicStatus(String genomicStatus) {
		this.genomicStatus = genomicStatus;
	}

	public String getSdData() {
		return this.sdData;
	}

	public void setSdData(String sdData) {
		this.sdData = sdData;
	}

	public String getSdStatus() {
		return this.sdStatus;
	}

	public void setSdStatus(String sdStatus) {
		this.sdStatus = sdStatus;
	}

	public String getCpData() {
		return this.cpData;
	}

	public void setCpData(String cpData) {
		this.cpData = cpData;
	}

	public String getCpStatus() {
		return this.cpStatus;
	}

	public void setCpStatus(String cpStatus) {
		this.cpStatus = cpStatus;
	}

}
