package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ConfigAttribute generated by hbm2java
 */
public class ConfigAttribute implements java.io.Serializable {

	private BigDecimal configAttributeId;
	private Variable variable;
	private String objectType;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal subsidiaryId;
	private Set<RoiAttributeFld> roiAttributeFlds = new HashSet<RoiAttributeFld>(
			0);
	private Set<AssignInstrumentValue> assignInstrumentValues = new HashSet<AssignInstrumentValue>(
			0);

	public ConfigAttribute() {
	}

	public ConfigAttribute(BigDecimal configAttributeId, Variable variable,
			String objectType) {
		this.configAttributeId = configAttributeId;
		this.variable = variable;
		this.objectType = objectType;
	}

	public ConfigAttribute(BigDecimal configAttributeId, Variable variable,
			String objectType, String createdBy, Date dateCreated,
			String modifiedBy, Date dateModified, BigDecimal subsidiaryId,
			Set<RoiAttributeFld> roiAttributeFlds,
			Set<AssignInstrumentValue> assignInstrumentValues) {
		this.configAttributeId = configAttributeId;
		this.variable = variable;
		this.objectType = objectType;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.subsidiaryId = subsidiaryId;
		this.roiAttributeFlds = roiAttributeFlds;
		this.assignInstrumentValues = assignInstrumentValues;
	}

	public BigDecimal getConfigAttributeId() {
		return this.configAttributeId;
	}

	public void setConfigAttributeId(BigDecimal configAttributeId) {
		this.configAttributeId = configAttributeId;
	}

	public Variable getVariable() {
		return this.variable;
	}

	public void setVariable(Variable variable) {
		this.variable = variable;
	}

	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

	public Set<RoiAttributeFld> getRoiAttributeFlds() {
		return this.roiAttributeFlds;
	}

	public void setRoiAttributeFlds(Set<RoiAttributeFld> roiAttributeFlds) {
		this.roiAttributeFlds = roiAttributeFlds;
	}

	public Set<AssignInstrumentValue> getAssignInstrumentValues() {
		return this.assignInstrumentValues;
	}

	public void setAssignInstrumentValues(
			Set<AssignInstrumentValue> assignInstrumentValues) {
		this.assignInstrumentValues = assignInstrumentValues;
	}

}
