package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * ContainerFilename generated by hbm2java
 */
public class ContainerFilename implements java.io.Serializable {

	private ContainerFilenameId id;
	private Container container;
	private Subsidiary subsidiary;
	private Filename filename;

	public ContainerFilename() {
	}

	public ContainerFilename(ContainerFilenameId id, Container container,
			Filename filename) {
		this.id = id;
		this.container = container;
		this.filename = filename;
	}

	public ContainerFilename(ContainerFilenameId id, Container container,
			Subsidiary subsidiary, Filename filename) {
		this.id = id;
		this.container = container;
		this.subsidiary = subsidiary;
		this.filename = filename;
	}

	public ContainerFilenameId getId() {
		return this.id;
	}

	public void setId(ContainerFilenameId id) {
		this.id = id;
	}

	public Container getContainer() {
		return this.container;
	}

	public void setContainer(Container container) {
		this.container = container;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public Filename getFilename() {
		return this.filename;
	}

	public void setFilename(Filename filename) {
		this.filename = filename;
	}

}
