package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Container generated by hbm2java
 */
public class Container implements java.io.Serializable {

	private String containerId;
	private Freezer freezer;
	private Subsidiary subsidiary;
	private ContainerMap containerMap;
	private String compartment;
	private String shelf;
	private String rack;
	private String location;
	private String purpose;
	private String description;
	private String checkoutBy;
	private Date dateCheckout;
	private Boolean discarded;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private String containerCondition;
	private String status;
	private String comments;
	private Set<SpecimenShipmentPackage> specimenShipmentPackagesForContainerIdTo = new HashSet<SpecimenShipmentPackage>(
			0);
	private Set<MtpSample> mtpSamples = new HashSet<MtpSample>(0);
	private Set<ContainerFilename> containerFilenames = new HashSet<ContainerFilename>(
			0);
	private Set<TraceQc> traceQcs = new HashSet<TraceQc>(0);
	private Set<ContainerReagent> containerReagents = new HashSet<ContainerReagent>(
			0);
	private Set<PcrCleanupContainer> pcrCleanupContainersForFilterContainerId = new HashSet<PcrCleanupContainer>(
			0);
	private Set<SeqSetupContainer> seqSetupContainersForRevContainerId = new HashSet<SeqSetupContainer>(
			0);
	private Set<PcrSetupContainer> pcrSetupContainers = new HashSet<PcrSetupContainer>(
			0);
	private Set<GelMarker> gelMarkers = new HashSet<GelMarker>(0);
	private Set<SpecimenShipmentPackage> specimenShipmentPackagesForContainerIdFrom = new HashSet<SpecimenShipmentPackage>(
			0);
	private Set<PcrCleanupContainer> pcrCleanupContainersForElutionContainerId = new HashSet<PcrCleanupContainer>(
			0);
	private Set<SampleTable> sampleTables = new HashSet<SampleTable>(0);
	private Set<CpRun> cpRuns = new HashSet<CpRun>(0);
	private Set<AssignInstrument> assignInstruments = new HashSet<AssignInstrument>(
			0);
	private Set<OligoAssayDesign> oligoAssayDesigns = new HashSet<OligoAssayDesign>(
			0);
	private Set<PlateTemplateContainer> plateTemplateContainers = new HashSet<PlateTemplateContainer>(
			0);
	private Set<PcrSetupOligo> pcrSetupOligos = new HashSet<PcrSetupOligo>(0);
	private Set<SeqSetupContainer> seqSetupContainersForFwdContainerId = new HashSet<SeqSetupContainer>(
			0);
	private Set<Reagent> reagents = new HashSet<Reagent>(0);
	private Set<SampleInstrumentAssoc> sampleInstrumentAssocs = new HashSet<SampleInstrumentAssoc>(
			0);

	public Container() {
	}

	public Container(String containerId) {
		this.containerId = containerId;
	}

	public Container(
			String containerId,
			Freezer freezer,
			Subsidiary subsidiary,
			ContainerMap containerMap,
			String compartment,
			String shelf,
			String rack,
			String location,
			String purpose,
			String description,
			String checkoutBy,
			Date dateCheckout,
			Boolean discarded,
			String createdBy,
			Date dateCreated,
			String modifiedBy,
			Date dateModified,
			String containerCondition,
			String status,
			String comments,
			Set<SpecimenShipmentPackage> specimenShipmentPackagesForContainerIdTo,
			Set<MtpSample> mtpSamples,
			Set<ContainerFilename> containerFilenames,
			Set<TraceQc> traceQcs,
			Set<ContainerReagent> containerReagents,
			Set<PcrCleanupContainer> pcrCleanupContainersForFilterContainerId,
			Set<SeqSetupContainer> seqSetupContainersForRevContainerId,
			Set<PcrSetupContainer> pcrSetupContainers,
			Set<GelMarker> gelMarkers,
			Set<SpecimenShipmentPackage> specimenShipmentPackagesForContainerIdFrom,
			Set<PcrCleanupContainer> pcrCleanupContainersForElutionContainerId,
			Set<SampleTable> sampleTables, Set<CpRun> cpRuns,
			Set<AssignInstrument> assignInstruments,
			Set<OligoAssayDesign> oligoAssayDesigns,
			Set<PlateTemplateContainer> plateTemplateContainers,
			Set<PcrSetupOligo> pcrSetupOligos,
			Set<SeqSetupContainer> seqSetupContainersForFwdContainerId,
			Set<Reagent> reagents,
			Set<SampleInstrumentAssoc> sampleInstrumentAssocs) {
		this.containerId = containerId;
		this.freezer = freezer;
		this.subsidiary = subsidiary;
		this.containerMap = containerMap;
		this.compartment = compartment;
		this.shelf = shelf;
		this.rack = rack;
		this.location = location;
		this.purpose = purpose;
		this.description = description;
		this.checkoutBy = checkoutBy;
		this.dateCheckout = dateCheckout;
		this.discarded = discarded;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.containerCondition = containerCondition;
		this.status = status;
		this.comments = comments;
		this.specimenShipmentPackagesForContainerIdTo = specimenShipmentPackagesForContainerIdTo;
		this.mtpSamples = mtpSamples;
		this.containerFilenames = containerFilenames;
		this.traceQcs = traceQcs;
		this.containerReagents = containerReagents;
		this.pcrCleanupContainersForFilterContainerId = pcrCleanupContainersForFilterContainerId;
		this.seqSetupContainersForRevContainerId = seqSetupContainersForRevContainerId;
		this.pcrSetupContainers = pcrSetupContainers;
		this.gelMarkers = gelMarkers;
		this.specimenShipmentPackagesForContainerIdFrom = specimenShipmentPackagesForContainerIdFrom;
		this.pcrCleanupContainersForElutionContainerId = pcrCleanupContainersForElutionContainerId;
		this.sampleTables = sampleTables;
		this.cpRuns = cpRuns;
		this.assignInstruments = assignInstruments;
		this.oligoAssayDesigns = oligoAssayDesigns;
		this.plateTemplateContainers = plateTemplateContainers;
		this.pcrSetupOligos = pcrSetupOligos;
		this.seqSetupContainersForFwdContainerId = seqSetupContainersForFwdContainerId;
		this.reagents = reagents;
		this.sampleInstrumentAssocs = sampleInstrumentAssocs;
	}

	public String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(String containerId) {
		this.containerId = containerId;
	}

	public Freezer getFreezer() {
		return this.freezer;
	}

	public void setFreezer(Freezer freezer) {
		this.freezer = freezer;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public ContainerMap getContainerMap() {
		return this.containerMap;
	}

	public void setContainerMap(ContainerMap containerMap) {
		this.containerMap = containerMap;
	}

	public String getCompartment() {
		return this.compartment;
	}

	public void setCompartment(String compartment) {
		this.compartment = compartment;
	}

	public String getShelf() {
		return this.shelf;
	}

	public void setShelf(String shelf) {
		this.shelf = shelf;
	}

	public String getRack() {
		return this.rack;
	}

	public void setRack(String rack) {
		this.rack = rack;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCheckoutBy() {
		return this.checkoutBy;
	}

	public void setCheckoutBy(String checkoutBy) {
		this.checkoutBy = checkoutBy;
	}

	public Date getDateCheckout() {
		return this.dateCheckout;
	}

	public void setDateCheckout(Date dateCheckout) {
		this.dateCheckout = dateCheckout;
	}

	public Boolean getDiscarded() {
		return this.discarded;
	}

	public void setDiscarded(Boolean discarded) {
		this.discarded = discarded;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public String getContainerCondition() {
		return this.containerCondition;
	}

	public void setContainerCondition(String containerCondition) {
		this.containerCondition = containerCondition;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Set<SpecimenShipmentPackage> getSpecimenShipmentPackagesForContainerIdTo() {
		return this.specimenShipmentPackagesForContainerIdTo;
	}

	public void setSpecimenShipmentPackagesForContainerIdTo(
			Set<SpecimenShipmentPackage> specimenShipmentPackagesForContainerIdTo) {
		this.specimenShipmentPackagesForContainerIdTo = specimenShipmentPackagesForContainerIdTo;
	}

	public Set<MtpSample> getMtpSamples() {
		return this.mtpSamples;
	}

	public void setMtpSamples(Set<MtpSample> mtpSamples) {
		this.mtpSamples = mtpSamples;
	}

	public Set<ContainerFilename> getContainerFilenames() {
		return this.containerFilenames;
	}

	public void setContainerFilenames(Set<ContainerFilename> containerFilenames) {
		this.containerFilenames = containerFilenames;
	}

	public Set<TraceQc> getTraceQcs() {
		return this.traceQcs;
	}

	public void setTraceQcs(Set<TraceQc> traceQcs) {
		this.traceQcs = traceQcs;
	}

	public Set<ContainerReagent> getContainerReagents() {
		return this.containerReagents;
	}

	public void setContainerReagents(Set<ContainerReagent> containerReagents) {
		this.containerReagents = containerReagents;
	}

	public Set<PcrCleanupContainer> getPcrCleanupContainersForFilterContainerId() {
		return this.pcrCleanupContainersForFilterContainerId;
	}

	public void setPcrCleanupContainersForFilterContainerId(
			Set<PcrCleanupContainer> pcrCleanupContainersForFilterContainerId) {
		this.pcrCleanupContainersForFilterContainerId = pcrCleanupContainersForFilterContainerId;
	}

	public Set<SeqSetupContainer> getSeqSetupContainersForRevContainerId() {
		return this.seqSetupContainersForRevContainerId;
	}

	public void setSeqSetupContainersForRevContainerId(
			Set<SeqSetupContainer> seqSetupContainersForRevContainerId) {
		this.seqSetupContainersForRevContainerId = seqSetupContainersForRevContainerId;
	}

	public Set<PcrSetupContainer> getPcrSetupContainers() {
		return this.pcrSetupContainers;
	}

	public void setPcrSetupContainers(Set<PcrSetupContainer> pcrSetupContainers) {
		this.pcrSetupContainers = pcrSetupContainers;
	}

	public Set<GelMarker> getGelMarkers() {
		return this.gelMarkers;
	}

	public void setGelMarkers(Set<GelMarker> gelMarkers) {
		this.gelMarkers = gelMarkers;
	}

	public Set<SpecimenShipmentPackage> getSpecimenShipmentPackagesForContainerIdFrom() {
		return this.specimenShipmentPackagesForContainerIdFrom;
	}

	public void setSpecimenShipmentPackagesForContainerIdFrom(
			Set<SpecimenShipmentPackage> specimenShipmentPackagesForContainerIdFrom) {
		this.specimenShipmentPackagesForContainerIdFrom = specimenShipmentPackagesForContainerIdFrom;
	}

	public Set<PcrCleanupContainer> getPcrCleanupContainersForElutionContainerId() {
		return this.pcrCleanupContainersForElutionContainerId;
	}

	public void setPcrCleanupContainersForElutionContainerId(
			Set<PcrCleanupContainer> pcrCleanupContainersForElutionContainerId) {
		this.pcrCleanupContainersForElutionContainerId = pcrCleanupContainersForElutionContainerId;
	}

	public Set<SampleTable> getSampleTables() {
		return this.sampleTables;
	}

	public void setSampleTables(Set<SampleTable> sampleTables) {
		this.sampleTables = sampleTables;
	}

	public Set<CpRun> getCpRuns() {
		return this.cpRuns;
	}

	public void setCpRuns(Set<CpRun> cpRuns) {
		this.cpRuns = cpRuns;
	}

	public Set<AssignInstrument> getAssignInstruments() {
		return this.assignInstruments;
	}

	public void setAssignInstruments(Set<AssignInstrument> assignInstruments) {
		this.assignInstruments = assignInstruments;
	}

	public Set<OligoAssayDesign> getOligoAssayDesigns() {
		return this.oligoAssayDesigns;
	}

	public void setOligoAssayDesigns(Set<OligoAssayDesign> oligoAssayDesigns) {
		this.oligoAssayDesigns = oligoAssayDesigns;
	}

	public Set<PlateTemplateContainer> getPlateTemplateContainers() {
		return this.plateTemplateContainers;
	}

	public void setPlateTemplateContainers(
			Set<PlateTemplateContainer> plateTemplateContainers) {
		this.plateTemplateContainers = plateTemplateContainers;
	}

	public Set<PcrSetupOligo> getPcrSetupOligos() {
		return this.pcrSetupOligos;
	}

	public void setPcrSetupOligos(Set<PcrSetupOligo> pcrSetupOligos) {
		this.pcrSetupOligos = pcrSetupOligos;
	}

	public Set<SeqSetupContainer> getSeqSetupContainersForFwdContainerId() {
		return this.seqSetupContainersForFwdContainerId;
	}

	public void setSeqSetupContainersForFwdContainerId(
			Set<SeqSetupContainer> seqSetupContainersForFwdContainerId) {
		this.seqSetupContainersForFwdContainerId = seqSetupContainersForFwdContainerId;
	}

	public Set<Reagent> getReagents() {
		return this.reagents;
	}

	public void setReagents(Set<Reagent> reagents) {
		this.reagents = reagents;
	}

	public Set<SampleInstrumentAssoc> getSampleInstrumentAssocs() {
		return this.sampleInstrumentAssocs;
	}

	public void setSampleInstrumentAssocs(
			Set<SampleInstrumentAssoc> sampleInstrumentAssocs) {
		this.sampleInstrumentAssocs = sampleInstrumentAssocs;
	}

}
