package com.cardiodx.db.waban.table;
// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1


import com.cardiodx.db.waban.table.Create.java.lob.tableId;

/**
 * Create.java.lob.table generated by hbm2java
 */
public class Create.java.lob.table  implements java.io.Serializable {


     private Create.java.lob.tableId id;

    public Create.java.lob.table() {
    }

    public Create.java.lob.table(Create.java.lob.tableId id) {
       this.id = id;
    }
   
    public Create.java.lob.tableId getId() {
        return this.id;
    }
    
    public void setId(Create.java.lob.tableId id) {
        this.id = id;
    }




}


