package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * EventProcess generated by hbm2java
 */
public class EventProcess implements java.io.Serializable {

	private EventProcessId id;
	private Subsidiary subsidiary;
	private String objectId;
	private String objectType;
	private String processedBy;
	private Date dateProcessed;
	private String warning;
	private BigDecimal eventHandlerId;

	public EventProcess() {
	}

	public EventProcess(EventProcessId id) {
		this.id = id;
	}

	public EventProcess(EventProcessId id, Subsidiary subsidiary,
			String objectId, String objectType, String processedBy,
			Date dateProcessed, String warning, BigDecimal eventHandlerId) {
		this.id = id;
		this.subsidiary = subsidiary;
		this.objectId = objectId;
		this.objectType = objectType;
		this.processedBy = processedBy;
		this.dateProcessed = dateProcessed;
		this.warning = warning;
		this.eventHandlerId = eventHandlerId;
	}

	public EventProcessId getId() {
		return this.id;
	}

	public void setId(EventProcessId id) {
		this.id = id;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	public String getProcessedBy() {
		return this.processedBy;
	}

	public void setProcessedBy(String processedBy) {
		this.processedBy = processedBy;
	}

	public Date getDateProcessed() {
		return this.dateProcessed;
	}

	public void setDateProcessed(Date dateProcessed) {
		this.dateProcessed = dateProcessed;
	}

	public String getWarning() {
		return this.warning;
	}

	public void setWarning(String warning) {
		this.warning = warning;
	}

	public BigDecimal getEventHandlerId() {
		return this.eventHandlerId;
	}

	public void setEventHandlerId(BigDecimal eventHandlerId) {
		this.eventHandlerId = eventHandlerId;
	}

}
