package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * FilenameR generated by hbm2java
 */
public class FilenameR implements java.io.Serializable {

	private FilenameRId id;
	private BigDecimal databaseId;

	public FilenameR() {
	}

	public FilenameR(FilenameRId id) {
		this.id = id;
	}

	public FilenameR(FilenameRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public FilenameRId getId() {
		return this.id;
	}

	public void setId(FilenameRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
