package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * FunctionalStep generated by hbm2java
 */
public class FunctionalStep implements java.io.Serializable {

	private BigDecimal functionalStepId;
	private OcxLoad ocxLoad;
	private String functionalStepName;
	private String description;
	private String sampleOcxName;
	private String batchOcxName;
	private String viewName;
	private Set<StepTemplate> stepTemplates = new HashSet<StepTemplate>(0);
	private Set<FunctionalStepParameter> functionalStepParameters = new HashSet<FunctionalStepParameter>(
			0);

	public FunctionalStep() {
	}

	public FunctionalStep(BigDecimal functionalStepId,
			String functionalStepName, String sampleOcxName, String batchOcxName) {
		this.functionalStepId = functionalStepId;
		this.functionalStepName = functionalStepName;
		this.sampleOcxName = sampleOcxName;
		this.batchOcxName = batchOcxName;
	}

	public FunctionalStep(BigDecimal functionalStepId, OcxLoad ocxLoad,
			String functionalStepName, String description,
			String sampleOcxName, String batchOcxName, String viewName,
			Set<StepTemplate> stepTemplates,
			Set<FunctionalStepParameter> functionalStepParameters) {
		this.functionalStepId = functionalStepId;
		this.ocxLoad = ocxLoad;
		this.functionalStepName = functionalStepName;
		this.description = description;
		this.sampleOcxName = sampleOcxName;
		this.batchOcxName = batchOcxName;
		this.viewName = viewName;
		this.stepTemplates = stepTemplates;
		this.functionalStepParameters = functionalStepParameters;
	}

	public BigDecimal getFunctionalStepId() {
		return this.functionalStepId;
	}

	public void setFunctionalStepId(BigDecimal functionalStepId) {
		this.functionalStepId = functionalStepId;
	}

	public OcxLoad getOcxLoad() {
		return this.ocxLoad;
	}

	public void setOcxLoad(OcxLoad ocxLoad) {
		this.ocxLoad = ocxLoad;
	}

	public String getFunctionalStepName() {
		return this.functionalStepName;
	}

	public void setFunctionalStepName(String functionalStepName) {
		this.functionalStepName = functionalStepName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSampleOcxName() {
		return this.sampleOcxName;
	}

	public void setSampleOcxName(String sampleOcxName) {
		this.sampleOcxName = sampleOcxName;
	}

	public String getBatchOcxName() {
		return this.batchOcxName;
	}

	public void setBatchOcxName(String batchOcxName) {
		this.batchOcxName = batchOcxName;
	}

	public String getViewName() {
		return this.viewName;
	}

	public void setViewName(String viewName) {
		this.viewName = viewName;
	}

	public Set<StepTemplate> getStepTemplates() {
		return this.stepTemplates;
	}

	public void setStepTemplates(Set<StepTemplate> stepTemplates) {
		this.stepTemplates = stepTemplates;
	}

	public Set<FunctionalStepParameter> getFunctionalStepParameters() {
		return this.functionalStepParameters;
	}

	public void setFunctionalStepParameters(
			Set<FunctionalStepParameter> functionalStepParameters) {
		this.functionalStepParameters = functionalStepParameters;
	}

}
