package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Gene generated by hbm2java
 */
public class Gene implements java.io.Serializable {

	private BigDecimal geneId;
	private String geneName;
	private String geneLongName;
	private BigDecimal numberInSequence;
	private String description;
	private Clob sequence;
	private String organism;
	private String range;
	private String ensemblId;
	private Set<PgxGeneDataReport> pgxGeneDataReports = new HashSet<PgxGeneDataReport>(
			0);
	private Set<ProtocolGene> protocolGenes = new HashSet<ProtocolGene>(0);
	private Set<MdbStructure> mdbStructures = new HashSet<MdbStructure>(0);
	private Set<Roi> rois = new HashSet<Roi>(0);
	private Set<GenotypeAutocallRule> genotypeAutocallRules = new HashSet<GenotypeAutocallRule>(
			0);
	private Set<PgxGeneNarrativeTemplates> pgxGeneNarrativeTemplateses = new HashSet<PgxGeneNarrativeTemplates>(
			0);
	private Set<Assay> assaies = new HashSet<Assay>(0);
	private Set<MdbPolymorphism> mdbPolymorphisms = new HashSet<MdbPolymorphism>(
			0);
	private Set<ProcedureTemplateGene> procedureTemplateGenes = new HashSet<ProcedureTemplateGene>(
			0);
	private Set<GeneValue> geneValues = new HashSet<GeneValue>(0);
	private Set<PgxModifiedGeneTemplate> pgxModifiedGeneTemplates = new HashSet<PgxModifiedGeneTemplate>(
			0);
	private Set<GeneResult> geneResults = new HashSet<GeneResult>(0);
	private Set<GeneInterpretation> geneInterpretations = new HashSet<GeneInterpretation>(
			0);
	private Set<Allele> alleles = new HashSet<Allele>(0);
	private Set<MdbVariant> mdbVariants = new HashSet<MdbVariant>(0);
	private Set<PhenotypeAutocallRule> phenotypeAutocallRules = new HashSet<PhenotypeAutocallRule>(
			0);

	public Gene() {
	}

	public Gene(BigDecimal geneId, String geneName) {
		this.geneId = geneId;
		this.geneName = geneName;
	}

	public Gene(BigDecimal geneId, String geneName, String geneLongName,
			BigDecimal numberInSequence, String description, Clob sequence,
			String organism, String range, String ensemblId,
			Set<PgxGeneDataReport> pgxGeneDataReports,
			Set<ProtocolGene> protocolGenes, Set<MdbStructure> mdbStructures,
			Set<Roi> rois, Set<GenotypeAutocallRule> genotypeAutocallRules,
			Set<PgxGeneNarrativeTemplates> pgxGeneNarrativeTemplateses,
			Set<Assay> assaies, Set<MdbPolymorphism> mdbPolymorphisms,
			Set<ProcedureTemplateGene> procedureTemplateGenes,
			Set<GeneValue> geneValues,
			Set<PgxModifiedGeneTemplate> pgxModifiedGeneTemplates,
			Set<GeneResult> geneResults,
			Set<GeneInterpretation> geneInterpretations, Set<Allele> alleles,
			Set<MdbVariant> mdbVariants,
			Set<PhenotypeAutocallRule> phenotypeAutocallRules) {
		this.geneId = geneId;
		this.geneName = geneName;
		this.geneLongName = geneLongName;
		this.numberInSequence = numberInSequence;
		this.description = description;
		this.sequence = sequence;
		this.organism = organism;
		this.range = range;
		this.ensemblId = ensemblId;
		this.pgxGeneDataReports = pgxGeneDataReports;
		this.protocolGenes = protocolGenes;
		this.mdbStructures = mdbStructures;
		this.rois = rois;
		this.genotypeAutocallRules = genotypeAutocallRules;
		this.pgxGeneNarrativeTemplateses = pgxGeneNarrativeTemplateses;
		this.assaies = assaies;
		this.mdbPolymorphisms = mdbPolymorphisms;
		this.procedureTemplateGenes = procedureTemplateGenes;
		this.geneValues = geneValues;
		this.pgxModifiedGeneTemplates = pgxModifiedGeneTemplates;
		this.geneResults = geneResults;
		this.geneInterpretations = geneInterpretations;
		this.alleles = alleles;
		this.mdbVariants = mdbVariants;
		this.phenotypeAutocallRules = phenotypeAutocallRules;
	}

	public BigDecimal getGeneId() {
		return this.geneId;
	}

	public void setGeneId(BigDecimal geneId) {
		this.geneId = geneId;
	}

	public String getGeneName() {
		return this.geneName;
	}

	public void setGeneName(String geneName) {
		this.geneName = geneName;
	}

	public String getGeneLongName() {
		return this.geneLongName;
	}

	public void setGeneLongName(String geneLongName) {
		this.geneLongName = geneLongName;
	}

	public BigDecimal getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(BigDecimal numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Clob getSequence() {
		return this.sequence;
	}

	public void setSequence(Clob sequence) {
		this.sequence = sequence;
	}

	public String getOrganism() {
		return this.organism;
	}

	public void setOrganism(String organism) {
		this.organism = organism;
	}

	public String getRange() {
		return this.range;
	}

	public void setRange(String range) {
		this.range = range;
	}

	public String getEnsemblId() {
		return this.ensemblId;
	}

	public void setEnsemblId(String ensemblId) {
		this.ensemblId = ensemblId;
	}

	public Set<PgxGeneDataReport> getPgxGeneDataReports() {
		return this.pgxGeneDataReports;
	}

	public void setPgxGeneDataReports(Set<PgxGeneDataReport> pgxGeneDataReports) {
		this.pgxGeneDataReports = pgxGeneDataReports;
	}

	public Set<ProtocolGene> getProtocolGenes() {
		return this.protocolGenes;
	}

	public void setProtocolGenes(Set<ProtocolGene> protocolGenes) {
		this.protocolGenes = protocolGenes;
	}

	public Set<MdbStructure> getMdbStructures() {
		return this.mdbStructures;
	}

	public void setMdbStructures(Set<MdbStructure> mdbStructures) {
		this.mdbStructures = mdbStructures;
	}

	public Set<Roi> getRois() {
		return this.rois;
	}

	public void setRois(Set<Roi> rois) {
		this.rois = rois;
	}

	public Set<GenotypeAutocallRule> getGenotypeAutocallRules() {
		return this.genotypeAutocallRules;
	}

	public void setGenotypeAutocallRules(
			Set<GenotypeAutocallRule> genotypeAutocallRules) {
		this.genotypeAutocallRules = genotypeAutocallRules;
	}

	public Set<PgxGeneNarrativeTemplates> getPgxGeneNarrativeTemplateses() {
		return this.pgxGeneNarrativeTemplateses;
	}

	public void setPgxGeneNarrativeTemplateses(
			Set<PgxGeneNarrativeTemplates> pgxGeneNarrativeTemplateses) {
		this.pgxGeneNarrativeTemplateses = pgxGeneNarrativeTemplateses;
	}

	public Set<Assay> getAssaies() {
		return this.assaies;
	}

	public void setAssaies(Set<Assay> assaies) {
		this.assaies = assaies;
	}

	public Set<MdbPolymorphism> getMdbPolymorphisms() {
		return this.mdbPolymorphisms;
	}

	public void setMdbPolymorphisms(Set<MdbPolymorphism> mdbPolymorphisms) {
		this.mdbPolymorphisms = mdbPolymorphisms;
	}

	public Set<ProcedureTemplateGene> getProcedureTemplateGenes() {
		return this.procedureTemplateGenes;
	}

	public void setProcedureTemplateGenes(
			Set<ProcedureTemplateGene> procedureTemplateGenes) {
		this.procedureTemplateGenes = procedureTemplateGenes;
	}

	public Set<GeneValue> getGeneValues() {
		return this.geneValues;
	}

	public void setGeneValues(Set<GeneValue> geneValues) {
		this.geneValues = geneValues;
	}

	public Set<PgxModifiedGeneTemplate> getPgxModifiedGeneTemplates() {
		return this.pgxModifiedGeneTemplates;
	}

	public void setPgxModifiedGeneTemplates(
			Set<PgxModifiedGeneTemplate> pgxModifiedGeneTemplates) {
		this.pgxModifiedGeneTemplates = pgxModifiedGeneTemplates;
	}

	public Set<GeneResult> getGeneResults() {
		return this.geneResults;
	}

	public void setGeneResults(Set<GeneResult> geneResults) {
		this.geneResults = geneResults;
	}

	public Set<GeneInterpretation> getGeneInterpretations() {
		return this.geneInterpretations;
	}

	public void setGeneInterpretations(
			Set<GeneInterpretation> geneInterpretations) {
		this.geneInterpretations = geneInterpretations;
	}

	public Set<Allele> getAlleles() {
		return this.alleles;
	}

	public void setAlleles(Set<Allele> alleles) {
		this.alleles = alleles;
	}

	public Set<MdbVariant> getMdbVariants() {
		return this.mdbVariants;
	}

	public void setMdbVariants(Set<MdbVariant> mdbVariants) {
		this.mdbVariants = mdbVariants;
	}

	public Set<PhenotypeAutocallRule> getPhenotypeAutocallRules() {
		return this.phenotypeAutocallRules;
	}

	public void setPhenotypeAutocallRules(
			Set<PhenotypeAutocallRule> phenotypeAutocallRules) {
		this.phenotypeAutocallRules = phenotypeAutocallRules;
	}

}
