package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * GeneInterprDefinitionR generated by hbm2java
 */
public class GeneInterprDefinitionR implements java.io.Serializable {

	private GeneInterprDefinitionRId id;
	private BigDecimal databaseId;

	public GeneInterprDefinitionR() {
	}

	public GeneInterprDefinitionR(GeneInterprDefinitionRId id) {
		this.id = id;
	}

	public GeneInterprDefinitionR(GeneInterprDefinitionRId id,
			BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public GeneInterprDefinitionRId getId() {
		return this.id;
	}

	public void setId(GeneInterprDefinitionRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
