package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * InstrumentProgram generated by hbm2java
 */
public class InstrumentProgram implements java.io.Serializable {

	private BigDecimal instrumentProgramId;
	private Subsidiary subsidiary;
	private Instrument instrument;
	private String program;
	private BigDecimal numberInSequence;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;

	public InstrumentProgram() {
	}

	public InstrumentProgram(BigDecimal instrumentProgramId,
			Instrument instrument, String program) {
		this.instrumentProgramId = instrumentProgramId;
		this.instrument = instrument;
		this.program = program;
	}

	public InstrumentProgram(BigDecimal instrumentProgramId,
			Subsidiary subsidiary, Instrument instrument, String program,
			BigDecimal numberInSequence, String createdBy, Date dateCreated,
			String modifiedBy, Date dateModified) {
		this.instrumentProgramId = instrumentProgramId;
		this.subsidiary = subsidiary;
		this.instrument = instrument;
		this.program = program;
		this.numberInSequence = numberInSequence;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
	}

	public BigDecimal getInstrumentProgramId() {
		return this.instrumentProgramId;
	}

	public void setInstrumentProgramId(BigDecimal instrumentProgramId) {
		this.instrumentProgramId = instrumentProgramId;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public Instrument getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Instrument instrument) {
		this.instrument = instrument;
	}

	public String getProgram() {
		return this.program;
	}

	public void setProgram(String program) {
		this.program = program;
	}

	public BigDecimal getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(BigDecimal numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
