package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * MasterMixItem generated by hbm2java
 */
public class MasterMixItem implements java.io.Serializable {

	private BigDecimal masterMixItemId;
	private MasterMix masterMix;
	private String reagentName;
	private String reagentPfx;
	private BigDecimal targetAmount;
	private String targetUnits;
	private Set<MasterMixReagent> masterMixReagents = new HashSet<MasterMixReagent>(
			0);

	public MasterMixItem() {
	}

	public MasterMixItem(BigDecimal masterMixItemId) {
		this.masterMixItemId = masterMixItemId;
	}

	public MasterMixItem(BigDecimal masterMixItemId, MasterMix masterMix,
			String reagentName, String reagentPfx, BigDecimal targetAmount,
			String targetUnits, Set<MasterMixReagent> masterMixReagents) {
		this.masterMixItemId = masterMixItemId;
		this.masterMix = masterMix;
		this.reagentName = reagentName;
		this.reagentPfx = reagentPfx;
		this.targetAmount = targetAmount;
		this.targetUnits = targetUnits;
		this.masterMixReagents = masterMixReagents;
	}

	public BigDecimal getMasterMixItemId() {
		return this.masterMixItemId;
	}

	public void setMasterMixItemId(BigDecimal masterMixItemId) {
		this.masterMixItemId = masterMixItemId;
	}

	public MasterMix getMasterMix() {
		return this.masterMix;
	}

	public void setMasterMix(MasterMix masterMix) {
		this.masterMix = masterMix;
	}

	public String getReagentName() {
		return this.reagentName;
	}

	public void setReagentName(String reagentName) {
		this.reagentName = reagentName;
	}

	public String getReagentPfx() {
		return this.reagentPfx;
	}

	public void setReagentPfx(String reagentPfx) {
		this.reagentPfx = reagentPfx;
	}

	public BigDecimal getTargetAmount() {
		return this.targetAmount;
	}

	public void setTargetAmount(BigDecimal targetAmount) {
		this.targetAmount = targetAmount;
	}

	public String getTargetUnits() {
		return this.targetUnits;
	}

	public void setTargetUnits(String targetUnits) {
		this.targetUnits = targetUnits;
	}

	public Set<MasterMixReagent> getMasterMixReagents() {
		return this.masterMixReagents;
	}

	public void setMasterMixReagents(Set<MasterMixReagent> masterMixReagents) {
		this.masterMixReagents = masterMixReagents;
	}

}
