package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * OcxLoad generated by hbm2java
 */
public class OcxLoad implements java.io.Serializable {

	private BigDecimal ocxLoadId;
	private String ocxName;
	private String loadOcx;
	private String ocxVersion;
	private String minAppVersion;
	private String ocxType;
	private Blob ocxBlob;
	private Blob htmlBlob;
	private Blob lpkBlob;
	private Set<StudyProtocol> studyProtocolsForAccessionVarOcx = new HashSet<StudyProtocol>(
			0);
	private Set<MenuItem> menuItems = new HashSet<MenuItem>(0);
	private Set<FunctionalStep> functionalSteps = new HashSet<FunctionalStep>(0);
	private Set<StudyProtocol> studyProtocolsForStudyVarOcx = new HashSet<StudyProtocol>(
			0);
	private Set<ParentMenu> parentMenus = new HashSet<ParentMenu>(0);
	private Set<StudyProtocol> studyProtocolsForPatientVarOcx = new HashSet<StudyProtocol>(
			0);

	public OcxLoad() {
	}

	public OcxLoad(BigDecimal ocxLoadId, String ocxName, String loadOcx) {
		this.ocxLoadId = ocxLoadId;
		this.ocxName = ocxName;
		this.loadOcx = loadOcx;
	}

	public OcxLoad(BigDecimal ocxLoadId, String ocxName, String loadOcx,
			String ocxVersion, String minAppVersion, String ocxType,
			Blob ocxBlob, Blob htmlBlob, Blob lpkBlob,
			Set<StudyProtocol> studyProtocolsForAccessionVarOcx,
			Set<MenuItem> menuItems, Set<FunctionalStep> functionalSteps,
			Set<StudyProtocol> studyProtocolsForStudyVarOcx,
			Set<ParentMenu> parentMenus,
			Set<StudyProtocol> studyProtocolsForPatientVarOcx) {
		this.ocxLoadId = ocxLoadId;
		this.ocxName = ocxName;
		this.loadOcx = loadOcx;
		this.ocxVersion = ocxVersion;
		this.minAppVersion = minAppVersion;
		this.ocxType = ocxType;
		this.ocxBlob = ocxBlob;
		this.htmlBlob = htmlBlob;
		this.lpkBlob = lpkBlob;
		this.studyProtocolsForAccessionVarOcx = studyProtocolsForAccessionVarOcx;
		this.menuItems = menuItems;
		this.functionalSteps = functionalSteps;
		this.studyProtocolsForStudyVarOcx = studyProtocolsForStudyVarOcx;
		this.parentMenus = parentMenus;
		this.studyProtocolsForPatientVarOcx = studyProtocolsForPatientVarOcx;
	}

	public BigDecimal getOcxLoadId() {
		return this.ocxLoadId;
	}

	public void setOcxLoadId(BigDecimal ocxLoadId) {
		this.ocxLoadId = ocxLoadId;
	}

	public String getOcxName() {
		return this.ocxName;
	}

	public void setOcxName(String ocxName) {
		this.ocxName = ocxName;
	}

	public String getLoadOcx() {
		return this.loadOcx;
	}

	public void setLoadOcx(String loadOcx) {
		this.loadOcx = loadOcx;
	}

	public String getOcxVersion() {
		return this.ocxVersion;
	}

	public void setOcxVersion(String ocxVersion) {
		this.ocxVersion = ocxVersion;
	}

	public String getMinAppVersion() {
		return this.minAppVersion;
	}

	public void setMinAppVersion(String minAppVersion) {
		this.minAppVersion = minAppVersion;
	}

	public String getOcxType() {
		return this.ocxType;
	}

	public void setOcxType(String ocxType) {
		this.ocxType = ocxType;
	}

	public Blob getOcxBlob() {
		return this.ocxBlob;
	}

	public void setOcxBlob(Blob ocxBlob) {
		this.ocxBlob = ocxBlob;
	}

	public Blob getHtmlBlob() {
		return this.htmlBlob;
	}

	public void setHtmlBlob(Blob htmlBlob) {
		this.htmlBlob = htmlBlob;
	}

	public Blob getLpkBlob() {
		return this.lpkBlob;
	}

	public void setLpkBlob(Blob lpkBlob) {
		this.lpkBlob = lpkBlob;
	}

	public Set<StudyProtocol> getStudyProtocolsForAccessionVarOcx() {
		return this.studyProtocolsForAccessionVarOcx;
	}

	public void setStudyProtocolsForAccessionVarOcx(
			Set<StudyProtocol> studyProtocolsForAccessionVarOcx) {
		this.studyProtocolsForAccessionVarOcx = studyProtocolsForAccessionVarOcx;
	}

	public Set<MenuItem> getMenuItems() {
		return this.menuItems;
	}

	public void setMenuItems(Set<MenuItem> menuItems) {
		this.menuItems = menuItems;
	}

	public Set<FunctionalStep> getFunctionalSteps() {
		return this.functionalSteps;
	}

	public void setFunctionalSteps(Set<FunctionalStep> functionalSteps) {
		this.functionalSteps = functionalSteps;
	}

	public Set<StudyProtocol> getStudyProtocolsForStudyVarOcx() {
		return this.studyProtocolsForStudyVarOcx;
	}

	public void setStudyProtocolsForStudyVarOcx(
			Set<StudyProtocol> studyProtocolsForStudyVarOcx) {
		this.studyProtocolsForStudyVarOcx = studyProtocolsForStudyVarOcx;
	}

	public Set<ParentMenu> getParentMenus() {
		return this.parentMenus;
	}

	public void setParentMenus(Set<ParentMenu> parentMenus) {
		this.parentMenus = parentMenus;
	}

	public Set<StudyProtocol> getStudyProtocolsForPatientVarOcx() {
		return this.studyProtocolsForPatientVarOcx;
	}

	public void setStudyProtocolsForPatientVarOcx(
			Set<StudyProtocol> studyProtocolsForPatientVarOcx) {
		this.studyProtocolsForPatientVarOcx = studyProtocolsForPatientVarOcx;
	}

}
