package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * OligoMixtureDesign generated by hbm2java
 */
public class OligoMixtureDesign implements java.io.Serializable {

	private BigDecimal mixtureId;
	private OligoDesign oligoDesignByOligoMixtureId;
	private OligoDesign oligoDesignByOligoId;
	private BigDecimal volume;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;

	public OligoMixtureDesign() {
	}

	public OligoMixtureDesign(BigDecimal mixtureId, String createdBy,
			Date dateCreated) {
		this.mixtureId = mixtureId;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public OligoMixtureDesign(BigDecimal mixtureId,
			OligoDesign oligoDesignByOligoMixtureId,
			OligoDesign oligoDesignByOligoId, BigDecimal volume,
			String createdBy, Date dateCreated, String modifiedBy,
			Date dateModified) {
		this.mixtureId = mixtureId;
		this.oligoDesignByOligoMixtureId = oligoDesignByOligoMixtureId;
		this.oligoDesignByOligoId = oligoDesignByOligoId;
		this.volume = volume;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
	}

	public BigDecimal getMixtureId() {
		return this.mixtureId;
	}

	public void setMixtureId(BigDecimal mixtureId) {
		this.mixtureId = mixtureId;
	}

	public OligoDesign getOligoDesignByOligoMixtureId() {
		return this.oligoDesignByOligoMixtureId;
	}

	public void setOligoDesignByOligoMixtureId(
			OligoDesign oligoDesignByOligoMixtureId) {
		this.oligoDesignByOligoMixtureId = oligoDesignByOligoMixtureId;
	}

	public OligoDesign getOligoDesignByOligoId() {
		return this.oligoDesignByOligoId;
	}

	public void setOligoDesignByOligoId(OligoDesign oligoDesignByOligoId) {
		this.oligoDesignByOligoId = oligoDesignByOligoId;
	}

	public BigDecimal getVolume() {
		return this.volume;
	}

	public void setVolume(BigDecimal volume) {
		this.volume = volume;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
