package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PgxModifiedGeneTemplate generated by hbm2java
 */
public class PgxModifiedGeneTemplate implements java.io.Serializable {

	private BigDecimal geneModificationId;
	private PgxDataReport pgxDataReport;
	private Subsidiary subsidiary;
	private Gene gene;
	private String createdBy;
	private Date dateCreated;

	public PgxModifiedGeneTemplate() {
	}

	public PgxModifiedGeneTemplate(BigDecimal geneModificationId,
			PgxDataReport pgxDataReport, Gene gene, String createdBy,
			Date dateCreated) {
		this.geneModificationId = geneModificationId;
		this.pgxDataReport = pgxDataReport;
		this.gene = gene;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public PgxModifiedGeneTemplate(BigDecimal geneModificationId,
			PgxDataReport pgxDataReport, Subsidiary subsidiary, Gene gene,
			String createdBy, Date dateCreated) {
		this.geneModificationId = geneModificationId;
		this.pgxDataReport = pgxDataReport;
		this.subsidiary = subsidiary;
		this.gene = gene;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public BigDecimal getGeneModificationId() {
		return this.geneModificationId;
	}

	public void setGeneModificationId(BigDecimal geneModificationId) {
		this.geneModificationId = geneModificationId;
	}

	public PgxDataReport getPgxDataReport() {
		return this.pgxDataReport;
	}

	public void setPgxDataReport(PgxDataReport pgxDataReport) {
		this.pgxDataReport = pgxDataReport;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public Gene getGene() {
		return this.gene;
	}

	public void setGene(Gene gene) {
		this.gene = gene;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
