package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * PgxPatientDataReport generated by hbm2java
 */
public class PgxPatientDataReport implements java.io.Serializable {

	private BigDecimal pgxPatientId;
	private Patient patient;
	private PgxDataReport pgxDataReport;
	private Subsidiary subsidiary;

	public PgxPatientDataReport() {
	}

	public PgxPatientDataReport(BigDecimal pgxPatientId,
			PgxDataReport pgxDataReport) {
		this.pgxPatientId = pgxPatientId;
		this.pgxDataReport = pgxDataReport;
	}

	public PgxPatientDataReport(BigDecimal pgxPatientId, Patient patient,
			PgxDataReport pgxDataReport, Subsidiary subsidiary) {
		this.pgxPatientId = pgxPatientId;
		this.patient = patient;
		this.pgxDataReport = pgxDataReport;
		this.subsidiary = subsidiary;
	}

	public BigDecimal getPgxPatientId() {
		return this.pgxPatientId;
	}

	public void setPgxPatientId(BigDecimal pgxPatientId) {
		this.pgxPatientId = pgxPatientId;
	}

	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public PgxDataReport getPgxDataReport() {
		return this.pgxDataReport;
	}

	public void setPgxDataReport(PgxDataReport pgxDataReport) {
		this.pgxDataReport = pgxDataReport;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

}
