package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PhenotypeAutocallRule generated by hbm2java
 */
public class PhenotypeAutocallRule implements java.io.Serializable {

	private BigDecimal phenotypeAutocallRuleId;
	private GeneInterprDefinition geneInterprDefinition;
	private Subsidiary subsidiary;
	private Gene gene;
	private String geneResult;
	private BigDecimal isValid;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;

	public PhenotypeAutocallRule() {
	}

	public PhenotypeAutocallRule(BigDecimal phenotypeAutocallRuleId,
			GeneInterprDefinition geneInterprDefinition, Gene gene,
			String geneResult) {
		this.phenotypeAutocallRuleId = phenotypeAutocallRuleId;
		this.geneInterprDefinition = geneInterprDefinition;
		this.gene = gene;
		this.geneResult = geneResult;
	}

	public PhenotypeAutocallRule(BigDecimal phenotypeAutocallRuleId,
			GeneInterprDefinition geneInterprDefinition, Subsidiary subsidiary,
			Gene gene, String geneResult, BigDecimal isValid, String createdBy,
			Date dateCreated, String modifiedBy, Date dateModified) {
		this.phenotypeAutocallRuleId = phenotypeAutocallRuleId;
		this.geneInterprDefinition = geneInterprDefinition;
		this.subsidiary = subsidiary;
		this.gene = gene;
		this.geneResult = geneResult;
		this.isValid = isValid;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
	}

	public BigDecimal getPhenotypeAutocallRuleId() {
		return this.phenotypeAutocallRuleId;
	}

	public void setPhenotypeAutocallRuleId(BigDecimal phenotypeAutocallRuleId) {
		this.phenotypeAutocallRuleId = phenotypeAutocallRuleId;
	}

	public GeneInterprDefinition getGeneInterprDefinition() {
		return this.geneInterprDefinition;
	}

	public void setGeneInterprDefinition(
			GeneInterprDefinition geneInterprDefinition) {
		this.geneInterprDefinition = geneInterprDefinition;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public Gene getGene() {
		return this.gene;
	}

	public void setGene(Gene gene) {
		this.gene = gene;
	}

	public String getGeneResult() {
		return this.geneResult;
	}

	public void setGeneResult(String geneResult) {
		this.geneResult = geneResult;
	}

	public BigDecimal getIsValid() {
		return this.isValid;
	}

	public void setIsValid(BigDecimal isValid) {
		this.isValid = isValid;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
