package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * PlateTemplateWellId generated by hbm2java
 */
public class PlateTemplateWellId implements java.io.Serializable {

	private BigDecimal plateTemplateId;
	private BigDecimal plateRow;
	private BigDecimal plateColumn;

	public PlateTemplateWellId() {
	}

	public PlateTemplateWellId(BigDecimal plateTemplateId, BigDecimal plateRow,
			BigDecimal plateColumn) {
		this.plateTemplateId = plateTemplateId;
		this.plateRow = plateRow;
		this.plateColumn = plateColumn;
	}

	public BigDecimal getPlateTemplateId() {
		return this.plateTemplateId;
	}

	public void setPlateTemplateId(BigDecimal plateTemplateId) {
		this.plateTemplateId = plateTemplateId;
	}

	public BigDecimal getPlateRow() {
		return this.plateRow;
	}

	public void setPlateRow(BigDecimal plateRow) {
		this.plateRow = plateRow;
	}

	public BigDecimal getPlateColumn() {
		return this.plateColumn;
	}

	public void setPlateColumn(BigDecimal plateColumn) {
		this.plateColumn = plateColumn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlateTemplateWellId))
			return false;
		PlateTemplateWellId castOther = (PlateTemplateWellId) other;

		return ((this.getPlateTemplateId() == castOther.getPlateTemplateId()) || (this
				.getPlateTemplateId() != null
				&& castOther.getPlateTemplateId() != null && this
				.getPlateTemplateId().equals(castOther.getPlateTemplateId())))
				&& ((this.getPlateRow() == castOther.getPlateRow()) || (this
						.getPlateRow() != null
						&& castOther.getPlateRow() != null && this
						.getPlateRow().equals(castOther.getPlateRow())))
				&& ((this.getPlateColumn() == castOther.getPlateColumn()) || (this
						.getPlateColumn() != null
						&& castOther.getPlateColumn() != null && this
						.getPlateColumn().equals(castOther.getPlateColumn())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPlateTemplateId() == null ? 0 : this.getPlateTemplateId()
						.hashCode());
		result = 37 * result
				+ (getPlateRow() == null ? 0 : this.getPlateRow().hashCode());
		result = 37
				* result
				+ (getPlateColumn() == null ? 0 : this.getPlateColumn()
						.hashCode());
		return result;
	}

}
