package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PlateTemplate generated by hbm2java
 */
public class PlateTemplate implements java.io.Serializable {

	private BigDecimal plateTemplateId;
	private Subsidiary subsidiary;
	private ContainerMap containerMap;
	private String templateName;
	private String description;
	private Boolean rowFirst;
	private String createdBy;
	private Date dateCreated;
	private String templateType;
	private Set<PlateTemplateWell> plateTemplateWells = new HashSet<PlateTemplateWell>(
			0);
	private Set<ContainerBatch> containerBatchs = new HashSet<ContainerBatch>(0);
	private Set<OligoPlateTemplateDesign> oligoPlateTemplateDesigns = new HashSet<OligoPlateTemplateDesign>(
			0);
	private Set<PlateTemplateContainer> plateTemplateContainers = new HashSet<PlateTemplateContainer>(
			0);

	public PlateTemplate() {
	}

	public PlateTemplate(BigDecimal plateTemplateId, ContainerMap containerMap,
			String templateName) {
		this.plateTemplateId = plateTemplateId;
		this.containerMap = containerMap;
		this.templateName = templateName;
	}

	public PlateTemplate(BigDecimal plateTemplateId, Subsidiary subsidiary,
			ContainerMap containerMap, String templateName, String description,
			Boolean rowFirst, String createdBy, Date dateCreated,
			String templateType, Set<PlateTemplateWell> plateTemplateWells,
			Set<ContainerBatch> containerBatchs,
			Set<OligoPlateTemplateDesign> oligoPlateTemplateDesigns,
			Set<PlateTemplateContainer> plateTemplateContainers) {
		this.plateTemplateId = plateTemplateId;
		this.subsidiary = subsidiary;
		this.containerMap = containerMap;
		this.templateName = templateName;
		this.description = description;
		this.rowFirst = rowFirst;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.templateType = templateType;
		this.plateTemplateWells = plateTemplateWells;
		this.containerBatchs = containerBatchs;
		this.oligoPlateTemplateDesigns = oligoPlateTemplateDesigns;
		this.plateTemplateContainers = plateTemplateContainers;
	}

	public BigDecimal getPlateTemplateId() {
		return this.plateTemplateId;
	}

	public void setPlateTemplateId(BigDecimal plateTemplateId) {
		this.plateTemplateId = plateTemplateId;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public ContainerMap getContainerMap() {
		return this.containerMap;
	}

	public void setContainerMap(ContainerMap containerMap) {
		this.containerMap = containerMap;
	}

	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getRowFirst() {
		return this.rowFirst;
	}

	public void setRowFirst(Boolean rowFirst) {
		this.rowFirst = rowFirst;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getTemplateType() {
		return this.templateType;
	}

	public void setTemplateType(String templateType) {
		this.templateType = templateType;
	}

	public Set<PlateTemplateWell> getPlateTemplateWells() {
		return this.plateTemplateWells;
	}

	public void setPlateTemplateWells(Set<PlateTemplateWell> plateTemplateWells) {
		this.plateTemplateWells = plateTemplateWells;
	}

	public Set<ContainerBatch> getContainerBatchs() {
		return this.containerBatchs;
	}

	public void setContainerBatchs(Set<ContainerBatch> containerBatchs) {
		this.containerBatchs = containerBatchs;
	}

	public Set<OligoPlateTemplateDesign> getOligoPlateTemplateDesigns() {
		return this.oligoPlateTemplateDesigns;
	}

	public void setOligoPlateTemplateDesigns(
			Set<OligoPlateTemplateDesign> oligoPlateTemplateDesigns) {
		this.oligoPlateTemplateDesigns = oligoPlateTemplateDesigns;
	}

	public Set<PlateTemplateContainer> getPlateTemplateContainers() {
		return this.plateTemplateContainers;
	}

	public void setPlateTemplateContainers(
			Set<PlateTemplateContainer> plateTemplateContainers) {
		this.plateTemplateContainers = plateTemplateContainers;
	}

}
