package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ProcedureTemplateR generated by hbm2java
 */
public class ProcedureTemplateR implements java.io.Serializable {

	private ProcedureTemplateRId id;
	private BigDecimal databaseId;

	public ProcedureTemplateR() {
	}

	public ProcedureTemplateR(ProcedureTemplateRId id) {
		this.id = id;
	}

	public ProcedureTemplateR(ProcedureTemplateRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public ProcedureTemplateRId getId() {
		return this.id;
	}

	public void setId(ProcedureTemplateRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
