package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ProcedureTemplateAlleleId generated by hbm2java
 */
public class ProcedureTemplateAlleleId implements java.io.Serializable {

	private BigDecimal procedureTemplateId;
	private BigDecimal alleleId;
	private BigDecimal numberInSequence;

	public ProcedureTemplateAlleleId() {
	}

	public ProcedureTemplateAlleleId(BigDecimal procedureTemplateId,
			BigDecimal alleleId, BigDecimal numberInSequence) {
		this.procedureTemplateId = procedureTemplateId;
		this.alleleId = alleleId;
		this.numberInSequence = numberInSequence;
	}

	public BigDecimal getProcedureTemplateId() {
		return this.procedureTemplateId;
	}

	public void setProcedureTemplateId(BigDecimal procedureTemplateId) {
		this.procedureTemplateId = procedureTemplateId;
	}

	public BigDecimal getAlleleId() {
		return this.alleleId;
	}

	public void setAlleleId(BigDecimal alleleId) {
		this.alleleId = alleleId;
	}

	public BigDecimal getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(BigDecimal numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcedureTemplateAlleleId))
			return false;
		ProcedureTemplateAlleleId castOther = (ProcedureTemplateAlleleId) other;

		return ((this.getProcedureTemplateId() == castOther
				.getProcedureTemplateId()) || (this.getProcedureTemplateId() != null
				&& castOther.getProcedureTemplateId() != null && this
				.getProcedureTemplateId().equals(
						castOther.getProcedureTemplateId())))
				&& ((this.getAlleleId() == castOther.getAlleleId()) || (this
						.getAlleleId() != null
						&& castOther.getAlleleId() != null && this
						.getAlleleId().equals(castOther.getAlleleId())))
				&& ((this.getNumberInSequence() == castOther
						.getNumberInSequence()) || (this.getNumberInSequence() != null
						&& castOther.getNumberInSequence() != null && this
						.getNumberInSequence().equals(
								castOther.getNumberInSequence())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProcedureTemplateId() == null ? 0 : this
						.getProcedureTemplateId().hashCode());
		result = 37 * result
				+ (getAlleleId() == null ? 0 : this.getAlleleId().hashCode());
		result = 37
				* result
				+ (getNumberInSequence() == null ? 0 : this
						.getNumberInSequence().hashCode());
		return result;
	}

}
