package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ProtocolProcedure generated by hbm2java
 */
public class ProtocolProcedure implements java.io.Serializable {

	private ProtocolProcedureId id;
	private ProcedureTemplate procedureTemplate;
	private StudyProtocol studyProtocol;
	private Subsidiary subsidiary;
	private BigDecimal turnAroundTime;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;

	public ProtocolProcedure() {
	}

	public ProtocolProcedure(ProtocolProcedureId id,
			ProcedureTemplate procedureTemplate, StudyProtocol studyProtocol) {
		this.id = id;
		this.procedureTemplate = procedureTemplate;
		this.studyProtocol = studyProtocol;
	}

	public ProtocolProcedure(ProtocolProcedureId id,
			ProcedureTemplate procedureTemplate, StudyProtocol studyProtocol,
			Subsidiary subsidiary, BigDecimal turnAroundTime, String createdBy,
			Date dateCreated, String modifiedBy, Date dateModified) {
		this.id = id;
		this.procedureTemplate = procedureTemplate;
		this.studyProtocol = studyProtocol;
		this.subsidiary = subsidiary;
		this.turnAroundTime = turnAroundTime;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
	}

	public ProtocolProcedureId getId() {
		return this.id;
	}

	public void setId(ProtocolProcedureId id) {
		this.id = id;
	}

	public ProcedureTemplate getProcedureTemplate() {
		return this.procedureTemplate;
	}

	public void setProcedureTemplate(ProcedureTemplate procedureTemplate) {
		this.procedureTemplate = procedureTemplate;
	}

	public StudyProtocol getStudyProtocol() {
		return this.studyProtocol;
	}

	public void setStudyProtocol(StudyProtocol studyProtocol) {
		this.studyProtocol = studyProtocol;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public BigDecimal getTurnAroundTime() {
		return this.turnAroundTime;
	}

	public void setTurnAroundTime(BigDecimal turnAroundTime) {
		this.turnAroundTime = turnAroundTime;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
