package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ProtocolGeneValueId generated by hbm2java
 */
public class ProtocolGeneValueId implements java.io.Serializable {

	private BigDecimal protocolGeneId;
	private BigDecimal numberInSequence;

	public ProtocolGeneValueId() {
	}

	public ProtocolGeneValueId(BigDecimal protocolGeneId,
			BigDecimal numberInSequence) {
		this.protocolGeneId = protocolGeneId;
		this.numberInSequence = numberInSequence;
	}

	public BigDecimal getProtocolGeneId() {
		return this.protocolGeneId;
	}

	public void setProtocolGeneId(BigDecimal protocolGeneId) {
		this.protocolGeneId = protocolGeneId;
	}

	public BigDecimal getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(BigDecimal numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProtocolGeneValueId))
			return false;
		ProtocolGeneValueId castOther = (ProtocolGeneValueId) other;

		return ((this.getProtocolGeneId() == castOther.getProtocolGeneId()) || (this
				.getProtocolGeneId() != null
				&& castOther.getProtocolGeneId() != null && this
				.getProtocolGeneId().equals(castOther.getProtocolGeneId())))
				&& ((this.getNumberInSequence() == castOther
						.getNumberInSequence()) || (this.getNumberInSequence() != null
						&& castOther.getNumberInSequence() != null && this
						.getNumberInSequence().equals(
								castOther.getNumberInSequence())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProtocolGeneId() == null ? 0 : this.getProtocolGeneId()
						.hashCode());
		result = 37
				* result
				+ (getNumberInSequence() == null ? 0 : this
						.getNumberInSequence().hashCode());
		return result;
	}

}
