package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReportTemplate generated by hbm2java
 */
public class ReportTemplate implements java.io.Serializable {

	private BigDecimal templateId;
	private PgxSetupTemplate pgxSetupTemplate;
	private String templateName;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal subsidiaryId;
	private BigDecimal setupTemplateId;
	private Set<ReportTemplateParam> reportTemplateParams = new HashSet<ReportTemplateParam>(
			0);

	public ReportTemplate() {
	}

	public ReportTemplate(BigDecimal templateId,
			PgxSetupTemplate pgxSetupTemplate, String templateName) {
		this.templateId = templateId;
		this.pgxSetupTemplate = pgxSetupTemplate;
		this.templateName = templateName;
	}

	public ReportTemplate(BigDecimal templateId,
			PgxSetupTemplate pgxSetupTemplate, String templateName,
			String createdBy, Date dateCreated, String modifiedBy,
			Date dateModified, BigDecimal subsidiaryId,
			BigDecimal setupTemplateId,
			Set<ReportTemplateParam> reportTemplateParams) {
		this.templateId = templateId;
		this.pgxSetupTemplate = pgxSetupTemplate;
		this.templateName = templateName;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.subsidiaryId = subsidiaryId;
		this.setupTemplateId = setupTemplateId;
		this.reportTemplateParams = reportTemplateParams;
	}

	public BigDecimal getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(BigDecimal templateId) {
		this.templateId = templateId;
	}

	public PgxSetupTemplate getPgxSetupTemplate() {
		return this.pgxSetupTemplate;
	}

	public void setPgxSetupTemplate(PgxSetupTemplate pgxSetupTemplate) {
		this.pgxSetupTemplate = pgxSetupTemplate;
	}

	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getSetupTemplateId() {
		return this.setupTemplateId;
	}

	public void setSetupTemplateId(BigDecimal setupTemplateId) {
		this.setupTemplateId = setupTemplateId;
	}

	public Set<ReportTemplateParam> getReportTemplateParams() {
		return this.reportTemplateParams;
	}

	public void setReportTemplateParams(
			Set<ReportTemplateParam> reportTemplateParams) {
		this.reportTemplateParams = reportTemplateParams;
	}

}
