package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * RequestPurpose generated by hbm2java
 */
public class RequestPurpose implements java.io.Serializable {

	private BigDecimal requestPurposeId;
	private SpecimenRequest specimenRequest;
	private String purpose;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal subsidiaryId;

	public RequestPurpose() {
	}

	public RequestPurpose(BigDecimal requestPurposeId) {
		this.requestPurposeId = requestPurposeId;
	}

	public RequestPurpose(BigDecimal requestPurposeId,
			SpecimenRequest specimenRequest, String purpose, String createdBy,
			Date dateCreated, String modifiedBy, Date dateModified,
			BigDecimal subsidiaryId) {
		this.requestPurposeId = requestPurposeId;
		this.specimenRequest = specimenRequest;
		this.purpose = purpose;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getRequestPurposeId() {
		return this.requestPurposeId;
	}

	public void setRequestPurposeId(BigDecimal requestPurposeId) {
		this.requestPurposeId = requestPurposeId;
	}

	public SpecimenRequest getSpecimenRequest() {
		return this.specimenRequest;
	}

	public void setSpecimenRequest(SpecimenRequest specimenRequest) {
		this.specimenRequest = specimenRequest;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
