package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Review generated by hbm2java
 */
public class Review implements java.io.Serializable {

	private BigDecimal reviewId;
	private Checklist checklist;
	private Subsidiary subsidiary;
	private String reviewName;
	private String reviewNotes;
	private String username;
	private String rolename;
	private String md5digest;
	private BigDecimal checklistRow;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;

	public Review() {
	}

	public Review(BigDecimal reviewId, String createdBy, Date dateCreated) {
		this.reviewId = reviewId;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public Review(BigDecimal reviewId, Checklist checklist,
			Subsidiary subsidiary, String reviewName, String reviewNotes,
			String username, String rolename, String md5digest,
			BigDecimal checklistRow, String createdBy, Date dateCreated,
			String modifiedBy, Date dateModified) {
		this.reviewId = reviewId;
		this.checklist = checklist;
		this.subsidiary = subsidiary;
		this.reviewName = reviewName;
		this.reviewNotes = reviewNotes;
		this.username = username;
		this.rolename = rolename;
		this.md5digest = md5digest;
		this.checklistRow = checklistRow;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
	}

	public BigDecimal getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(BigDecimal reviewId) {
		this.reviewId = reviewId;
	}

	public Checklist getChecklist() {
		return this.checklist;
	}

	public void setChecklist(Checklist checklist) {
		this.checklist = checklist;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public String getReviewName() {
		return this.reviewName;
	}

	public void setReviewName(String reviewName) {
		this.reviewName = reviewName;
	}

	public String getReviewNotes() {
		return this.reviewNotes;
	}

	public void setReviewNotes(String reviewNotes) {
		this.reviewNotes = reviewNotes;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public String getMd5digest() {
		return this.md5digest;
	}

	public void setMd5digest(String md5digest) {
		this.md5digest = md5digest;
	}

	public BigDecimal getChecklistRow() {
		return this.checklistRow;
	}

	public void setChecklistRow(BigDecimal checklistRow) {
		this.checklistRow = checklistRow;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

}
