package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SampleIdentificationKeyId generated by hbm2java
 */
public class SampleIdentificationKeyId implements java.io.Serializable {

	private BigDecimal sampleId;
	private BigDecimal anonymizationLogId;
	private BigDecimal anonymizationRequestId;
	private BigDecimal anonymizationStudySetupId;
	private BigDecimal accessionId;
	private BigDecimal studyProtocolId;
	private String identifiedSampleId;
	private Boolean isEncrypted;
	private BigDecimal subsidiaryId;

	public SampleIdentificationKeyId() {
	}

	public SampleIdentificationKeyId(BigDecimal sampleId,
			BigDecimal anonymizationLogId, BigDecimal anonymizationRequestId,
			BigDecimal anonymizationStudySetupId, BigDecimal accessionId,
			BigDecimal studyProtocolId, String identifiedSampleId,
			Boolean isEncrypted, BigDecimal subsidiaryId) {
		this.sampleId = sampleId;
		this.anonymizationLogId = anonymizationLogId;
		this.anonymizationRequestId = anonymizationRequestId;
		this.anonymizationStudySetupId = anonymizationStudySetupId;
		this.accessionId = accessionId;
		this.studyProtocolId = studyProtocolId;
		this.identifiedSampleId = identifiedSampleId;
		this.isEncrypted = isEncrypted;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getSampleId() {
		return this.sampleId;
	}

	public void setSampleId(BigDecimal sampleId) {
		this.sampleId = sampleId;
	}

	public BigDecimal getAnonymizationLogId() {
		return this.anonymizationLogId;
	}

	public void setAnonymizationLogId(BigDecimal anonymizationLogId) {
		this.anonymizationLogId = anonymizationLogId;
	}

	public BigDecimal getAnonymizationRequestId() {
		return this.anonymizationRequestId;
	}

	public void setAnonymizationRequestId(BigDecimal anonymizationRequestId) {
		this.anonymizationRequestId = anonymizationRequestId;
	}

	public BigDecimal getAnonymizationStudySetupId() {
		return this.anonymizationStudySetupId;
	}

	public void setAnonymizationStudySetupId(
			BigDecimal anonymizationStudySetupId) {
		this.anonymizationStudySetupId = anonymizationStudySetupId;
	}

	public BigDecimal getAccessionId() {
		return this.accessionId;
	}

	public void setAccessionId(BigDecimal accessionId) {
		this.accessionId = accessionId;
	}

	public BigDecimal getStudyProtocolId() {
		return this.studyProtocolId;
	}

	public void setStudyProtocolId(BigDecimal studyProtocolId) {
		this.studyProtocolId = studyProtocolId;
	}

	public String getIdentifiedSampleId() {
		return this.identifiedSampleId;
	}

	public void setIdentifiedSampleId(String identifiedSampleId) {
		this.identifiedSampleId = identifiedSampleId;
	}

	public Boolean getIsEncrypted() {
		return this.isEncrypted;
	}

	public void setIsEncrypted(Boolean isEncrypted) {
		this.isEncrypted = isEncrypted;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SampleIdentificationKeyId))
			return false;
		SampleIdentificationKeyId castOther = (SampleIdentificationKeyId) other;

		return ((this.getSampleId() == castOther.getSampleId()) || (this
				.getSampleId() != null && castOther.getSampleId() != null && this
				.getSampleId().equals(castOther.getSampleId())))
				&& ((this.getAnonymizationLogId() == castOther
						.getAnonymizationLogId()) || (this
						.getAnonymizationLogId() != null
						&& castOther.getAnonymizationLogId() != null && this
						.getAnonymizationLogId().equals(
								castOther.getAnonymizationLogId())))
				&& ((this.getAnonymizationRequestId() == castOther
						.getAnonymizationRequestId()) || (this
						.getAnonymizationRequestId() != null
						&& castOther.getAnonymizationRequestId() != null && this
						.getAnonymizationRequestId().equals(
								castOther.getAnonymizationRequestId())))
				&& ((this.getAnonymizationStudySetupId() == castOther
						.getAnonymizationStudySetupId()) || (this
						.getAnonymizationStudySetupId() != null
						&& castOther.getAnonymizationStudySetupId() != null && this
						.getAnonymizationStudySetupId().equals(
								castOther.getAnonymizationStudySetupId())))
				&& ((this.getAccessionId() == castOther.getAccessionId()) || (this
						.getAccessionId() != null
						&& castOther.getAccessionId() != null && this
						.getAccessionId().equals(castOther.getAccessionId())))
				&& ((this.getStudyProtocolId() == castOther
						.getStudyProtocolId()) || (this.getStudyProtocolId() != null
						&& castOther.getStudyProtocolId() != null && this
						.getStudyProtocolId().equals(
								castOther.getStudyProtocolId())))
				&& ((this.getIdentifiedSampleId() == castOther
						.getIdentifiedSampleId()) || (this
						.getIdentifiedSampleId() != null
						&& castOther.getIdentifiedSampleId() != null && this
						.getIdentifiedSampleId().equals(
								castOther.getIdentifiedSampleId())))
				&& ((this.getIsEncrypted() == castOther.getIsEncrypted()) || (this
						.getIsEncrypted() != null
						&& castOther.getIsEncrypted() != null && this
						.getIsEncrypted().equals(castOther.getIsEncrypted())))
				&& ((this.getSubsidiaryId() == castOther.getSubsidiaryId()) || (this
						.getSubsidiaryId() != null
						&& castOther.getSubsidiaryId() != null && this
						.getSubsidiaryId().equals(castOther.getSubsidiaryId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSampleId() == null ? 0 : this.getSampleId().hashCode());
		result = 37
				* result
				+ (getAnonymizationLogId() == null ? 0 : this
						.getAnonymizationLogId().hashCode());
		result = 37
				* result
				+ (getAnonymizationRequestId() == null ? 0 : this
						.getAnonymizationRequestId().hashCode());
		result = 37
				* result
				+ (getAnonymizationStudySetupId() == null ? 0 : this
						.getAnonymizationStudySetupId().hashCode());
		result = 37
				* result
				+ (getAccessionId() == null ? 0 : this.getAccessionId()
						.hashCode());
		result = 37
				* result
				+ (getStudyProtocolId() == null ? 0 : this.getStudyProtocolId()
						.hashCode());
		result = 37
				* result
				+ (getIdentifiedSampleId() == null ? 0 : this
						.getIdentifiedSampleId().hashCode());
		result = 37
				* result
				+ (getIsEncrypted() == null ? 0 : this.getIsEncrypted()
						.hashCode());
		result = 37
				* result
				+ (getSubsidiaryId() == null ? 0 : this.getSubsidiaryId()
						.hashCode());
		return result;
	}

}
