package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ScreenAccessR generated by hbm2java
 */
public class ScreenAccessR implements java.io.Serializable {

	private ScreenAccessRId id;
	private BigDecimal databaseId;

	public ScreenAccessR() {
	}

	public ScreenAccessR(ScreenAccessRId id) {
		this.id = id;
	}

	public ScreenAccessR(ScreenAccessRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public ScreenAccessRId getId() {
		return this.id;
	}

	public void setId(ScreenAccessRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
