package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SeqSetup generated by hbm2java
 */
public class SeqSetup implements java.io.Serializable {

	private BigDecimal seqSetupId;
	private StepTemplate stepTemplate;
	private Checklist checklist;
	private Instrument instrument;
	private String scriptGenerated;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal subsidiaryId;
	private Set<SeqSetupContainer> seqSetupContainers = new HashSet<SeqSetupContainer>(
			0);

	public SeqSetup() {
	}

	public SeqSetup(BigDecimal seqSetupId) {
		this.seqSetupId = seqSetupId;
	}

	public SeqSetup(BigDecimal seqSetupId, StepTemplate stepTemplate,
			Checklist checklist, Instrument instrument, String scriptGenerated,
			String createdBy, Date dateCreated, String modifiedBy,
			Date dateModified, BigDecimal subsidiaryId,
			Set<SeqSetupContainer> seqSetupContainers) {
		this.seqSetupId = seqSetupId;
		this.stepTemplate = stepTemplate;
		this.checklist = checklist;
		this.instrument = instrument;
		this.scriptGenerated = scriptGenerated;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.subsidiaryId = subsidiaryId;
		this.seqSetupContainers = seqSetupContainers;
	}

	public BigDecimal getSeqSetupId() {
		return this.seqSetupId;
	}

	public void setSeqSetupId(BigDecimal seqSetupId) {
		this.seqSetupId = seqSetupId;
	}

	public StepTemplate getStepTemplate() {
		return this.stepTemplate;
	}

	public void setStepTemplate(StepTemplate stepTemplate) {
		this.stepTemplate = stepTemplate;
	}

	public Checklist getChecklist() {
		return this.checklist;
	}

	public void setChecklist(Checklist checklist) {
		this.checklist = checklist;
	}

	public Instrument getInstrument() {
		return this.instrument;
	}

	public void setInstrument(Instrument instrument) {
		this.instrument = instrument;
	}

	public String getScriptGenerated() {
		return this.scriptGenerated;
	}

	public void setScriptGenerated(String scriptGenerated) {
		this.scriptGenerated = scriptGenerated;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

	public Set<SeqSetupContainer> getSeqSetupContainers() {
		return this.seqSetupContainers;
	}

	public void setSeqSetupContainers(Set<SeqSetupContainer> seqSetupContainers) {
		this.seqSetupContainers = seqSetupContainers;
	}

}
