package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ShipmentAirbillR generated by hbm2java
 */
public class ShipmentAirbillR implements java.io.Serializable {

	private ShipmentAirbillRId id;
	private BigDecimal databaseId;

	public ShipmentAirbillR() {
	}

	public ShipmentAirbillR(ShipmentAirbillRId id) {
		this.id = id;
	}

	public ShipmentAirbillR(ShipmentAirbillRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public ShipmentAirbillRId getId() {
		return this.id;
	}

	public void setId(ShipmentAirbillRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
