package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SpecimenShipmentR generated by hbm2java
 */
public class SpecimenShipmentR implements java.io.Serializable {

	private SpecimenShipmentRId id;
	private BigDecimal databaseId;

	public SpecimenShipmentR() {
	}

	public SpecimenShipmentR(SpecimenShipmentRId id) {
		this.id = id;
	}

	public SpecimenShipmentR(SpecimenShipmentRId id, BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public SpecimenShipmentRId getId() {
		return this.id;
	}

	public void setId(SpecimenShipmentRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
