package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SpecimenShipmentAirbillR generated by hbm2java
 */
public class SpecimenShipmentAirbillR implements java.io.Serializable {

	private SpecimenShipmentAirbillRId id;
	private BigDecimal databaseId;

	public SpecimenShipmentAirbillR() {
	}

	public SpecimenShipmentAirbillR(SpecimenShipmentAirbillRId id) {
		this.id = id;
	}

	public SpecimenShipmentAirbillR(SpecimenShipmentAirbillRId id,
			BigDecimal databaseId) {
		this.id = id;
		this.databaseId = databaseId;
	}

	public SpecimenShipmentAirbillRId getId() {
		return this.id;
	}

	public void setId(SpecimenShipmentAirbillRId id) {
		this.id = id;
	}

	public BigDecimal getDatabaseId() {
		return this.databaseId;
	}

	public void setDatabaseId(BigDecimal databaseId) {
		this.databaseId = databaseId;
	}

}
