package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TraceTransferAttribute generated by hbm2java
 */
public class TraceTransferAttribute implements java.io.Serializable {

	private BigDecimal traceTrfAttrbId;
	private TraceTransfer traceTransfer;
	private String tagName;
	private String tagValue;
	private String createdBy;
	private Date dateCreated;
	private String modifiedBy;
	private Date dateModified;
	private BigDecimal subsidiaryId;

	public TraceTransferAttribute() {
	}

	public TraceTransferAttribute(BigDecimal traceTrfAttrbId) {
		this.traceTrfAttrbId = traceTrfAttrbId;
	}

	public TraceTransferAttribute(BigDecimal traceTrfAttrbId,
			TraceTransfer traceTransfer, String tagName, String tagValue,
			String createdBy, Date dateCreated, String modifiedBy,
			Date dateModified, BigDecimal subsidiaryId) {
		this.traceTrfAttrbId = traceTrfAttrbId;
		this.traceTransfer = traceTransfer;
		this.tagName = tagName;
		this.tagValue = tagValue;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.modifiedBy = modifiedBy;
		this.dateModified = dateModified;
		this.subsidiaryId = subsidiaryId;
	}

	public BigDecimal getTraceTrfAttrbId() {
		return this.traceTrfAttrbId;
	}

	public void setTraceTrfAttrbId(BigDecimal traceTrfAttrbId) {
		this.traceTrfAttrbId = traceTrfAttrbId;
	}

	public TraceTransfer getTraceTransfer() {
		return this.traceTransfer;
	}

	public void setTraceTransfer(TraceTransfer traceTransfer) {
		this.traceTransfer = traceTransfer;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	public String getTagValue() {
		return this.tagValue;
	}

	public void setTagValue(String tagValue) {
		this.tagValue = tagValue;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	public BigDecimal getSubsidiaryId() {
		return this.subsidiaryId;
	}

	public void setSubsidiaryId(BigDecimal subsidiaryId) {
		this.subsidiaryId = subsidiaryId;
	}

}
