package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserSubsidiary generated by hbm2java
 */
public class UserSubsidiary implements java.io.Serializable {

	private UserSubsidiaryId id;
	private Subsidiary subsidiary;
	private String createdBy;
	private Date dateCreated;

	public UserSubsidiary() {
	}

	public UserSubsidiary(UserSubsidiaryId id, Subsidiary subsidiary) {
		this.id = id;
		this.subsidiary = subsidiary;
	}

	public UserSubsidiary(UserSubsidiaryId id, Subsidiary subsidiary,
			String createdBy, Date dateCreated) {
		this.id = id;
		this.subsidiary = subsidiary;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
	}

	public UserSubsidiaryId getId() {
		return this.id;
	}

	public void setId(UserSubsidiaryId id) {
		this.id = id;
	}

	public Subsidiary getSubsidiary() {
		return this.subsidiary;
	}

	public void setSubsidiary(Subsidiary subsidiary) {
		this.subsidiary = subsidiary;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
