package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * VariableType generated by hbm2java
 */
public class VariableType implements java.io.Serializable {

	private String variableTypeId;
	private String variableType;
	private BigDecimal numberInSequence;
	private String screenName;
	private Set<Variable> variables = new HashSet<Variable>(0);

	public VariableType() {
	}

	public VariableType(String variableTypeId, String variableType) {
		this.variableTypeId = variableTypeId;
		this.variableType = variableType;
	}

	public VariableType(String variableTypeId, String variableType,
			BigDecimal numberInSequence, String screenName,
			Set<Variable> variables) {
		this.variableTypeId = variableTypeId;
		this.variableType = variableType;
		this.numberInSequence = numberInSequence;
		this.screenName = screenName;
		this.variables = variables;
	}

	public String getVariableTypeId() {
		return this.variableTypeId;
	}

	public void setVariableTypeId(String variableTypeId) {
		this.variableTypeId = variableTypeId;
	}

	public String getVariableType() {
		return this.variableType;
	}

	public void setVariableType(String variableType) {
		this.variableType = variableType;
	}

	public BigDecimal getNumberInSequence() {
		return this.numberInSequence;
	}

	public void setNumberInSequence(BigDecimal numberInSequence) {
		this.numberInSequence = numberInSequence;
	}

	public String getScreenName() {
		return this.screenName;
	}

	public void setScreenName(String screenName) {
		this.screenName = screenName;
	}

	public Set<Variable> getVariables() {
		return this.variables;
	}

	public void setVariables(Set<Variable> variables) {
		this.variables = variables;
	}

}
