package com.cardiodx.db.waban.table;

// Generated Jul 14, 2011 12:30:41 PM by Hibernate Tools 3.4.0.CR1

/**
 * WorkflowSubWorkflow generated by hbm2java
 */
public class WorkflowSubWorkflow implements java.io.Serializable {

	private WorkflowSubWorkflowId id;

	public WorkflowSubWorkflow() {
	}

	public WorkflowSubWorkflow(WorkflowSubWorkflowId id) {
		this.id = id;
	}

	public WorkflowSubWorkflowId getId() {
		return this.id;
	}

	public void setId(WorkflowSubWorkflowId id) {
		this.id = id;
	}

}
